export const GET_EXCURSION_TYPES = 'GET_EXCURSION_TYPES';
export const GET_EXCURSION_TYPES_PENDING = 'GET_EXCURSION_TYPES_PENDING';
export const GET_EXCURSION_TYPES_FULFILLED = 'GET_EXCURSION_TYPES_FULFILLED';
export const GET_EXCURSION_TYPES_REJECTED = 'GET_EXCURSION_TYPES_REJECTED';
export const GET_EXCURSION_BY_FILTER = 'GET_EXCURSION_BY_FILTER';
export const GET_EXCURSION_BY_FILTER_PENDING =
  'GET_EXCURSION_BY_FILTER_PENDING';
export const GET_EXCURSION_BY_FILTER_FULFILLED =
  'GET_EXCURSION_BY_FILTER_FULFILLED';
export const GET_EXCURSION_BY_FILTER_REJECTED =
  'GET_EXCURSION_BY_FILTER_REJECTED';
export const RESET_STATUS_EXCURSION = 'RESET_STATUS_EXCURSION';
export const GET_EXCURSION_BY_ID = 'GET_EXCURSION_BY_ID';
export const GET_EXCURSION_BY_ID_PENDING = 'GET_EXCURSION_BY_ID_PENDING';
export const GET_EXCURSION_BY_ID_REJECTED = 'GET_EXCURSION_BY_ID_REJECTED';
export const GET_EXCURSION_BY_ID_FULFILLED = 'GET_EXCURSION_BY_ID_FULFILLED';
export const GET_EXCRUSION_DETAIL = 'GET_EXCRUSION_DETAIL';
export const GET_EXCRUSION_DETAIL_PENDING = 'GET_EXCRUSION_DETAIL_PENDING';
export const GET_EXCRUSION_DETAIL_REJECTED = 'GET_EXCRUSION_DETAIL_REJECTED';
export const GET_EXCRUSION_DETAIL_FULFILLED = 'GET_EXCRUSION_DETAIL_FULFILLED';
export const RESET_GET_EXCRUSION_DETAIL = 'RESET_GET_EXCRUSION_DETAIL';
