export const dummy = {
  Departures: [
    {
      Address:
        'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
      City: {
        Id: 'JAKARTA',
        Name: 'Jakarta',
        ImageUrl: '',
        Region: {
          Id: 'JAKARTA',
          Code: null,
          Name: 'Jakarta',
          ImageUrl:
            'http://agenfiforlif.mc468.com/wp-content/uploads/2016/06/DKI-Jakarta.jpg',
        },
        Country: {
          Id: 'ID',
          Code: '+62',
          Name: 'Indonesia',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
        },
        UTC: 7,
      },
      Date: '2019-11-01T08:00:00',
      Day: 1,
      Note: null,
      Place: 'Soekarno-Hatta International Airport',
      PlaceId: 2,
      PlaceType: 'Airport',
      Region: 'JABAR',
      TransferType: 'Movement_departure',
      NextDay: false,
    },
    {
      Address:
        'Jalan Pajajaran No.156, Husen Sastranegara, Cicendo, Kota Bandung, Jawa Barat 40174',
      City: {
        Id: 'BANDUNG',
        Name: 'Bandung',
        ImageUrl: '',
        Region: {
          Id: 'JABAR',
          Code: null,
          Name: 'Jawa Barat',
          ImageUrl:
            'https://dolandolen.com/wp-content/uploads/2015/08/nusa-tenggara-barat-cover.jpg',
        },
        Country: {
          Id: 'ID',
          Code: '+62',
          Name: 'Indonesia',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
        },
        UTC: 7,
      },
      Date: '2019-11-01T10:00:00',
      Day: 1,
      Note: null,
      Place: 'Husein Sastranegara International Airport',
      PlaceId: 10,
      PlaceType: 'Airport',
      Region: 'JABAR',
      TransferType: 'Movement_arrival',
      NextDay: false,
    },
  ],
  MainPrograms: [
    {
      AccommodationSummary: {
        CheckIn: '2019-11-01T14:00:00',
        CheckOut: '2019-11-03T10:00:00',
        Address: 'Jl. Cihampelas No. 125-127 Bandung',
        AccommodationProfileId: 92,
        Allocations: {
          ChildExtraBedPax: 0,
          ChildSharingRoomPax: 0,
          ChildSingleRoomPax: 0,
          ExtraBedPax: 0,
          NoBedPax: 0,
          SharingBedPax: 0,
          SharingRoomPax: 1,
          SingleRoomPax: 0,
        },
        DateTime: '2019-11-01T00:00:00',
        Name: 'Aston Tropicana Cihampelas',
        RoomName: 'Deluxe Room',
        RoomService: 'With_breakfast',
        RoomType: 'Double/Twin Sharing',
        SeqNumber: null,
        ServiceItemId: 4030,
        ImageUrl:
          'https://touressapi.azurewebsites.net/Content/imgSrc/Accommodations/aston-tropicana-gallery-Deluxe-Twin.jpg',
      },
      City: {
        Id: 'BANDUNG',
        Name: 'Bandung',
        ImageUrl: '',
        Region: {
          Id: 'JABAR',
          Code: null,
          Name: 'Jawa Barat',
          ImageUrl:
            'https://dolandolen.com/wp-content/uploads/2015/08/nusa-tenggara-barat-cover.jpg',
        },
        Country: {
          Id: 'ID',
          Code: '+62',
          Name: 'Indonesia',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
        },
        UTC: 7,
      },
      Date: '2019-11-01T00:00:00',
      Day: 1,
      LeavingDate: '2019-11-03T00:00:00',
      Note: null,
      Region: 'JABAR',
      TotalDays: 3,
      NextDay: false,
    },
  ],
  Returns: [
    {
      Address:
        'Jalan Pajajaran No.156, Husen Sastranegara, Cicendo, Kota Bandung, Jawa Barat 40174',
      City: {
        Id: 'BANDUNG',
        Name: 'Bandung',
        ImageUrl: '',
        Region: {
          Id: 'JABAR',
          Code: null,
          Name: 'Jawa Barat',
          ImageUrl:
            'https://dolandolen.com/wp-content/uploads/2015/08/nusa-tenggara-barat-cover.jpg',
        },
        Country: {
          Id: 'ID',
          Code: '+62',
          Name: 'Indonesia',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
        },
        UTC: 7,
      },
      Date: '2019-11-03T14:00:00',
      Day: 2,
      Note: null,
      Place: 'Husein Sastranegara International Airport',
      PlaceId: 10,
      PlaceType: 'Airport',
      Region: 'JABAR',
      TransferType: 'Movement_departure',
      NextDay: false,
    },
    {
      Address:
        'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
      City: {
        Id: 'JAKARTA',
        Name: 'Jakarta',
        ImageUrl: '',
        Region: {
          Id: 'JAKARTA',
          Code: null,
          Name: 'Jakarta',
          ImageUrl:
            'http://agenfiforlif.mc468.com/wp-content/uploads/2016/06/DKI-Jakarta.jpg',
        },
        Country: {
          Id: 'ID',
          Code: '+62',
          Name: 'Indonesia',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
        },
        UTC: 7,
      },
      Date: '2019-11-03T16:00:00',
      Day: 1,
      Note: null,
      Place: 'Soekarno-Hatta International Airport',
      PlaceId: 2,
      PlaceType: 'Airport',
      Region: 'JABAR',
      TransferType: 'Movement_arrival',
      NextDay: false,
    },
  ],
};

export const Room = {
  ChildExtraBedQty: 0,
  ChildSharingRoomQty: 0,
  ChildSingleRoomQty: 0,
  ExtraBedQty: 0,
  NoBed: 0,
  SharingBedQty: 0,
  SharingRoomQty: 1,
  SingleRoomQty: 0,
};

export const dataDummy = {
  Departures: [
    {
      Address: 'Tangerang City, Banten 19120',
      City: {
        Id: 'JAKARTA',
        ImageUrl: null,
        Name: 'Jakarta',
        UTC: 7,
      },
      Date: '2019-12-30T09:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Soekarno-Hatta International Airport',
      PlaceId: 2,
      PlaceType: 'Airport',
      Region: 'JAKARTA',
      TransferType: 'Movement_departure',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
    {
      Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
      City: {
        Id: 'SURABAYA',
        ImageUrl: null,
        Name: 'Surabaya',
        UTC: 7,
      },
      Date: '2019-12-30T10:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Juanda International Airport',
      PlaceId: 27,
      PlaceType: 'Airport',
      Region: 'JAWATIMUR',
      TransferType: 'Movement_arrival',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 14400,
        IsTransit: true,
        IsAllowedActivity: false,
      },
    },
    {
      Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
      City: {
        Id: 'SURABAYA',
        ImageUrl: null,
        Name: 'Surabaya',
        UTC: 7,
      },
      Date: '2019-12-30T13:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Juanda International Airport',
      PlaceId: 27,
      PlaceType: 'Airport',
      Region: 'JAWATIMUR',
      TransferType: 'Movement_departure',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 14400,
        IsTransit: true,
        IsAllowedActivity: false,
      },
    },
    {
      Address:
        'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
      City: {
        Id: 'KUTA',
        ImageUrl: null,
        Name: 'Kuta',
        UTC: 7,
      },
      Date: '2019-12-30T14:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Ngurah Rai International Airport',
      PlaceId: 1,
      PlaceType: 'Airport',
      Region: 'BALI',
      TransferType: 'Movement_arrival',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
  ],
  MainPrograms: [
    {
      AccommodationSummary: {
        CheckIn: '2019-12-30T14:35:00',
        CheckOut: '2019-12-31T10:00:00',
        Address:
          'Jl Legian No 328 - Legian Kelod Kuta - Kuta, Bali 80361 BALI - INDONESIA',
        AccommodationProfileId: 23,
        Allocations: {
          ChildExtraBedPax: 0,
          ChildSharingRoomPax: 0,
          ChildSingleRoomPax: 0,
          ExtraBedPax: 0,
          NoBedPax: 0,
          SharingBedPax: 0,
          SharingRoomPax: 2,
          SingleRoomPax: 0,
        },
        DateTime: '2019-12-30T00:00:00',
        Name: 'Mercure Legian',
        RoomName: 'Deluxe Balcony',
        RoomService: 'With_breakfast',
        RoomType: 'Double/Twin Sharing',
        SeqNumber: null,
        ServiceItemId: 6277,
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/Accommodations/b98efc92-6504-454a-bfe3-e302dbe17ec0dubai-2057585_1920.jpg.jpg',
      },
      City: {
        Id: 'KUTA',
        Name: 'Kuta',
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/City/0ed74a00-3093-4c16-987e-e64b856f1454travel-3239795_1920.jpg.jpg',
        UTC: 8,
        Region: {
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/upload/beautiful-beach.jpg',
          Id: 'BALI',
          Name: 'Bali',
        },
        Country: {
          Code: '+62',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
          Id: 'ID',
          Name: 'Indonesia',
        },
      },
      Date: '2019-12-30T00:00:00',
      Day: 1,
      LeavingDate: '2019-12-31T00:00:00',
      Note: null,
      Region: 'BALI',
      TotalDays: 2,
      NextDay: false,
    },
    {
      Address:
        'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
      City: {
        Id: 'KUTA',
        ImageUrl: null,
        Name: 'Kuta',
        UTC: 7,
      },
      Date: '2019-12-31T14:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Ngurah Rai International Airport',
      PlaceId: 1,
      PlaceType: 'Airport',
      Region: 'BALI',
      TransferType: 'Movement_departure',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
    {
      Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
      City: {
        Id: 'SURABAYA',
        ImageUrl: null,
        Name: 'Surabaya',
        UTC: 7,
      },
      Date: '2019-12-31T17:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Juanda International Airport',
      PlaceId: 27,
      PlaceType: 'Airport',
      Region: 'JAWATIMUR',
      TransferType: 'Movement_arrival',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 14400,
        IsTransit: true,
        IsAllowedActivity: false,
      },
    },
    {
      AccommodationSummary: {
        CheckIn: '2019-12-31T18:35:00',
        CheckOut: '2020-01-01T10:00:00',
        Address:
          'Jl Legian No 328 - Legian Kelod Kuta - Kuta, Bali 80361 BALI - INDONESIA',
        AccommodationProfileId: 23,
        Allocations: {
          ChildExtraBedPax: 0,
          ChildSharingRoomPax: 0,
          ChildSingleRoomPax: 0,
          ExtraBedPax: 0,
          NoBedPax: 0,
          SharingBedPax: 0,
          SharingRoomPax: 2,
          SingleRoomPax: 0,
        },
        DateTime: '2019-12-31T00:00:00',
        Name: 'Mercure Legian',
        RoomName: 'Deluxe Balcony',
        RoomService: 'With_breakfast',
        RoomType: 'Double/Twin Sharing',
        SeqNumber: null,
        ServiceItemId: 6277,
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/Accommodations/b98efc92-6504-454a-bfe3-e302dbe17ec0dubai-2057585_1920.jpg.jpg',
      },
      City: {
        Id: 'SURABAYA',
        Name: 'Surabaya',
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/City/0ed74a00-3093-4c16-987e-e64b856f1454travel-3239795_1920.jpg.jpg',
        UTC: 8,
        Region: {
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/upload/beautiful-beach.jpg',
          Id: 'BALI',
          Name: 'Bali',
        },
        Country: {
          Code: '+62',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
          Id: 'ID',
          Name: 'Indonesia',
        },
      },
      Date: '2019-12-31T00:00:00',
      Day: 1,
      LeavingDate: '2020-01-01T00:00:00',
      Note: null,
      Region: 'BALI',
      TotalDays: 2,
      NextDay: false,
    },
    {
      Address:
        'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
      City: {
        Id: 'KUTA',
        ImageUrl: null,
        Name: 'Kuta',
        UTC: 7,
      },
      Date: '2019-12-31T14:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Ngurah Rai International Airport',
      PlaceId: 1,
      PlaceType: 'Airport',
      Region: 'BALI',
      TransferType: 'Movement_departure',
      Ticket: {
        ServiceItemId: '1',
        PNR: '',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
    {
      Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
      City: {
        Id: 'SURABAYA',
        ImageUrl: null,
        Name: 'Surabaya',
        UTC: 7,
      },
      Date: '2019-12-31T17:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Juanda International Airport',
      PlaceId: 27,
      PlaceType: 'Airport',
      Region: 'JAWATIMUR',
      TransferType: 'Movement_arrival',
      Ticket: {
        ServiceItemId: '1',
        PNR: '',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 14400,
        IsTransit: true,
        IsAllowedActivity: false,
      },
    },
    {
      AccommodationSummary: {
        CheckIn: '2019-12-31T18:35:00',
        CheckOut: '2020-01-01T10:00:00',
        Address:
          'Jl Legian No 328 - Legian Kelod Kuta - Kuta, Bali 80361 BALI - INDONESIA',
        AccommodationProfileId: 23,
        Allocations: {
          ChildExtraBedPax: 0,
          ChildSharingRoomPax: 0,
          ChildSingleRoomPax: 0,
          ExtraBedPax: 0,
          NoBedPax: 0,
          SharingBedPax: 0,
          SharingRoomPax: 2,
          SingleRoomPax: 0,
        },
        DateTime: '2019-12-31T00:00:00',
        Name: 'Mercure Legian',
        RoomName: 'Deluxe Balcony',
        RoomService: 'With_breakfast',
        RoomType: 'Double/Twin Sharing',
        SeqNumber: null,
        ServiceItemId: 6277,
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/Accommodations/b98efc92-6504-454a-bfe3-e302dbe17ec0dubai-2057585_1920.jpg.jpg',
      },
      City: {
        Id: 'SURABAYA',
        Name: 'Surabaya',
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/City/0ed74a00-3093-4c16-987e-e64b856f1454travel-3239795_1920.jpg.jpg',
        UTC: 8,
        Region: {
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/upload/beautiful-beach.jpg',
          Id: 'BALI',
          Name: 'Bali',
        },
        Country: {
          Code: '+62',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
          Id: 'ID',
          Name: 'Indonesia',
        },
      },
      Date: '2019-12-31T00:00:00',
      Day: 1,
      LeavingDate: '2020-01-01T00:00:00',
      Note: null,
      Region: 'BALI',
      TotalDays: 2,
      NextDay: false,
    },
  ],
  Returns: [
    {
      Address:
        'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
      City: {
        Id: 'KUTA',
        Name: 'Kuta',
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/City/0ed74a00-3093-4c16-987e-e64b856f1454travel-3239795_1920.jpg.jpg',
        Region: {
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/upload/beautiful-beach.jpg',
          Id: 'BALI',
          Name: 'Bali',
        },
        Country: {
          Code: '+62',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
          Id: 'ID',
          Name: 'Indonesia',
        },
      },
      UTC: 8,
      Date: '2020-01-01T12:00:00',
      Day: 2,
      Note: null,
      Place: 'Ngurah Rai International Airport',
      PlaceId: 1,
      PlaceType: 'Airport',
      Region: 'BALI',
      TransferType: 'Movement_departure',
      NextDay: false,
      RequestFrom: 'BALI',
      Ticket: {
        ServiceItemId: '',
        PNR: '',
        FlightNumber: '345',
        AirlineProfileName: '',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
    {
      Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
      City: {
        Id: 'SURABAYA',
        ImageUrl: null,
        Name: 'Surabaya',
        UTC: 7,
      },
      Date: '2020-01-01T13:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Juanda International Airport',
      PlaceId: 27,
      PlaceType: 'Airport',
      Region: 'JAWATIMUR',
      TransferType: 'Movement_arrival',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 14400,
        IsTransit: true,
        IsAllowedActivity: false,
      },
    },
  ],
};

export const dataFlight = [
  {
    Id: 1,
    RouteName: 'CGK-DPS',
    AirlineLogo: null,
    AirlineName: 'Garuda Indonesia',
    ScheduleItems: [
      {
        Id: 1,
        FlightCode: '1234',
        DeparturePlace: {
          Id: 2,
          Name: 'Soekarno-Hatta International Airport',
          Code: 'CGK',
          Address: 'Tangerang City, Banten 19120',
          CityId: 'JAKARTA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1154,
            Address1: 'Tangerang City, Banten 19120',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'JAKARTA',
            Area: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            City: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Region: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        DeparturePlaceTime: '2019-11-26T09:00:00',
        ArrivalPlace: {
          Id: 1,
          Name: 'Ngurah Rai International Airport',
          Code: 'DPS',
          Address:
            'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
          CityId: 'KUTA',
          PlaceType: 'Airport',
          City: {
            UTC: 8,
            ImageUrl: null,
            Id: 'KUTA',
            Name: 'Kuta',
          },
          Region: {
            ImageUrl: null,
            Id: 'BALI',
            Name: 'Bali',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1165,
            Address1:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'BADUNG',
            Area: {
              Id: 'BADUNG',
              Name: 'Badung',
            },
            City: {
              Id: 'KUTA',
              Name: 'Kuta',
            },
            Region: {
              Id: 'BALI',
              Name: 'Bali',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
            Coordinate: null,
          },
          IsPopular: true,
        },
        ArrivalPlaceTime: '2019-11-26T14:00:00',
        Duration: '3600',
        Class: 'Economy',
        ConnectionCount: 1,
        Connection: [
          {
            Class: 'Economy',
            FlightCode: '1234',
            Duration: '3600',
            IsAllowedActivity: false,
            DeparturePlace: {
              Id: 2,
              Name: 'Soekarno-Hatta International Airport',
              Code: 'CGK',
              Address: 'Tangerang City, Banten 19120',
              CityId: 'JAKARTA',
              PlaceType: 'Airport',
              City: {
                UTC: 7,
                ImageUrl: null,
                Id: 'JAKARTA',
                Name: 'Jakarta',
              },
              Region: {
                ImageUrl: null,
                Id: 'JAKARTA',
                Name: 'Jakarta',
              },
              Country: {
                Code: null,
                ImageUrl: null,
                Id: 'ID',
                Name: 'Indonesia',
              },
              AddressObject: {
                Id: 1154,
                Address1: 'Tangerang City, Banten 19120',
                Address2: '',
                Address3: '',
                PostalCode: '',
                Landmark: '',
                AreaId: 'JAKARTA',
                Area: {
                  Id: 'JAKARTA',
                  Name: 'Jakarta',
                },
                City: {
                  Id: 'JAKARTA',
                  Name: 'Jakarta',
                },
                Region: {
                  Id: 'JAKARTA',
                  Name: 'Jakarta',
                },
                Country: {
                  Id: 'ID',
                  Name: 'Indonesia',
                },
                AddressString:
                  'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
                Coordinate: null,
              },
              IsPopular: false,
            },
            DepartureTime: '2019-11-26T09:00:00',
            ArrivalPlace: {
              Id: 27,
              Name: 'Juanda International Airport',
              Code: 'SUB',
              Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
              CityId: 'SURABAYA',
              PlaceType: 'Airport',
              City: {
                UTC: 7,
                ImageUrl: null,
                Id: 'SURABAYA',
                Name: 'Surabaya',
              },
              Region: {
                ImageUrl: null,
                Id: 'JAWATIMUR',
                Name: 'Jawa Timur',
              },
              Country: {
                Code: null,
                ImageUrl: null,
                Id: 'ID',
                Name: 'Indonesia',
              },
              AddressObject: {
                Id: 799,
                Address1: 'Jalan Ir. Haji Juanda Surabaya 61253',
                Address2: '',
                Address3: '',
                PostalCode: '',
                Landmark: '',
                AreaId: 'SURABAYA',
                Area: {
                  Id: 'SURABAYA',
                  Name: 'Surabaya',
                },
                City: {
                  Id: 'SURABAYA',
                  Name: 'Surabaya',
                },
                Region: {
                  Id: 'JAWATIMUR',
                  Name: 'Jawa Timur',
                },
                Country: {
                  Id: 'ID',
                  Name: 'Indonesia',
                },
                AddressString:
                  'Jalan Ir. Haji Juanda Surabaya 61253, Surabaya, Surabaya, Jawa Timur, Indonesia',
                Coordinate: null,
              },
              IsPopular: false,
            },
            ArrivalTime: '2019-11-26T10:00:00',
          },
          {
            Class: 'Economy',
            FlightCode: '1234',
            Duration: '3600',
            IsAllowedActivity: false,
            DeparturePlace: {
              Id: 27,
              Name: 'Juanda International Airport',
              Code: 'SUB',
              Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
              CityId: 'SURABAYA',
              PlaceType: 'Airport',
              City: {
                UTC: 7,
                ImageUrl: null,
                Id: 'SURABAYA',
                Name: 'Surabaya',
              },
              Region: {
                ImageUrl: null,
                Id: 'JAWATIMUR',
                Name: 'Jawa Timur',
              },
              Country: {
                Code: null,
                ImageUrl: null,
                Id: 'ID',
                Name: 'Indonesia',
              },
              AddressObject: {
                Id: 799,
                Address1: 'Jalan Ir. Haji Juanda Surabaya 61253',
                Address2: '',
                Address3: '',
                PostalCode: '',
                Landmark: '',
                AreaId: 'SURABAYA',
                Area: {
                  Id: 'SURABAYA',
                  Name: 'Surabaya',
                },
                City: {
                  Id: 'SURABAYA',
                  Name: 'Surabaya',
                },
                Region: {
                  Id: 'JAWATIMUR',
                  Name: 'Jawa Timur',
                },
                Country: {
                  Id: 'ID',
                  Name: 'Indonesia',
                },
                AddressString:
                  'Jalan Ir. Haji Juanda Surabaya 61253, Surabaya, Surabaya, Jawa Timur, Indonesia',
                Coordinate: null,
              },
              IsPopular: false,
            },
            DepartureTime: '2019-11-26T13:00:00',
            ArrivalPlace: {
              Id: 1,
              Name: 'Ngurah Rai International Airport',
              Code: 'DPS',
              Address:
                'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
              CityId: 'KUTA',
              PlaceType: 'Airport',
              City: {
                UTC: 8,
                ImageUrl: null,
                Id: 'KUTA',
                Name: 'Kuta',
              },
              Region: {
                ImageUrl: null,
                Id: 'BALI',
                Name: 'Bali',
              },
              Country: {
                Code: null,
                ImageUrl: null,
                Id: 'ID',
                Name: 'Indonesia',
              },
              AddressObject: {
                Id: 1165,
                Address1:
                  'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621',
                Address2: '',
                Address3: '',
                PostalCode: '',
                Landmark: '',
                AreaId: 'BADUNG',
                Area: {
                  Id: 'BADUNG',
                  Name: 'Badung',
                },
                City: {
                  Id: 'KUTA',
                  Name: 'Kuta',
                },
                Region: {
                  Id: 'BALI',
                  Name: 'Bali',
                },
                Country: {
                  Id: 'ID',
                  Name: 'Indonesia',
                },
                AddressString:
                  'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
                Coordinate: null,
              },
              IsPopular: true,
            },
            ArrivalTime: '2019-11-26T14:00:00',
          },
        ],
      },
    ],
  },
];

export const moreDestination = [
  {
    Id: 1,
    RouteName: 'CGK-DPS-SUB',
    AirlineLogo: null,
    AirlineName: 'Garuda Indonesia',
    IsRoundTrip: true,
    ScheduleItems: [
      {
        Id: 1,
        FlightCode: '1234',
        DeparturePlace: {
          Id: 2,
          Name: 'Soekarno-Hatta International Airport',
          Code: 'CGK',
          Address: 'Tangerang City, Banten 19120',
          CityId: 'JAKARTA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1154,
            Address1: 'Tangerang City, Banten 19120',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'JAKARTA',
            Area: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            City: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Region: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        DeparturePlaceTime: '2019-11-26T09:00:00',
        ArrivalPlace: {
          Id: 1,
          Name: 'Ngurah Rai International Airport',
          Code: 'DPS',
          Address:
            'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
          CityId: 'KUTA',
          PlaceType: 'Airport',
          City: {
            UTC: 8,
            ImageUrl: null,
            Id: 'KUTA',
            Name: 'Kuta',
          },
          Region: {
            ImageUrl: null,
            Id: 'BALI',
            Name: 'Bali',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1165,
            Address1:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'BADUNG',
            Area: {
              Id: 'BADUNG',
              Name: 'Badung',
            },
            City: {
              Id: 'KUTA',
              Name: 'Kuta',
            },
            Region: {
              Id: 'BALI',
              Name: 'Bali',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
            Coordinate: null,
          },
          IsPopular: true,
        },
        ArrivalPlaceTime: '2019-11-26T11:00:00',
        Duration: '3600',
        Class: 'Economy',
        ConnectionCount: 0,
        Connection: [],
      },
      {
        Id: 2,
        FlightCode: '1234',
        DeparturePlace: {
          Id: 1,
          Name: 'Ngurah Rai International Airport',
          Code: 'DPS',
          Address:
            'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
          CityId: 'KUTA',
          PlaceType: 'Airport',
          City: {
            UTC: 8,
            ImageUrl: null,
            Id: 'KUTA',
            Name: 'Kuta',
          },
          Region: {
            ImageUrl: null,
            Id: 'BALI',
            Name: 'Bali',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1165,
            Address1:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'BADUNG',
            Area: {
              Id: 'BADUNG',
              Name: 'Badung',
            },
            City: {
              Id: 'KUTA',
              Name: 'Kuta',
            },
            Region: {
              Id: 'BALI',
              Name: 'Bali',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
            Coordinate: null,
          },
          IsPopular: true,
        },
        DeparturePlaceTime: '2019-11-30T09:00:00',
        ArrivalPlace: {
          Id: 27,
          Name: 'Juanda International Airport',
          Code: 'SUB',
          Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
          CityId: 'SURABAYA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'SURABAYA',
            Name: 'Surabaya',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAWATIMUR',
            Name: 'Jawa Timur',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 799,
            Address1: 'Jalan Ir. Haji Juanda Surabaya 61253',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'SURABAYA',
            Area: {
              Id: 'SURABAYA',
              Name: 'Surabaya',
            },
            City: {
              Id: 'SURABAYA',
              Name: 'Surabaya',
            },
            Region: {
              Id: 'JAWATIMUR',
              Name: 'Jawa Timur',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Ir. Haji Juanda Surabaya 61253, Surabaya, Surabaya, Jawa Timur, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        ArrivalPlaceTime: '2019-12-30T10:00:00',
        Duration: '3600',
        Class: 'Economy',
        ConnectionCount: 0,
        Connection: [],
      },
      {
        Id: 3,
        FlightCode: '1234',
        DeparturePlace: {
          Id: 27,
          Name: 'Juanda International Airport',
          Code: 'SUB',
          Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
          CityId: 'SURABAYA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'SURABAYA',
            Name: 'Surabaya',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAWATIMUR',
            Name: 'Jawa Timur',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 799,
            Address1: 'Jalan Ir. Haji Juanda Surabaya 61253',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'SURABAYA',
            Area: {
              Id: 'SURABAYA',
              Name: 'Surabaya',
            },
            City: {
              Id: 'SURABAYA',
              Name: 'Surabaya',
            },
            Region: {
              Id: 'JAWATIMUR',
              Name: 'Jawa Timur',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Ir. Haji Juanda Surabaya 61253, Surabaya, Surabaya, Jawa Timur, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        DeparturePlaceTime: '2019-12-02T09:00:00',
        ArrivalPlace: {
          Id: 2,
          Name: 'Soekarno-Hatta International Airport',
          Code: 'CGK',
          Address: 'Tangerang City, Banten 19120',
          CityId: 'JAKARTA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1154,
            Address1: 'Tangerang City, Banten 19120',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'JAKARTA',
            Area: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            City: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Region: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        ArrivalPlaceTime: '2019-12-02T10:00:00',
        Duration: '3600',
        Class: 'Economy',
        ConnectionCount: 0,
        Connection: [],
      },
    ],
  },
];
export const dummy = {
  Departures: [
    {
      Address:
        'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
      City: {
        Id: 'JAKARTA',
        Name: 'Jakarta',
        ImageUrl: '',
        Region: {
          Id: 'JAKARTA',
          Code: null,
          Name: 'Jakarta',
          ImageUrl:
            'http://agenfiforlif.mc468.com/wp-content/uploads/2016/06/DKI-Jakarta.jpg',
        },
        Country: {
          Id: 'ID',
          Code: '+62',
          Name: 'Indonesia',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
        },
        UTC: 7,
      },
      Date: '2019-11-01T08:00:00',
      Day: 1,
      Note: null,
      Place: 'Soekarno-Hatta International Airport',
      PlaceId: 2,
      PlaceType: 'Airport',
      Region: 'JABAR',
      TransferType: 'Movement_departure',
      NextDay: false,
    },
    {
      Address:
        'Jalan Pajajaran No.156, Husen Sastranegara, Cicendo, Kota Bandung, Jawa Barat 40174',
      City: {
        Id: 'BANDUNG',
        Name: 'Bandung',
        ImageUrl: '',
        Region: {
          Id: 'JABAR',
          Code: null,
          Name: 'Jawa Barat',
          ImageUrl:
            'https://dolandolen.com/wp-content/uploads/2015/08/nusa-tenggara-barat-cover.jpg',
        },
        Country: {
          Id: 'ID',
          Code: '+62',
          Name: 'Indonesia',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
        },
        UTC: 7,
      },
      Date: '2019-11-01T10:00:00',
      Day: 1,
      Note: null,
      Place: 'Husein Sastranegara International Airport',
      PlaceId: 10,
      PlaceType: 'Airport',
      Region: 'JABAR',
      TransferType: 'Movement_arrival',
      NextDay: false,
    },
  ],
  MainPrograms: [
    {
      AccommodationSummary: {
        CheckIn: '2019-11-01T14:00:00',
        CheckOut: '2019-11-03T10:00:00',
        Address: 'Jl. Cihampelas No. 125-127 Bandung',
        AccommodationProfileId: 92,
        Allocations: {
          ChildExtraBedPax: 0,
          ChildSharingRoomPax: 0,
          ChildSingleRoomPax: 0,
          ExtraBedPax: 0,
          NoBedPax: 0,
          SharingBedPax: 0,
          SharingRoomPax: 1,
          SingleRoomPax: 0,
        },
        DateTime: '2019-11-01T00:00:00',
        Name: 'Aston Tropicana Cihampelas',
        RoomName: 'Deluxe Room',
        RoomService: 'With_breakfast',
        RoomType: 'Double/Twin Sharing',
        SeqNumber: null,
        ServiceItemId: 4030,
        ImageUrl:
          'https://touressapi.azurewebsites.net/Content/imgSrc/Accommodations/aston-tropicana-gallery-Deluxe-Twin.jpg',
      },
      City: {
        Id: 'BANDUNG',
        Name: 'Bandung',
        ImageUrl: '',
        Region: {
          Id: 'JABAR',
          Code: null,
          Name: 'Jawa Barat',
          ImageUrl:
            'https://dolandolen.com/wp-content/uploads/2015/08/nusa-tenggara-barat-cover.jpg',
        },
        Country: {
          Id: 'ID',
          Code: '+62',
          Name: 'Indonesia',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
        },
        UTC: 7,
      },
      Date: '2019-11-01T00:00:00',
      Day: 1,
      LeavingDate: '2019-11-03T00:00:00',
      Note: null,
      Region: 'JABAR',
      TotalDays: 3,
      NextDay: false,
    },
  ],
  Returns: [
    {
      Address:
        'Jalan Pajajaran No.156, Husen Sastranegara, Cicendo, Kota Bandung, Jawa Barat 40174',
      City: {
        Id: 'BANDUNG',
        Name: 'Bandung',
        ImageUrl: '',
        Region: {
          Id: 'JABAR',
          Code: null,
          Name: 'Jawa Barat',
          ImageUrl:
            'https://dolandolen.com/wp-content/uploads/2015/08/nusa-tenggara-barat-cover.jpg',
        },
        Country: {
          Id: 'ID',
          Code: '+62',
          Name: 'Indonesia',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
        },
        UTC: 7,
      },
      Date: '2019-11-03T14:00:00',
      Day: 2,
      Note: null,
      Place: 'Husein Sastranegara International Airport',
      PlaceId: 10,
      PlaceType: 'Airport',
      Region: 'JABAR',
      TransferType: 'Movement_departure',
      NextDay: false,
    },
    {
      Address:
        'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
      City: {
        Id: 'JAKARTA',
        Name: 'Jakarta',
        ImageUrl: '',
        Region: {
          Id: 'JAKARTA',
          Code: null,
          Name: 'Jakarta',
          ImageUrl:
            'http://agenfiforlif.mc468.com/wp-content/uploads/2016/06/DKI-Jakarta.jpg',
        },
        Country: {
          Id: 'ID',
          Code: '+62',
          Name: 'Indonesia',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
        },
        UTC: 7,
      },
      Date: '2019-11-03T16:00:00',
      Day: 1,
      Note: null,
      Place: 'Soekarno-Hatta International Airport',
      PlaceId: 2,
      PlaceType: 'Airport',
      Region: 'JABAR',
      TransferType: 'Movement_arrival',
      NextDay: false,
    },
  ],
};

export const Room = {
  ChildExtraBedQty: 0,
  ChildSharingRoomQty: 0,
  ChildSingleRoomQty: 0,
  ExtraBedQty: 0,
  NoBed: 0,
  SharingBedQty: 0,
  SharingRoomQty: 1,
  SingleRoomQty: 0,
};

export const dataDummy = {
  Departures: [
    {
      Address: 'Tangerang City, Banten 19120',
      City: {
        Id: 'JAKARTA',
        ImageUrl: null,
        Name: 'Jakarta',
        UTC: 7,
      },
      Date: '2019-12-30T09:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Soekarno-Hatta International Airport',
      PlaceId: 2,
      PlaceType: 'Airport',
      Region: 'JAKARTA',
      TransferType: 'Movement_departure',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
    {
      Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
      City: {
        Id: 'SURABAYA',
        ImageUrl: null,
        Name: 'Surabaya',
        UTC: 7,
      },
      Date: '2019-12-30T10:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Juanda International Airport',
      PlaceId: 27,
      PlaceType: 'Airport',
      Region: 'JAWATIMUR',
      TransferType: 'Movement_arrival',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 14400,
        IsTransit: true,
        IsAllowedActivity: false,
      },
    },
    {
      Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
      City: {
        Id: 'SURABAYA',
        ImageUrl: null,
        Name: 'Surabaya',
        UTC: 7,
      },
      Date: '2019-12-30T13:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Juanda International Airport',
      PlaceId: 27,
      PlaceType: 'Airport',
      Region: 'JAWATIMUR',
      TransferType: 'Movement_departure',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 14400,
        IsTransit: true,
        IsAllowedActivity: false,
      },
    },
    {
      Address:
        'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
      City: {
        Id: 'KUTA',
        ImageUrl: null,
        Name: 'Kuta',
        UTC: 7,
      },
      Date: '2019-12-30T14:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Ngurah Rai International Airport',
      PlaceId: 1,
      PlaceType: 'Airport',
      Region: 'BALI',
      TransferType: 'Movement_arrival',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
  ],
  MainPrograms: [
    {
      AccommodationSummary: {
        CheckIn: '2019-12-30T14:35:00',
        CheckOut: '2019-12-31T10:00:00',
        Address:
          'Jl Legian No 328 - Legian Kelod Kuta - Kuta, Bali 80361 BALI - INDONESIA',
        AccommodationProfileId: 23,
        Allocations: {
          ChildExtraBedPax: 0,
          ChildSharingRoomPax: 0,
          ChildSingleRoomPax: 0,
          ExtraBedPax: 0,
          NoBedPax: 0,
          SharingBedPax: 0,
          SharingRoomPax: 2,
          SingleRoomPax: 0,
        },
        DateTime: '2019-12-30T00:00:00',
        Name: 'Mercure Legian',
        RoomName: 'Deluxe Balcony',
        RoomService: 'With_breakfast',
        RoomType: 'Double/Twin Sharing',
        SeqNumber: null,
        ServiceItemId: 6277,
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/Accommodations/b98efc92-6504-454a-bfe3-e302dbe17ec0dubai-2057585_1920.jpg.jpg',
      },
      City: {
        Id: 'KUTA',
        Name: 'Kuta',
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/City/0ed74a00-3093-4c16-987e-e64b856f1454travel-3239795_1920.jpg.jpg',
        UTC: 8,
        Region: {
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/upload/beautiful-beach.jpg',
          Id: 'BALI',
          Name: 'Bali',
        },
        Country: {
          Code: '+62',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
          Id: 'ID',
          Name: 'Indonesia',
        },
      },
      Date: '2019-12-30T00:00:00',
      Day: 1,
      LeavingDate: '2019-12-31T00:00:00',
      Note: null,
      Region: 'BALI',
      TotalDays: 2,
      NextDay: false,
    },
    {
      Address:
        'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
      City: {
        Id: 'KUTA',
        ImageUrl: null,
        Name: 'Kuta',
        UTC: 7,
      },
      Date: '2019-12-31T14:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Ngurah Rai International Airport',
      PlaceId: 1,
      PlaceType: 'Airport',
      Region: 'BALI',
      TransferType: 'Movement_departure',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
    {
      Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
      City: {
        Id: 'SURABAYA',
        ImageUrl: null,
        Name: 'Surabaya',
        UTC: 7,
      },
      Date: '2019-12-31T17:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Juanda International Airport',
      PlaceId: 27,
      PlaceType: 'Airport',
      Region: 'JAWATIMUR',
      TransferType: 'Movement_arrival',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 14400,
        IsTransit: true,
        IsAllowedActivity: false,
      },
    },
    {
      AccommodationSummary: {
        CheckIn: '2019-12-31T18:35:00',
        CheckOut: '2020-01-01T10:00:00',
        Address:
          'Jl Legian No 328 - Legian Kelod Kuta - Kuta, Bali 80361 BALI - INDONESIA',
        AccommodationProfileId: 23,
        Allocations: {
          ChildExtraBedPax: 0,
          ChildSharingRoomPax: 0,
          ChildSingleRoomPax: 0,
          ExtraBedPax: 0,
          NoBedPax: 0,
          SharingBedPax: 0,
          SharingRoomPax: 2,
          SingleRoomPax: 0,
        },
        DateTime: '2019-12-31T00:00:00',
        Name: 'Mercure Legian',
        RoomName: 'Deluxe Balcony',
        RoomService: 'With_breakfast',
        RoomType: 'Double/Twin Sharing',
        SeqNumber: null,
        ServiceItemId: 6277,
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/Accommodations/b98efc92-6504-454a-bfe3-e302dbe17ec0dubai-2057585_1920.jpg.jpg',
      },
      City: {
        Id: 'SURABAYA',
        Name: 'Surabaya',
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/City/0ed74a00-3093-4c16-987e-e64b856f1454travel-3239795_1920.jpg.jpg',
        UTC: 8,
        Region: {
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/upload/beautiful-beach.jpg',
          Id: 'BALI',
          Name: 'Bali',
        },
        Country: {
          Code: '+62',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
          Id: 'ID',
          Name: 'Indonesia',
        },
      },
      Date: '2019-12-31T00:00:00',
      Day: 1,
      LeavingDate: '2020-01-01T00:00:00',
      Note: null,
      Region: 'BALI',
      TotalDays: 2,
      NextDay: false,
    },
    {
      Address:
        'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
      City: {
        Id: 'KUTA',
        ImageUrl: null,
        Name: 'Kuta',
        UTC: 7,
      },
      Date: '2019-12-31T14:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Ngurah Rai International Airport',
      PlaceId: 1,
      PlaceType: 'Airport',
      Region: 'BALI',
      TransferType: 'Movement_departure',
      Ticket: {
        ServiceItemId: '1',
        PNR: '',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
    {
      Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
      City: {
        Id: 'SURABAYA',
        ImageUrl: null,
        Name: 'Surabaya',
        UTC: 7,
      },
      Date: '2019-12-31T17:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Juanda International Airport',
      PlaceId: 27,
      PlaceType: 'Airport',
      Region: 'JAWATIMUR',
      TransferType: 'Movement_arrival',
      Ticket: {
        ServiceItemId: '1',
        PNR: '',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 14400,
        IsTransit: true,
        IsAllowedActivity: false,
      },
    },
    {
      AccommodationSummary: {
        CheckIn: '2019-12-31T18:35:00',
        CheckOut: '2020-01-01T10:00:00',
        Address:
          'Jl Legian No 328 - Legian Kelod Kuta - Kuta, Bali 80361 BALI - INDONESIA',
        AccommodationProfileId: 23,
        Allocations: {
          ChildExtraBedPax: 0,
          ChildSharingRoomPax: 0,
          ChildSingleRoomPax: 0,
          ExtraBedPax: 0,
          NoBedPax: 0,
          SharingBedPax: 0,
          SharingRoomPax: 2,
          SingleRoomPax: 0,
        },
        DateTime: '2019-12-31T00:00:00',
        Name: 'Mercure Legian',
        RoomName: 'Deluxe Balcony',
        RoomService: 'With_breakfast',
        RoomType: 'Double/Twin Sharing',
        SeqNumber: null,
        ServiceItemId: 6277,
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/Accommodations/b98efc92-6504-454a-bfe3-e302dbe17ec0dubai-2057585_1920.jpg.jpg',
      },
      City: {
        Id: 'SURABAYA',
        Name: 'Surabaya',
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/City/0ed74a00-3093-4c16-987e-e64b856f1454travel-3239795_1920.jpg.jpg',
        UTC: 8,
        Region: {
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/upload/beautiful-beach.jpg',
          Id: 'BALI',
          Name: 'Bali',
        },
        Country: {
          Code: '+62',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
          Id: 'ID',
          Name: 'Indonesia',
        },
      },
      Date: '2019-12-31T00:00:00',
      Day: 1,
      LeavingDate: '2020-01-01T00:00:00',
      Note: null,
      Region: 'BALI',
      TotalDays: 2,
      NextDay: false,
    },
  ],
  Returns: [
    {
      Address:
        'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
      City: {
        Id: 'KUTA',
        Name: 'Kuta',
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/City/0ed74a00-3093-4c16-987e-e64b856f1454travel-3239795_1920.jpg.jpg',
        Region: {
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/upload/beautiful-beach.jpg',
          Id: 'BALI',
          Name: 'Bali',
        },
        Country: {
          Code: '+62',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
          Id: 'ID',
          Name: 'Indonesia',
        },
      },
      UTC: 8,
      Date: '2020-01-01T12:00:00',
      Day: 2,
      Note: null,
      Place: 'Ngurah Rai International Airport',
      PlaceId: 1,
      PlaceType: 'Airport',
      Region: 'BALI',
      TransferType: 'Movement_departure',
      NextDay: false,
      RequestFrom: 'BALI',
      Ticket: {
        ServiceItemId: '',
        PNR: '',
        FlightNumber: '345',
        AirlineProfileName: '',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
    {
      Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
      City: {
        Id: 'SURABAYA',
        ImageUrl: null,
        Name: 'Surabaya',
        UTC: 7,
      },
      Date: '2020-01-01T13:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Juanda International Airport',
      PlaceId: 27,
      PlaceType: 'Airport',
      Region: 'JAWATIMUR',
      TransferType: 'Movement_arrival',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 14400,
        IsTransit: true,
        IsAllowedActivity: false,
      },
    },
  ],
};

export const dataFlight = [
  {
    Id: 1,
    RouteName: 'CGK-DPS',
    AirlineLogo: null,
    AirlineName: 'Garuda Indonesia',
    ScheduleItems: [
      {
        Id: 1,
        FlightCode: '1234',
        DeparturePlace: {
          Id: 2,
          Name: 'Soekarno-Hatta International Airport',
          Code: 'CGK',
          Address: 'Tangerang City, Banten 19120',
          CityId: 'JAKARTA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1154,
            Address1: 'Tangerang City, Banten 19120',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'JAKARTA',
            Area: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            City: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Region: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        DeparturePlaceTime: '2019-11-26T09:00:00',
        ArrivalPlace: {
          Id: 1,
          Name: 'Ngurah Rai International Airport',
          Code: 'DPS',
          Address:
            'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
          CityId: 'KUTA',
          PlaceType: 'Airport',
          City: {
            UTC: 8,
            ImageUrl: null,
            Id: 'KUTA',
            Name: 'Kuta',
          },
          Region: {
            ImageUrl: null,
            Id: 'BALI',
            Name: 'Bali',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1165,
            Address1:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'BADUNG',
            Area: {
              Id: 'BADUNG',
              Name: 'Badung',
            },
            City: {
              Id: 'KUTA',
              Name: 'Kuta',
            },
            Region: {
              Id: 'BALI',
              Name: 'Bali',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
            Coordinate: null,
          },
          IsPopular: true,
        },
        ArrivalPlaceTime: '2019-11-26T14:00:00',
        Duration: '3600',
        Class: 'Economy',
        ConnectionCount: 1,
        Connection: [
          {
            Class: 'Economy',
            FlightCode: '1234',
            Duration: '3600',
            IsAllowedActivity: false,
            DeparturePlace: {
              Id: 2,
              Name: 'Soekarno-Hatta International Airport',
              Code: 'CGK',
              Address: 'Tangerang City, Banten 19120',
              CityId: 'JAKARTA',
              PlaceType: 'Airport',
              City: {
                UTC: 7,
                ImageUrl: null,
                Id: 'JAKARTA',
                Name: 'Jakarta',
              },
              Region: {
                ImageUrl: null,
                Id: 'JAKARTA',
                Name: 'Jakarta',
              },
              Country: {
                Code: null,
                ImageUrl: null,
                Id: 'ID',
                Name: 'Indonesia',
              },
              AddressObject: {
                Id: 1154,
                Address1: 'Tangerang City, Banten 19120',
                Address2: '',
                Address3: '',
                PostalCode: '',
                Landmark: '',
                AreaId: 'JAKARTA',
                Area: {
                  Id: 'JAKARTA',
                  Name: 'Jakarta',
                },
                City: {
                  Id: 'JAKARTA',
                  Name: 'Jakarta',
                },
                Region: {
                  Id: 'JAKARTA',
                  Name: 'Jakarta',
                },
                Country: {
                  Id: 'ID',
                  Name: 'Indonesia',
                },
                AddressString:
                  'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
                Coordinate: null,
              },
              IsPopular: false,
            },
            DepartureTime: '2019-11-26T09:00:00',
            ArrivalPlace: {
              Id: 27,
              Name: 'Juanda International Airport',
              Code: 'SUB',
              Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
              CityId: 'SURABAYA',
              PlaceType: 'Airport',
              City: {
                UTC: 7,
                ImageUrl: null,
                Id: 'SURABAYA',
                Name: 'Surabaya',
              },
              Region: {
                ImageUrl: null,
                Id: 'JAWATIMUR',
                Name: 'Jawa Timur',
              },
              Country: {
                Code: null,
                ImageUrl: null,
                Id: 'ID',
                Name: 'Indonesia',
              },
              AddressObject: {
                Id: 799,
                Address1: 'Jalan Ir. Haji Juanda Surabaya 61253',
                Address2: '',
                Address3: '',
                PostalCode: '',
                Landmark: '',
                AreaId: 'SURABAYA',
                Area: {
                  Id: 'SURABAYA',
                  Name: 'Surabaya',
                },
                City: {
                  Id: 'SURABAYA',
                  Name: 'Surabaya',
                },
                Region: {
                  Id: 'JAWATIMUR',
                  Name: 'Jawa Timur',
                },
                Country: {
                  Id: 'ID',
                  Name: 'Indonesia',
                },
                AddressString:
                  'Jalan Ir. Haji Juanda Surabaya 61253, Surabaya, Surabaya, Jawa Timur, Indonesia',
                Coordinate: null,
              },
              IsPopular: false,
            },
            ArrivalTime: '2019-11-26T10:00:00',
          },
          {
            Class: 'Economy',
            FlightCode: '1234',
            Duration: '3600',
            IsAllowedActivity: false,
            DeparturePlace: {
              Id: 27,
              Name: 'Juanda International Airport',
              Code: 'SUB',
              Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
              CityId: 'SURABAYA',
              PlaceType: 'Airport',
              City: {
                UTC: 7,
                ImageUrl: null,
                Id: 'SURABAYA',
                Name: 'Surabaya',
              },
              Region: {
                ImageUrl: null,
                Id: 'JAWATIMUR',
                Name: 'Jawa Timur',
              },
              Country: {
                Code: null,
                ImageUrl: null,
                Id: 'ID',
                Name: 'Indonesia',
              },
              AddressObject: {
                Id: 799,
                Address1: 'Jalan Ir. Haji Juanda Surabaya 61253',
                Address2: '',
                Address3: '',
                PostalCode: '',
                Landmark: '',
                AreaId: 'SURABAYA',
                Area: {
                  Id: 'SURABAYA',
                  Name: 'Surabaya',
                },
                City: {
                  Id: 'SURABAYA',
                  Name: 'Surabaya',
                },
                Region: {
                  Id: 'JAWATIMUR',
                  Name: 'Jawa Timur',
                },
                Country: {
                  Id: 'ID',
                  Name: 'Indonesia',
                },
                AddressString:
                  'Jalan Ir. Haji Juanda Surabaya 61253, Surabaya, Surabaya, Jawa Timur, Indonesia',
                Coordinate: null,
              },
              IsPopular: false,
            },
            DepartureTime: '2019-11-26T13:00:00',
            ArrivalPlace: {
              Id: 1,
              Name: 'Ngurah Rai International Airport',
              Code: 'DPS',
              Address:
                'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
              CityId: 'KUTA',
              PlaceType: 'Airport',
              City: {
                UTC: 8,
                ImageUrl: null,
                Id: 'KUTA',
                Name: 'Kuta',
              },
              Region: {
                ImageUrl: null,
                Id: 'BALI',
                Name: 'Bali',
              },
              Country: {
                Code: null,
                ImageUrl: null,
                Id: 'ID',
                Name: 'Indonesia',
              },
              AddressObject: {
                Id: 1165,
                Address1:
                  'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621',
                Address2: '',
                Address3: '',
                PostalCode: '',
                Landmark: '',
                AreaId: 'BADUNG',
                Area: {
                  Id: 'BADUNG',
                  Name: 'Badung',
                },
                City: {
                  Id: 'KUTA',
                  Name: 'Kuta',
                },
                Region: {
                  Id: 'BALI',
                  Name: 'Bali',
                },
                Country: {
                  Id: 'ID',
                  Name: 'Indonesia',
                },
                AddressString:
                  'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
                Coordinate: null,
              },
              IsPopular: true,
            },
            ArrivalTime: '2019-11-26T14:00:00',
          },
        ],
      },
    ],
  },
];

export const moreDestination = [
  {
    Id: 1,
    RouteName: 'CGK-DPS-SUB',
    AirlineLogo: null,
    AirlineName: 'Garuda Indonesia',
    IsRoundTrip: true,
    ScheduleItems: [
      {
        Id: 1,
        FlightCode: '1234',
        DeparturePlace: {
          Id: 2,
          Name: 'Soekarno-Hatta International Airport',
          Code: 'CGK',
          Address: 'Tangerang City, Banten 19120',
          CityId: 'JAKARTA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1154,
            Address1: 'Tangerang City, Banten 19120',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'JAKARTA',
            Area: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            City: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Region: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        DeparturePlaceTime: '2019-11-26T09:00:00',
        ArrivalPlace: {
          Id: 1,
          Name: 'Ngurah Rai International Airport',
          Code: 'DPS',
          Address:
            'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
          CityId: 'KUTA',
          PlaceType: 'Airport',
          City: {
            UTC: 8,
            ImageUrl: null,
            Id: 'KUTA',
            Name: 'Kuta',
          },
          Region: {
            ImageUrl: null,
            Id: 'BALI',
            Name: 'Bali',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1165,
            Address1:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'BADUNG',
            Area: {
              Id: 'BADUNG',
              Name: 'Badung',
            },
            City: {
              Id: 'KUTA',
              Name: 'Kuta',
            },
            Region: {
              Id: 'BALI',
              Name: 'Bali',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
            Coordinate: null,
          },
          IsPopular: true,
        },
        ArrivalPlaceTime: '2019-11-26T11:00:00',
        Duration: '3600',
        Class: 'Economy',
        ConnectionCount: 0,
        Connection: [],
      },
      {
        Id: 2,
        FlightCode: '1234',
        DeparturePlace: {
          Id: 1,
          Name: 'Ngurah Rai International Airport',
          Code: 'DPS',
          Address:
            'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
          CityId: 'KUTA',
          PlaceType: 'Airport',
          City: {
            UTC: 8,
            ImageUrl: null,
            Id: 'KUTA',
            Name: 'Kuta',
          },
          Region: {
            ImageUrl: null,
            Id: 'BALI',
            Name: 'Bali',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1165,
            Address1:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'BADUNG',
            Area: {
              Id: 'BADUNG',
              Name: 'Badung',
            },
            City: {
              Id: 'KUTA',
              Name: 'Kuta',
            },
            Region: {
              Id: 'BALI',
              Name: 'Bali',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
            Coordinate: null,
          },
          IsPopular: true,
        },
        DeparturePlaceTime: '2019-11-30T09:00:00',
        ArrivalPlace: {
          Id: 27,
          Name: 'Juanda International Airport',
          Code: 'SUB',
          Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
          CityId: 'SURABAYA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'SURABAYA',
            Name: 'Surabaya',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAWATIMUR',
            Name: 'Jawa Timur',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 799,
            Address1: 'Jalan Ir. Haji Juanda Surabaya 61253',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'SURABAYA',
            Area: {
              Id: 'SURABAYA',
              Name: 'Surabaya',
            },
            City: {
              Id: 'SURABAYA',
              Name: 'Surabaya',
            },
            Region: {
              Id: 'JAWATIMUR',
              Name: 'Jawa Timur',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Ir. Haji Juanda Surabaya 61253, Surabaya, Surabaya, Jawa Timur, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        ArrivalPlaceTime: '2019-12-30T10:00:00',
        Duration: '3600',
        Class: 'Economy',
        ConnectionCount: 0,
        Connection: [],
      },
      {
        Id: 3,
        FlightCode: '1234',
        DeparturePlace: {
          Id: 27,
          Name: 'Juanda International Airport',
          Code: 'SUB',
          Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
          CityId: 'SURABAYA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'SURABAYA',
            Name: 'Surabaya',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAWATIMUR',
            Name: 'Jawa Timur',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 799,
            Address1: 'Jalan Ir. Haji Juanda Surabaya 61253',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'SURABAYA',
            Area: {
              Id: 'SURABAYA',
              Name: 'Surabaya',
            },
            City: {
              Id: 'SURABAYA',
              Name: 'Surabaya',
            },
            Region: {
              Id: 'JAWATIMUR',
              Name: 'Jawa Timur',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Ir. Haji Juanda Surabaya 61253, Surabaya, Surabaya, Jawa Timur, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        DeparturePlaceTime: '2019-12-02T09:00:00',
        ArrivalPlace: {
          Id: 2,
          Name: 'Soekarno-Hatta International Airport',
          Code: 'CGK',
          Address: 'Tangerang City, Banten 19120',
          CityId: 'JAKARTA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1154,
            Address1: 'Tangerang City, Banten 19120',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'JAKARTA',
            Area: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            City: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Region: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        ArrivalPlaceTime: '2019-12-02T10:00:00',
        Duration: '3600',
        Class: 'Economy',
        ConnectionCount: 0,
        Connection: [],
      },
    ],
  },
];
