let data = {
  Departures: [
    {
      Address: 'Tangerang City, Banten 19120',
      City: {
        Id: 'JAKARTA',
        ImageUrl: null,
        Name: 'Jakarta',
        UTC: 7,
      },
      Date: '2019-12-30T09:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Soekarno-Hatta International Airport',
      PlaceId: 2,
      PlaceType: 'Airport',
      Region: 'JAKARTA',
      TransferType: 'Movement_departure',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
    {
      Address:
        'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
      City: {
        Id: 'KUTA',
        ImageUrl: null,
        Name: 'Kuta',
        UTC: 7,
      },
      Date: '2019-12-30T14:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Ngurah Rai International Airport',
      PlaceId: 1,
      PlaceType: 'Airport',
      Region: 'BALI',
      TransferType: 'Movement_arrival',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
  ],
  MainPrograms: [
    {
      AccommodationSummary: {
        CheckIn: '2019-12-30T14:35:00',
        CheckOut: '2019-12-31T10:00:00',
        Address:
          'Jl Legian No 328 - Legian Kelod Kuta - Kuta, Bali 80361 BALI - INDONESIA',
        AccommodationProfileId: 23,
        Allocations: {
          ChildExtraBedPax: 0,
          ChildSharingRoomPax: 0,
          ChildSingleRoomPax: 0,
          ExtraBedPax: 0,
          NoBedPax: 0,
          SharingBedPax: 0,
          SharingRoomPax: 2,
          SingleRoomPax: 0,
        },
        DateTime: '2019-12-30T00:00:00',
        Name: 'Mercure Legian',
        RoomName: 'Deluxe Balcony',
        RoomService: 'With_breakfast',
        RoomType: 'Double/Twin Sharing',
        SeqNumber: null,
        ServiceItemId: 6277,
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/Accommodations/b98efc92-6504-454a-bfe3-e302dbe17ec0dubai-2057585_1920.jpg.jpg',
      },
      City: {
        Id: 'KUTA',
        Name: 'Kuta',
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/City/0ed74a00-3093-4c16-987e-e64b856f1454travel-3239795_1920.jpg.jpg',
        UTC: 8,
        Region: {
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/upload/beautiful-beach.jpg',
          Id: 'BALI',
          Name: 'Bali',
        },
        Country: {
          Code: '+62',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
          Id: 'ID',
          Name: 'Indonesia',
        },
      },
      Date: '2019-12-30T00:00:00',
      Day: 1,
      LeavingDate: '2019-12-31T00:00:00',
      Note: null,
      Region: 'BALI',
      TotalDays: 6,
      NextDay: false,
    },
    {
      Address: 'Tangerang City, Banten 19120',
      City: {
        Id: 'JAKARTA',
        ImageUrl: null,
        Name: 'Jakarta',
        UTC: 7,
      },
      Date: '2019-12-30T09:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Soekarno-Hatta International Airport',
      PlaceId: 2,
      PlaceType: 'Airport',
      Region: 'JAKARTA',
      TransferType: 'Movement_departure',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
    {
      Address:
        'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
      City: {
        Id: 'KUTA',
        ImageUrl: null,
        Name: 'Kuta',
        UTC: 7,
      },
      Date: '2019-12-30T14:00:00',
      Day: 1,
      NextDay: false,
      Note: null,
      Place: 'Ngurah Rai International Airport',
      PlaceId: 1,
      PlaceType: 'Airport',
      Region: 'BALI',
      TransferType: 'Movement_arrival',
      Ticket: {
        ServiceItemId: '1',
        PNR: 'PNR123',
        FlightNumber: '345',
        AirlineProfileName: 'Garuda Indonesia',
        Duration: 0,
        IsTransit: false,
        IsAllowedActivity: false,
      },
    },
  ],
  Returns: [
    {
      Address:
        'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
      City: {
        Id: 'KUTA',
        Name: 'Kuta',
        ImageUrl:
          'https://touressapiqa.azurewebsites.net//Content/imgSrc/City/0ed74a00-3093-4c16-987e-e64b856f1454travel-3239795_1920.jpg.jpg',
        Region: {
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/upload/beautiful-beach.jpg',
          Id: 'BALI',
          Name: 'Bali',
        },
        Country: {
          Code: '+62',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
          Id: 'ID',
          Name: 'Indonesia',
        },
      },
      UTC: 8,
      Date: '2019-12-31T12:00:00',
      Day: 2,
      Note: null,
      Place: 'Ngurah Rai International Airport',
      PlaceId: 1,
      PlaceType: 'Airport',
      Region: 'BALI',
      TransferType: 'Movement_departure',
      NextDay: false,
      RequestFrom: 'BALI',
    },
    {
      Address:
        'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
      City: {
        Id: 'JAKARTA',
        Name: 'Jakarta',
        ImageUrl: '',
        Region: {
          ImageUrl:
            'http://agenfiforlif.mc468.com/wp-content/uploads/2016/06/DKI-Jakarta.jpg',
          Id: 'JAKARTA',
          Name: 'Jakarta',
        },
        Country: {
          Code: '+62',
          ImageUrl:
            'http://cloud.basajans.com:8868/tripplannerdev/5104226627001_5244682653001_5214868250001-vs.jpg',
          Id: 'ID',
          Name: 'Indonesia',
        },
        UTC: 7,
        Date: '2019-12-31T14:00:00',
        Day: 2,
        Note: null,
        Place: 'Soekarno-Hatta International Airport',
        PlaceId: 2,
        PlaceType: 'Airport',
        Region: null,
        TransferType: 'Movement_arrival',
        NextDay: false,
        RequestFrom: '',
      },
    },
  ],
};
export { data };
