import EStyleSheet from 'react-native-extended-stylesheet';
import { Dimensions, Platform } from 'react-native';

const fullWidth = Dimensions.get('window').width;

export default EStyleSheet.create({
  $goldcolor: '$gold',
  $redcolor: '$red',
  $blacklight2color: '$blacklight2',
  $whitelightcolor: '$background',
  colorgreylight2: { color: '$greylight2' },
  colorlightGrey: { color: '$lightGrey' },
  $lightGreycolor: '$lightGrey',
  $greylight2color: '$greylight2',
  colorTextRadioButton: { color: '$iosShadow' },
  $iosShadowcolor: '$iosShadow',
  $goldlightcolor: '$goldlight',
  $sandlightcolor: '$sandlight',
  $softbluecolor: '$softblue',
  marginLeft10: { marginLeft: 10 },
  tintColorWhite: { tintColor: 'white' },
  tintColorBlack: { tintColor: '#252525' },
  overflowHidden: { overflow: 'hidden' },
  height30: { height: 30 },
  bottom: {
    paddingBottom: 10,
  },
  checkBoxStyle: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    padding: 0,
  },
  stylesHeaderButton: {
    position: 'absolute',
    top: 20,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    zIndex: 2,
  },
  textWhite: {
    color: 'transparent',
  },
  stylesPageSchedule: {
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    width: Dimensions.get('window').width,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    flexDirection: 'row',
  },
  stylesHeaderDate: {
    fontSize: 32,
    fontWeight: '600',
    color: '#e6ca6b',
  },
  textDate: {
    fontSize: 14,
    fontWeight: '600',
    color: '#e6ca6b',
  },
  stylesCol: {
    flexDirection: 'column',
  },
  stylesScrollViewSchedule: {
    marginBottom: 0,
    width: Dimensions.get('window').width,
  },
  paddingTop20: {
    paddingTop: 20,
  },
  paddingTop60: {
    paddingTop: 60,
  },
  paddingTop40: {
    paddingTop: 40,
  },
  padding: {
    paddingHorizontal: 10,
    paddingVertical: 10,
  },

  headerOverlay: {
    width: '100%',
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  headerDetail: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    overflow: 'hidden',
    zIndex: 3,
  },
  image: {
    width: '100%',
    height: 125,
  },

  warningCard: {
    width: '90%',
    backgroundColor: '$cardoverlay',
    marginBottom: 15,
    borderStyle: 'solid',
    borderWidth: 0.3,
    borderColor: '$gold',
    borderRadius: 5,
    padding: 5,
    marginTop: 20,
  },
  // row: {
  //   flexDirection: 'row',
  //   justifyContent: 'space-between',
  //   width: '100%',
  //   paddingHorizontal: 5,
  //   paddingVertical: 5,
  // },
  // row100: {
  //   paddingHorizontal: 5,
  //   paddingVertical: 2.5,
  //   alignItems: 'center',
  //   flexDirection: 'row',
  //   flex: 1,
  //   width: '100%',
  // },
  // rowNoPadding: {
  //   flexDirection: 'row',
  //   width: '100%',
  // },
  rowspacebetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '80%',
  },
  rowPadding: {
    flexDirection: 'row',
    marginLeft: 10,
    marginRight: 10,
    width: '90%',
    justifyContent: 'center',
  },
  row100padding: {
    flexDirection: 'row',
    width: '99%',
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  rowBackground: {
    flexDirection: 'row',
    width: '100%',
    paddingVertical: 2.5,
    backgroundColor: '$cardoverlay',
    marginBottom: 5,
  },
  colNoPadding45: {
    flexDirection: 'column',
    width: '45%',
  },
  colNoPadding10: {
    width: '10%',
  },
  colNoPadding90: {
    width: '90%',
  },
  // card: {
  //   width: '100%',
  //   height: '15%',
  //   backgroundColor: '$cardoverlay',
  //   position: 'relative',
  //   left: 5,
  //   right: 5,
  //   bottom: 5,
  //   marginBottom: 15,
  // },
  bold14: {
    fontSize: 14,
    fontWeight: Platform.OS === 'ios' ? '600' : '300',
  },
  bold16: {
    fontSize: 16,
    fontWeight: Platform.OS === 'ios' ? '600' : '300',
    paddingBottom: 10,
  },
  bold18: {
    fontSize: 18,
    fontWeight: Platform.OS === 'ios' ? '600' : '300',
  },
  bold20: {
    fontSize: 20,
    fontWeight: Platform.OS === 'ios' ? '600' : '300',
  },
  size14: { fontSize: 14 },
  textblack: {
    fontSize: 12,
    color: 'black',
    textAlign: 'left',
  },
  marginBottom10: {
    marginBottom: 10,
  },
  elevation3: {
    elevation: 3,
  },

  marginBottom20: {
    marginBottom: 20,
  },
  paddingHorizontal20: {
    paddingHorizontal: 20,
  },
  paddingTop15: {
    paddingTop: 15,
  },
  styleContainer: {
    alignItems: 'center',
    backgroundColor: '$background',
    flex: 1,
    marginBottom: 60,
  },
  marginBottom60: {
    marginBottom: 60,
  },
  marginBottom80: {
    marginBottom: 80,
  },
  bottom0: {
    bottom: 0,
  },
  stylesTextCustomOption: {
    fontWeight: 'bold',
    fontSize: 14,
    alignSelf: 'flex-start',
    paddingLeft: 20,
    marginBottom: 20,
  },
  stylesContainerRadioGrup: {
    justifyContent: 'flex-start',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '$border',
    overflow: 'hidden',
    height: 45,
  },
  stylesButtonRadioGrup: {
    borderRadius: 0,
    borderWidth: 0,
    width: '50%',
  },
  marginTop20MarginBottom60: {
    paddingTop: 20,
    marginBottom: 60,
  },
  textblack15: {
    fontSize: 15,
  },

  widthHeight22: {
    width: 22,
    height: 22,
  },
  image30: {
    height: 30,
    width: 30,
  },
  textbold15: {
    fontSize: 15,
    fontWeight: Platform.OS === 'ios' ? '600' : '300',
    color: 'black',
  },
  textbold18: {
    fontSize: 16,
    fontWeight: Platform.OS === 'ios' ? '600' : '300',
    color: 'black',
    textAlign: 'center',
  },
  text14Wrap: {
    fontSize: 14,
    color: 'black',
    flexWrap: 'wrap',
  },
  text16Wrap: {
    fontSize: 16,
    color: 'black',
    flexWrap: 'wrap',
  },
  marginRight3: { marginRight: 3 },

  containerDropDown45: {
    width: '45%',
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    marginBottom: 2,
    backgroundColor: 'transparent',
  },
  containerDropDown50: {
    width: '50%',
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    backgroundColor: 'transparent',
  },
  footerFilter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 60,
    shadowColor: '#d3d3d3',
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowRadius: 10,
    shadowOpacity: 1,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderTopWidth: 0,
    elevation: 13,
  },

  footerTourGuide: {
    position: 'absolute',
    flex: 0.1,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    height: Platform.OS === 'ios' ? 60 : 100,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: Platform.OS === 'ios' ? 5 : 25,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: 'black',
  },

  footer: {
    position: 'absolute',
    flex: 0.1,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#f4f4f4',
    shadowOffset: {
      width: 5,
      height: 5,
    },
    zIndex: 0,
    shadowRadius: 10,
    shadowOpacity: 0.5,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: 'hidden',
  },
  Scroll: {
    flex: 1,
    width: '100%',
  },

  modalContainerLoding: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    backgroundColor: '$lightgrey1',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
  },
  innerContainer: {
    height: '50%',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 8,
    shadowColor: '$greylight',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '$background',
    shadowOpacity: 0.3,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },

  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '$lightgrey1',
  },
  cardhidden: {
    height: 75,
    width: '100%',
  },
  iosBackButton: {
    marginLeft: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButton: {
    position: 'absolute',
    left: 20,
    top: 20,
  },
  textBackButtonIos: {
    color: 'white',
    paddingLeft: 10,
    fontSize: 18,
  },
  textPicker: {
    color: '$blacklight',
    fontSize: 14,
  },
  containerDropDown: {
    borderColor: '$border',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    overflow: 'hidden',
    width: '100%',
  },
  dropdownIos: {
    width: '100%',
    backgroundColor: 'transparent',
    borderRadius: 5,
    height: 43,
    alignItems: 'center',
    padding: 0,
  },
  containerDropDownAndroid: {
    height: 43,
    width: fullWidth,
  },
  cardRadius: {
    marginBottom: 20,
    width: '90%',
    paddingVertical: 20,
    backgroundColor: 'white',
    alignSelf: 'center',
    shadowColor: '#f4f4f4',
    shadowOffset: {
      width: 5,
      height: 5,
    },
    zIndex: 0,
    shadowRadius: 10,
    shadowOpacity: 0.5,
    borderRadius: 5,
    overflow: 'hidden',
    elevation: 3,
  },
  containerScroll: {
    width: '100%',
    flex: 1,
    marginBottom: 60,
  },
  rowNoPadding: {
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
    width: '80%',
  },
  rowNoPaddingLeft: {
    flexDirection: 'row',
    flex: 1,
    width: '90%',
  },
  colNoPaddingLeft: {
    flexDirection: 'column',
    flex: 1,
    width: '90%',
  },
  topNav: {
    alignSelf: 'flex-start',
    paddingLeft: 20,
    paddingTop: 20,
  },
  topNavText: {
    alignSelf: 'flex-start',
    justifyContent: 'center',
    paddingBottom: 0,
    paddingTop: 30,
    paddingLeft: 50,
  },
  headerText: {
    color: '$blacklight',
    fontWeight: '300',
    fontSize: 16,
  },
  textShowing: {
    fontSize: 14,
    color: '#ccc',
    textAlign: 'center',
  },
  showingContainer: {
    width: '100%',
    alignItems: 'center',
    paddingBottom: 15,
  },
  imageDetailPckg: {
    backgroundColor: '$blacklight',
    borderRadius: 20,
    paddingVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  indicatorSlider: {
    color: 'white',
    width: 60,
    textAlign: 'center',
  },

  right: { alignItems: 'flex-end' },
  marginTop20: { marginTop: 20 },
  flexWrap: { flexWrap: 'wrap' },
  text28Bold: {
    fontWeight: '300',
    fontSize: 28,
    color: '$blacklight',
  },
  text14Red: {
    color: 'red',
    fontSize: 14,
  },
  text28Red: {
    color: 'red',
    fontSize: 28,
    marginRight: 5,
    fontWeight: '300',
  },
  rightBottom: { alignItems: 'flex-end', justifyContent: 'flex-end' },
  containerPrice: {
    justifyContent: 'space-between',
    padding: 0,
    alignItems: 'flex-start',
    height: 50,
  },
  paddingHorizontal10: {
    paddingHorizontal: 10,
  },
  headerOperatorList: {
    position: 'absolute',
    flex: 1,
    left: 0,
    right: 0,
    top: 0,
    justifyContent: 'center',
    backgroundColor: '#fff',
    shadowColor: '#ccc',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 7,
  },
  headerTop: {
    zIndex: 99,
    backgroundColor: 'white',
  },
  searchBarList: {
    backgroundColor: 'white',
    width: '100%',
    borderTopWidth: 0,
    borderBottomWidth: 0,
  },
  searcBarInputStyle: { backgroundColor: '#f4f4f4', borderRadius: 20 },

  //NEW
  carouselImageContainer: {
    width: fullWidth,
  },
  containerScrollDetail: {
    backgroundColor: 'white',
    flex: 1,
  },
  containerStyle: {
    backgroundColor: 'white',
    flex: 1,
    alignItems: 'center',
  },
  carouselImage: {
    width: '100%',
    height: 300,
  },
  colPadding20: {
    paddingHorizontal: 20,
  },
  textTourType: {
    alignSelf: 'flex-start',
    marginBottom: 10,
    color: '$blacklight3',
  },
  card: {
    marginBottom: 20,
    width: '90%',
    paddingVertical: 20,
    backgroundColor: 'white',
    alignSelf: 'center',
    shadowColor: '#f4f4f4',
    shadowOffset: {
      width: 5,
      height: 5,
    },
    zIndex: 0,
    shadowRadius: 10,
    shadowOpacity: 0.5,
    borderRadius: 5,
    overflow: 'hidden',
  },
  rowNoPadding100: {
    flexDirection: 'row',
    flex: 1,
    width: '100%',
  },
  scrollContainer: {
    flex: 1,
    width: '100%',
    top: 0,
    left: 0,
    right: 0,
    paddingVertical: 50,
  },
  container: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  imagestyleDetail: {
    alignSelf: 'center',
    height: 100,
    width: 100,
    borderRadius: 50,
    marginTop: 5,
    marginBottom: 5,
    borderWidth: 2,
    borderColor: 'yellow',
  },
  item: {
    width: fullWidth,
    height: fullWidth,
  },
  imageCard: {
    width: fullWidth,
    // height: 300,
  },
  row: {
    paddingHorizontal: 5,
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
    width: '90%',
  },
  footerDetail: {
    position: 'absolute',
    flex: 0.1,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    height: 70,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '$blacklight',
    shadowColor: '#f4f4f4',
    shadowOffset: {
      width: 5,
      height: 5,
    },
    zIndex: 0,
    shadowRadius: 10,
    shadowOpacity: 0.5,
  },
  col30: {
    width: '30%',
  },
  col70: {
    width: '70%',
  },
  col50: {
    width: '50%',
  },
  topNavDetail: {
    position: 'absolute',
    zIndex: 1,
    alignSelf: 'flex-start',
    paddingLeft: 20,
    paddingTop: 20,
  },
  topNavTextDetail: {
    position: 'absolute',
    zIndex: 1,
    alignSelf: 'center',
    justifyContent: 'center',
    paddingBottom: 0,
    paddingTop: 30,
  },
  row100: {
    paddingHorizontal: 5,
    alignItems: 'center',
    flexDirection: 'row',
    // flex: 1,
    width: '100%',
  },
  textWhite: {
    color: 'white',
  },
  cardList: {
    backgroundColor: 'white',
    width: '90%',
    paddingLeft: 10,
    paddingRight: 20,
    borderRadius: 10,
    position: 'absolute',
    marginTop: '60%',
    paddingTop: 20,
  },
  imageContainer: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  headerTransparent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    overflow: 'hidden',
    zIndex: 99,
    padding: 10,
  },
  gradientFooter: {
    width: '100%',
    height: 150,
    position: 'absolute',
  },
  textHeader: {
    color: '$blacklight',
    fontWeight: '500',
    marginLeft: 10,
  },

  contentContainerDetail: {
    paddingHorizontal: 20,
    position: 'absolute',
    top: 280,
  },
  containerIndicator: {
    backgroundColor: '$blacklight',
    borderRadius: 20,
    paddingVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  left: { alignItems: 'flex-start' },
  paddingVertical20: {
    paddingVertical: 20,
  },
  paddingVertical10: {
    paddingVertical: 10,
  },
  textJustify25: {
    textAlign: 'justify',
    lineHeight: 25,
    color: '$blacklight',
  },
  marginBottomCenter20: {
    justifyContent: 'center',
    marginBottom: 20,
  },
  marginTop10: {
    marginTop: 10,
  },

  readMoreText: { fontWeight: '300', color: '$gold' },
  paddingBottom20: { paddingBottom: 20 },
  borderRadius80: { borderRadius: 80 },
  paddingLeft30: { paddingLeft: 30 },
  textInfo: { color: '$blacklight', lineHeight: 25 },
  borderBottom2: {
    borderBottomColor: '#f4f4f4',
    borderBottomWidth: 2,
    paddingBottom: 20,
    marginBottom: 20,
    paddingLeft: 15,
  },
  paddingLeft10: { paddingLeft: 10 },
  text18: {
    fontSize: 18,
    lineHeight: 25,
  },
  readMoreTextGold: { fontWeight: '300', color: '$gold' },
  priceContainer: {
    width: '60%',
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  paddingLeft20: { paddingLeft: 20 },
  totalContainer: {
    width: '70%',
    paddingRight: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bold20White: {
    color: 'white',
    fontWeight: '300',
    fontSize: 20,
  },
  text12White: {
    color: 'white',
    fontSize: 12,
    alignSelf: 'flex-end',
  },
  text12Wrap: {
    fontSize: 12,
    color: '$blacklight',
    flexWrap: 'wrap',
  },
  bookButtonContainer: {
    width: '40%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '$gold',
  },
  accomodationTypeText: {
    fontSize: 14,
    paddingHorizontal: 5,
    borderWidth: 1,
    borderColor: '$gold',
    borderRadius: 5,
  },
  seall: {
    fontSize: 12,
    color: '#0f63f7',
  },
  tabNavigation: {
    width: '100%',
    flexDirection: 'row',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    zIndex: 5,
  },
  header: {
    width: '100%',
    justifyContent: 'center',
    backgroundColor: '#fff',
    shadowColor: '#ccc',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 3,
  },

  headerFix: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 70,
    backgroundColor: '#fff',
    shadowColor: '#ccc',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 7,
    paddingHorizontal: 20,
    width: '100%',
  },

  circleButton: {
    width: 40,
    height: 40,
    padding: 10,
    borderRadius: 30,
    backgroundColor: '$gold',
  },
  containerIcon50: {
    width: 50,
    height: 50,
  },
  justifySpace: {
    justifyContent: 'space-between',
  },
  cardWarning: {
    width: '100%',
    backgroundColor: '$cardoverlay',
    marginBottom: 15,
    borderStyle: 'solid',
    borderWidth: 0.3,
    borderColor: '$gold',
    paddingHorizontal: 5,
    paddingVertical: 10,
    flexDirection: 'column',
    alignItems: 'flex-start',
    borderRadius: 5,
  },
  btnDelete: {
    width: 30,
    height: 30,
    borderRadius: 30,
    backgroundColor: 'red',
    position: 'absolute',
    right: 5,
    top: -5,
    zIndex: 10,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
  },
  cardDisable: {
    width: '100%',
    backgroundColor: '$disabel',
    marginBottom: 5,
    borderStyle: 'solid',
    borderWidth: 0.3,
    borderColor: '$border',
    paddingHorizontal: 5,
    paddingVertical: 10,
    flexDirection: 'column',
    alignItems: 'flex-start',
    borderRadius: 5,
  },
  cardWarningGT: {
    width: '100%',
    // height: 58.7,
    backgroundColor: '$cardoverlay',
    borderStyle: 'solid',
    borderWidth: 0.3,
    borderColor: '$gold',
    paddingHorizontal: 4,
    paddingVertical: 4,
    borderRadius: 5,
  },
});
