export const GET_RESTAURANT_PROFILE_BY_SERVICE_ITEM =
  'GET_RESTAURANT_PROFILE_BY_SERVICE_ITEM';
export const GET_RESTAURANT_PROFILE_BY_SERVICE_ITEM_PENDING =
  'GET_RESTAURANT_PROFILE_BY_SERVICE_ITEM_PENDING';
export const GET_RESTAURANT_PROFILE_BY_SERVICE_ITEM_REJECTED =
  'GET_RESTAURANT_PROFILE_BY_SERVICE_ITEM_REJECTED';
export const GET_RESTAURANT_PROFILE_BY_SERVICE_ITEM_FULFILLED =
  'GET_RESTAURANT_PROFILE_BY_SERVICE_ITEM_FULFILLED';
export const GET_RESTAURANT_BY_FILTER = 'GET_RESTAURANT_BY_FILTER';
export const GET_RESTAURANT_BY_FILTER_PENDING =
  'GET_RESTAURANT_BY_FILTER_PENDING';
export const GET_RESTAURANT_BY_FILTER_FULFILLED =
  'GET_RESTAURANT_BY_FILTER_FULFILLED';
export const GET_RESTAURANT_BY_FILTER_REJECTED =
  'GET_RESTAURANT_BY_FILTER_REJECTED';
export const GET_RESTAURANT_RATING = 'GET_RESTAURANT_RATING';
export const GET_RESTAURANT_RATING_PENDING = 'GET_RESTAURANT_RATING_PENDING';
export const GET_RESTAURANT_RATING_FULFILLED =
  'GET_RESTAURANT_RATING_FULFILLED';
export const GET_RESTAURANT_RATING_REJECTED = 'GET_RESTAURANT_RATING_REJECTED';
export const GET_RESTAURANT_SPECIALIZATIONS = 'GET_RESTAURANT_SPECIALIZATIONS';
export const GET_RESTAURANT_SPECIALIZATIONS_PENDING =
  'GET_RESTAURANT_SPECIALIZATIONS_PENDING';
export const GET_RESTAURANT_SPECIALIZATIONS_FULFILLED =
  'GET_RESTAURANT_SPECIALIZATIONS_FULFILLED';
export const GET_RESTAURANT_SPECIALIZATIONS_REJECTED =
  'GET_RESTAURANT_SPECIALIZATIONS_REJECTED';
export const GET_RESTAURANT_MENU_CLASSES = 'GET_RESTAURANT_MENU_CLASSES';
export const GET_RESTAURANT_MENU_CLASSES_PENDING =
  'GET_RESTAURANT_MENU_CLASSES_PENDING';
export const GET_RESTAURANT_MENU_CLASSES_FULFILLED =
  'GET_RESTAURANT_MENU_CLASSES_FULFILLED';
export const GET_RESTAURANT_MENU_CLASSES_REJECTED =
  'GET_RESTAURANT_MENU_CLASSES_REJECTED';
export const GET_RESTAURANT_MENU_BY_ID = 'GET_RESTAURANT_MENU_BY_ID';
export const GET_RESTAURANT_MENU_BY_ID_PENDING =
  'GET_RESTAURANT_MENU_BY_ID_PENDING';
export const GET_RESTAURANT_MENU_BY_ID_FULFILLED =
  'GET_RESTAURANT_MENU_BY_ID_FULFILLED';
export const GET_RESTAURANT_MENU_BY_ID_REJECTED =
  'GET_RESTAURANT_MENU_BY_ID_REJECTED';
export const RESET_STATUS_RESTAURANT = 'RESET_STATUS_RESTAURANT';
export const RESET_STATUS_TRANSPORTATION = 'RESET_STATUS_TRANSPORTATION';
export const RESET_STATUS_TRANSPORTATION_UNITS_FILTER =
  'RESET_STATUS_TRANSPORTATION_UNITS_FILTER';
export const RESET_STATUS_RESTAURANTS_BY_FILTER =
  'RESET_STATUS_RESTAURANTS_BY_FILTER';
