export const GET_TOUR_OPERATOR_LIST = "GET_TOUR_OPERATOR_LIST";
export const GET_TOUR_OPERATOR_LIST_PENDING = "GET_TOUR_OPERATOR_LIST_PENDING";
export const GET_TOUR_OPERATOR_LIST_FULFILLED =
  "GET_TOUR_OPERATOR_LIST_FULFILLED";
export const GET_TOUR_OPERATOR_LIST_REJECTED =
  "GET_TOUR_OPERATOR_LIST_REJECTED";

export const RESET_TOUR_OPERATOR_LIST = "RESET_TOUR_OPERATOR_LIST";
