export const GET_TOUR_TYPE = 'GET_TOUR_TYPE';
export const GET_TOUR_TYPE_PENDING = 'GET_TOUR_TYPE_PENDING';
export const GET_TOUR_TYPE_FULFILLED = 'GET_TOUR_TYPE_FULFILLED';
export const GET_TOUR_TYPE_REJECTED = 'GET_TOUR_TYPE_REJECTED';

export const GET_TOUR_CATEGORY = 'GET_TOUR_CATEGORY';
export const GET_TOUR_CATEGORY_PENDING = 'GET_TOUR_CATEGORY_PENDING';
export const GET_TOUR_CATEGORY_FULFILLED = 'GET_TOUR_CATEGORY_FULFILLED';
export const GET_TOUR_CATEGORY_REJECTED = 'GET_TOUR_CATEGORY_REJECTED';

export const GET_ALL_MOVEMENT_TYPES = 'GET_ALL_MOVEMENT_TYPES';
export const GET_ALL_MOVEMENT_TYPES_PENDING = 'GET_ALL_MOVEMENT_TYPES_PENDING';
export const GET_ALL_MOVEMENT_TYPES_FULFILLED =
  'GET_ALL_MOVEMENT_TYPES_FULFILLED';
export const GET_ALL_MOVEMENT_TYPES_REJECTED =
  'GET_ALL_MOVEMENT_TYPES_REJECTED';

export const GET_CITY_IN_COUNTRY = 'GET_CITY_IN_COUNTRY';
export const GET_CITY_IN_COUNTRY_PENDING = 'GET_CITY_IN_COUNTRY_PENDING';
export const GET_CITY_IN_COUNTRY_FULFILLED = 'GET_CITY_IN_COUNTRY_FULFILLED';
export const GET_CITY_IN_COUNTRY_REJECTED = 'GET_CITY_IN_COUNTRY_REJECTED';

export const GET_CUSTOMER_LIST = 'GET_CUSTOMER_LIST';
export const GET_CUSTOMER_LIST_PENDING = 'GET_CUSTOMER_LIST_PENDING';
export const GET_CUSTOMER_LIST_FULFILLED = 'GET_CUSTOMER_LIST_FULFILLED';
export const GET_CUSTOMER_LIST_REJECTED = 'GET_CUSTOMER_LIST_REJECTED';

export const GET_USER_ID_COMPANY = 'GET_USER_ID_COMPANY';
export const GET_USER_ID_COMPANY_PENDING = 'GET_USER_ID_COMPANY_PENDING';
export const GET_USER_ID_COMPANY_FULFILLED = 'GET_USER_ID_COMPANY_FULFILLED';
export const GET_USER_ID_COMPANY_REJECTED = 'GET_USER_ID_COMPANY_REJECTED';
export const RESET_CUSTOMER_LIST = 'RESET_CUSTOMER_LIST';
export const SET_GUEST = 'SET_GUEST';

export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_PENDING = 'GET_COUNTRIES_PENDING';
export const GET_COUNTRIES_FULFILLED = 'GET_COUNTRIES_FULFILLED';
export const GET_COUNTRIES_REJECTED = 'GET_COUNTRIES_REJECTED';

export const GET_IDENTITY_TYPE = 'GET_IDENTITY_TYPE';
export const GET_IDENTITY_TYPE_FULFILLED = 'GET_IDENTITY_TYPE_FULFILLED';
export const GET_IDENTITY_TYPE_PENDING = 'GET_IDENTITY_TYPE_PENDING';
export const GET_IDENTITY_TYPE_REJECTED = 'GET_IDENTITY_TYPE_REJECTED';
export const GET_GUEST_TITLE_TYPE = 'GET_GUEST_TITLE_TYPE';
export const GET_GUEST_TITLE_TYPE_FULFILLED = 'GET_GUEST_TITLE_TYPE_FULFILLED';
export const GET_GUEST_TITLE_TYPE_PENDING = 'GET_GUEST_TITLE_TYPE_PENDING';
export const GET_GUEST_TITLE_TYPE_REJECTED = 'GET_GUEST_TITLE_TYPE_REJECTED';
