export const GET_TOUR_TYPE = "GET_TOUR_TYPE";
export const GET_TOUR_TYPE_PENDING = "GET_TOUR_TYPE_PENDING";
export const GET_TOUR_TYPE_FULFILLED = "GET_TOUR_TYPE_FULFILLED";
export const GET_TOUR_TYPE_REJECTED = "GET_TOUR_TYPE_REJECTED";

export const GET_TOUR_CATEGORY = "GET_TOUR_CATEGORY";
export const GET_TOUR_CATEGORY_PENDING = "GET_TOUR_CATEGORY_PENDING";
export const GET_TOUR_CATEGORY_FULFILLED = "GET_TOUR_CATEGORY_FULFILLED";
export const GET_TOUR_CATEGORY_REJECTED = "GET_TOUR_CATEGORY_REJECTED";

export const GET_ALL_MOVEMENT_TYPES = "GET_ALL_MOVEMENT_TYPES";
export const GET_ALL_MOVEMENT_TYPES_PENDING = "GET_ALL_MOVEMENT_TYPES_PENDING";
export const GET_ALL_MOVEMENT_TYPES_FULFILLED =
  "GET_ALL_MOVEMENT_TYPES_FULFILLED";
export const GET_ALL_MOVEMENT_TYPES_REJECTED =
  "GET_ALL_MOVEMENT_TYPES_REJECTED";
