export const GET_PACKAGE_LIST = "GET_PACKAGE_LIST";
export const GET_PACKAGE_LIST_PENDING = "GET_PACKAGE_LIST_PENDING";
export const GET_PACKAGE_LIST_FULFILLED = "GET_PACKAGE_LIST_FULFILLED";
export const GET_PACKAGE_LIST_REJECTED = "GET_PACKAGE_LIST_REJECTED";
export const SET_PACKAGE_ID = "SET_PACKAGE_ID";
export const SET_PACKAGE_STATUS_FROM_HOME_TO_LIST =
  "SET_PACKAGE_STATUS_FROM_HOME_TO_LIST";
export const RESET_PACKAGE_LIST_STATUS = "RESET_PACKAGE_LIST_STATUS";

export const GET_PACKAGE_BY_ID = "GET_PACKAGE_BY_ID";
export const GET_PACKAGE_BY_ID_PENDING = "GET_PACKAGE_BY_ID_PENDING";
export const GET_PACKAGE_BY_ID_FULFILLED = "GET_PACKAGE_BY_ID_FULFILLED";
export const GET_PACKAGE_BY_ID_REJECTED = "GET_PACKAGE_BY_ID_REJECTED";

export const GET_OPERATOR_PROFILE_BY_ID = "GET_OPERATOR_PROFILE_BY_ID";
export const GET_OPERATOR_PROFILE_BY_ID_PENDING =
  "GET_OPERATOR_PROFILE_BY_ID_PENDING";
export const GET_OPERATOR_PROFILE_BY_ID_FULFILLED =
  "GET_OPERATOR_PROFILE_BY_ID_FULFILLED";
export const GET_OPERATOR_PROFILE_BY_ID_REJECTED =
  "GET_OPERATOR_PROFILE_BY_ID_REJECTED";

// export const SET_PACKAGE_DATA = "SET_PACKAGE_DATA";
// export const SET_GUEST_DATA = "SET_GUEST_DATA";
// export const SET_CUSTOM_ITINERARY = "SET_CUSTOM_ITINERARY";
// export const SET_SUMMARY_PROGRAM = "SET_SUMMARY_PROGRAM";
// export const RESET_CUSTOM_ITINERARY = "RESET_CUSTOM_ITINERARY";
// export const SET_GUEST_QUOTATION = "SET_GUEST_QUOTATION";
// export const SET_DEPARTURES_ITINERARY = "SET_DEPARTURES_ITINERARY";
// export const SET_RETURNS_ITINERARY = "SET_RETURNS_ITINERARY";
export const SET_GUEST_TOUR_GUIDE = "SET_GUEST_TOUR_GUIDE";
export const SET_CUSTOM_ITINERARY = "SET_CUSTOM_ITINERARY";
export const RESET_CUSTOM_ITINERARY = "RESET_CUSTOM_ITINERARY";
export const SET_DEPARTURES_ITINERARY = "SET_DEPARTURES_ITINERARY";
export const RESET_DEPARTURES_ITINERARY = "RESET_DEPARTURES_ITINERARY";
export const SET_RETURNS_ITINERARY = "SET_RETURNS_ITINERARY";
export const RESET_RETURNS_ITINERARY = "RESET_RETURNS_ITINERARY";
export const SET_ARRIVAL_ITINERARY = "SET_ARRIVAL_ITINERARY";
export const RESET_ARRIVAL_ITINERARY = "RESET_ARRIVAL_ITINERARY";
export const SET_DEPATURE_ITINERARY = "SET_DEPATURE_ITINERARY";
export const RESET_DEPATURE_ITINERARY = "RESET_DEPATURE_ITINERARY";
export const SET_SUMMARY_PROGRAM = "SET_SUMMARY_PROGRAM";
export const RESET_SUMMARY_PROGRAM = "RESET_SUMMARY_PROGRAM";
export const SET_DAILY_PROGRAM = "SET_DAILY_PROGRAM";
export const RESET_DAILY_PROGRAM = "RESET_DAILY_PROGRAM";
export const SET_GUEST_ITINERARY = "SET_GUEST_ITINERARY";
export const RESET_GUEST_ITINERARY = "RESET_GUEST_ITINERARY";
export const SET_TOUROPERATOR = "SET_TOUROPERATOR";
export const RESET_TOUROPERATOR = "RESET_TOUROPERATOR";
export const SET_GUEST_QUOTATION = "SET_GUEST_QUOTATION";
export const RESET_GUEST_QUOTATION = "RESET_GUEST_QUOTATION";
