export const GET_PACKAGE_LIST = 'GET_PACKAGE_LIST';
export const GET_PACKAGE_LIST_PENDING = 'GET_PACKAGE_LIST_PENDING';
export const GET_PACKAGE_LIST_FULFILLED = 'GET_PACKAGE_LIST_FULFILLED';
export const GET_PACKAGE_LIST_REJECTED = 'GET_PACKAGE_LIST_REJECTED';
export const SET_PACKAGE_ID = 'SET_PACKAGE_ID';
export const SET_PACKAGE_STATUS_FROM_HOME_TO_LIST =
  'SET_PACKAGE_STATUS_FROM_HOME_TO_LIST';
export const RESET_PACKAGE_LIST_STATUS = 'RESET_PACKAGE_LIST_STATUS';

export const GET_PACKAGE_BY_ID = 'GET_PACKAGE_BY_ID';
export const GET_PACKAGE_BY_ID_PENDING = 'GET_PACKAGE_BY_ID_PENDING';
export const GET_PACKAGE_BY_ID_FULFILLED = 'GET_PACKAGE_BY_ID_FULFILLED';
export const GET_PACKAGE_BY_ID_REJECTED = 'GET_PACKAGE_BY_ID_REJECTED';

export const GET_OPERATOR_PROFILE_BY_ID = 'GET_OPERATOR_PROFILE_BY_ID';
export const GET_OPERATOR_PROFILE_BY_ID_PENDING =
  'GET_OPERATOR_PROFILE_BY_ID_PENDING';
export const GET_OPERATOR_PROFILE_BY_ID_FULFILLED =
  'GET_OPERATOR_PROFILE_BY_ID_FULFILLED';
export const GET_OPERATOR_PROFILE_BY_ID_REJECTED =
  'GET_OPERATOR_PROFILE_BY_ID_REJECTED';

export const SET_PACKAGE_DATA = 'SET_PACKAGE_DATA';
export const SET_GUEST_DATA = 'SET_GUEST_DATA';
// export const SET_CUSTOM_ITINERARY = "SET_CUSTOM_ITINERARY";
// export const SET_SUMMARY_PROGRAM = "SET_SUMMARY_PROGRAM";
// export const RESET_CUSTOM_ITINERARY = "RESET_CUSTOM_ITINERARY";
// export const SET_GUEST_QUOTATION = "SET_GUEST_QUOTATION";
// export const SET_DEPARTURES_ITINERARY = "SET_DEPARTURES_ITINERARY";
// export const SET_RETURNS_ITINERARY = "SET_RETURNS_ITINERARY";
export const SET_GUEST_TOUR_GUIDE = 'SET_GUEST_TOUR_GUIDE';
export const SET_CUSTOM_ITINERARY = 'SET_CUSTOM_ITINERARY';
export const RESET_CUSTOM_ITINERARY = 'RESET_CUSTOM_ITINERARY';
export const SET_DEPARTURES_ITINERARY = 'SET_DEPARTURES_ITINERARY';
export const RESET_DEPARTURES_ITINERARY = 'RESET_DEPARTURES_ITINERARY';
export const SET_RETURNS_ITINERARY = 'SET_RETURNS_ITINERARY';
export const RESET_RETURNS_ITINERARY = 'RESET_RETURNS_ITINERARY';
export const SET_ARRIVAL_ITINERARY = 'SET_ARRIVAL_ITINERARY';
export const RESET_ARRIVAL_ITINERARY = 'RESET_ARRIVAL_ITINERARY';
export const SET_DEPATURE_ITINERARY = 'SET_DEPATURE_ITINERARY';
export const RESET_DEPATURE_ITINERARY = 'RESET_DEPATURE_ITINERARY';
export const SET_SUMMARY_PROGRAM = 'SET_SUMMARY_PROGRAM';
export const RESET_SUMMARY_PROGRAM = 'RESET_SUMMARY_PROGRAM';
export const SET_DAILY_PROGRAM = 'SET_DAILY_PROGRAM';
export const RESET_DAILY_PROGRAM = 'RESET_DAILY_PROGRAM';
export const SET_GUEST_ITINERARY = 'SET_GUEST_ITINERARY';
export const RESET_GUEST_ITINERARY = 'RESET_GUEST_ITINERARY';
export const SET_TOUROPERATOR = 'SET_TOUROPERATOR';
export const RESET_TOUROPERATOR = 'RESET_TOUROPERATOR';
export const SET_GUEST_QUOTATION = 'SET_GUEST_QUOTATION';
export const RESET_GUEST_QUOTATION = 'RESET_GUEST_QUOTATION';

//   post_create_custom,
//   post_create_custom_onbehalf,
//   reset_post_create_custom,
//   post_edit_quotation,

export const RESET_POST_CREATE_CUSTOM = 'RESET_POST_CREATE_CUSTOM';
export const RESET_POST_QUOTATION = 'RESET_POST_QUOTATION';

export const SET_SPECIAL_ADJUSMENT = 'SET_SPECIAL_ADJUSMENT';
// export const SET_SPECIAL_ADJUSMENT_PENDING = 'SET_SPECIAL_ADJUSMENT_PENDING';
// export const SET_SPECIAL_ADJUSMENT_FULFILLED =
//   'SET_SPECIAL_ADJUSMENT_FULFILLED';
// export const SET_SPECIAL_ADJUSMENT_REJECTED = 'SET_SPECIAL_ADJUSMENT_REJECTED';

export const POST_EDIT_QUOTATION = 'POST_EDIT_QUOTATION';
export const POST_EDIT_QUOTATION_PENDING = 'POST_EDIT_QUOTATION_PENDING';
export const POST_EDIT_QUOTATION_FULFILLED = 'POST_EDIT_QUOTATION_FULFILLED';
export const POST_EDIT_QUOTATION_REJECTED = 'POST_EDIT_QUOTATION_REJECTED';

export const POST_CREATE_CUSTOM = 'POST_CREATE_CUSTOM';
export const POST_CREATE_CUSTOM_PENDING = 'POST_CREATE_CUSTOM_PENDING';
export const POST_CREATE_CUSTOM_FULFILLED = 'POST_CREATE_CUSTOM_FULFILLED';
export const POST_CREATE_CUSTOM_REJECTED = 'POST_CREATE_CUSTOM_REJECTED';

export const POST_CREATE_CUSTOM_ON_BE_HALF = 'POST_CREATE_CUSTOM_ON_BE_HALF';
export const POST_CREATE_CUSTOM_ON_BE_HALF_PENDING =
  'POST_CREATE_CUSTOM_ON_BE_HALF_PENDING';
export const POST_CREATE_CUSTOM_ON_BE_HALF_FULFILLED =
  'POST_CREATE_CUSTOM_ON_BE_HALF_FULFILLED';
export const POST_CREATE_CUSTOM_ON_BE_HALF_REJECTED =
  'POST_CREATE_CUSTOM_ON_BE_HALF_REJECTED';

export const POST_JOIN_TOUR = 'POST_JOIN_TOUR';
export const POST_JOIN_TOUR_PENDING = 'POST_JOIN_TOUR_PENDING';
export const POST_JOIN_TOUR_FULFILLED = 'POST_JOIN_TOUR_FULFILLED';
export const POST_JOIN_TOUR_REJECTED = 'POST_JOIN_TOUR_REJECTED';

export const GET_TOUR_SUMMARY_BY_ID = 'GET_TOUR_SUMMARY_BY_ID';
export const GET_TOUR_SUMMARY_BY_ID_PENDING = 'GET_TOUR_SUMMARY_BY_ID_PENDING';
export const GET_TOUR_SUMMARY_BY_ID_FULFILLED =
  'GET_TOUR_SUMMARY_BY_ID_FULFILLED';
export const GET_TOUR_SUMMARY_BY_ID_REJECTED =
  'GET_TOUR_SUMMARY_BY_ID_REJECTED';

export const GET_TRANSACTION_HISTORY_BY_STATUS =
  'GET_TRANSACTION_HISTORY_BY_STATUS';
export const GET_TRANSACTION_HISTORY_BY_STATUS_PENDING =
  'GET_TRANSACTION_HISTORY_BY_STATUS_PENDING';
export const GET_TRANSACTION_HISTORY_BY_STATUS_FULFILLED =
  'GET_TRANSACTION_HISTORY_BY_STATUS_FULFILLED';
export const GET_TRANSACTION_HISTORY_BY_STATUS_REJECTED =
  'GET_TRANSACTION_HISTORY_BY_STATUS_REJECTED';

export const POST_DEMO_JOIN_TOUR = 'POST_DEMO_JOIN_TOUR';
export const POST_DEMO_JOIN_TOUR_PENDING = 'POST_DEMO_JOIN_TOUR_PENDING';
export const POST_DEMO_JOIN_TOUR_FULFILLED = 'POST_DEMO_JOIN_TOUR_FULFILLED';
export const POST_DEMO_JOIN_TOUR_REJECTED = 'POST_DEMO_JOIN_TOUR_REJECTED';

export const POST_DEMO_CREATE_TOUR = 'POST_DEMO_CREATE_TOUR';
export const POST_DEMO_CREATE_TOUR_PENDING = 'POST_DEMO_CREATE_TOUR_PENDING';
export const POST_DEMO_CREATE_TOUR_FULFILLED =
  'POST_DEMO_CREATE_TOUR_FULFILLED';
export const POST_DEMO_CREATE_TOUR_REJECTED = 'POST_DEMO_CREATE_TOUR_REJECTED';
export const RESET_STATUS_POST_DEMO = 'RESET_STATUS_POST_DEMO';
