export const GET_PACKAGE_LIST = "GET_PACKAGE_LIST";
export const GET_PACKAGE_LIST_PENDING = "GET_PACKAGE_LIST_PENDING";
export const GET_PACKAGE_LIST_FULFILLED = "GET_PACKAGE_LIST_FULFILLED";
export const GET_PACKAGE_LIST_REJECTED = "GET_PACKAGE_LIST_REJECTED";
export const SET_PACKAGE_ID = "SET_PACKAGE_ID";
export const SET_PACKAGE_STATUS_FROM_HOME_TO_LIST =
  "SET_PACKAGE_STATUS_FROM_HOME_TO_LIST";
export const RESET_PACKAGE_LIST_STATUS = "RESET_PACKAGE_LIST_STATUS";

export const GET_PACKAGE_BY_ID = "GET_PACKAGE_BY_ID";
export const GET_PACKAGE_BY_ID_PENDING = "GET_PACKAGE_BY_ID_PENDING";
export const GET_PACKAGE_BY_ID_FULFILLED = "GET_PACKAGE_BY_ID_FULFILLED";
export const GET_PACKAGE_BY_ID_REJECTED = "GET_PACKAGE_BY_ID_REJECTED";
