export const RESET_ACCOMMODATION_PROFILE = 'RESET_ACCOMMODATION_PROFILE';
export const SET_CITY_ACCOMMODATION = 'SET_CITY_ACCOMMODATION';

export const GET_ACCOMMODATION = 'GET_ACCOMMODATION';
export const GET_ACCOMMODATION_PENDING = 'GET_ACCOMMODATION_PENDING';
export const GET_ACCOMMODATION_FULFILLED = 'GET_ACCOMMODATION_FULFILLED';
export const GET_ACCOMMODATION_REJECTED = 'GET_ACCOMMODATION_REJECTED';

export const GET_ACCOMMODATION_RATINGS = 'GET_ACCOMMODATION_RATINGS';
export const GET_ACCOMMODATION_RATINGS_PENDING =
  'GET_ACCOMMODATION_RATINGS_PENDING';
export const GET_ACCOMMODATION_RATINGS_FULFILLED =
  'GET_ACCOMMODATION_RATINGS_FULFILLED';
export const GET_ACCOMMODATION_RATINGS_REJECTED =
  'GET_ACCOMMODATION_RATINGS_REJECTED';

export const GET_ACCOMMODATION_AREAS = 'GET_ACCOMMODATION_AREAS';
export const GET_ACCOMMODATION_AREAS_PENDING =
  'GET_ACCOMMODATION_AREAS_PENDING';
export const GET_ACCOMMODATION_AREAS_FULFILLED =
  'GET_ACCOMMODATION_AREAS_FULFILLED';
export const GET_ACCOMMODATION_AREAS_REJECTED =
  'GET_ACCOMMODATION_AREAS_REJECTED';

export const GET_ACCOMMODATION_TYPES = 'GET_ACCOMMODATION_TYPES';
export const GET_ACCOMMODATION_TYPES_PENDING =
  'GET_ACCOMMODATION_TYPES_PENDING';
export const GET_ACCOMMODATION_TYPES_FULFILLED =
  'GET_ACCOMMODATION_TYPES_FULFILLED';
export const GET_ACCOMMODATION_TYPES_REJECTED =
  'GET_ACCOMMODATION_TYPES_REJECTED';

export const GET_ACCOMMODATION_LOCATIONS = 'GET_ACCOMMODATION_LOCATIONS';
export const GET_ACCOMMODATION_LOCATIONS_PENDING =
  'GET_ACCOMMODATION_LOCATIONS_PENDING';
export const GET_ACCOMMODATION_LOCATIONS_FULFILLED =
  'GET_ACCOMMODATION_LOCATIONS_FULFILLED';
export const GET_ACCOMMODATION_LOCATIONS_REJECTED =
  'GET_ACCOMMODATION_LOCATIONS_REJECTED';

export const GET_ACCOMMODATION_FACILITIES = 'GET_ACCOMMODATION_FACILITIES';
export const GET_ACCOMMODATION_FACILITIES_PENDING =
  'GET_ACCOMMODATION_FACILITIES_PENDING';
export const GET_ACCOMMODATION_FACILITIES_FULFILLED =
  'GET_ACCOMMODATION_FACILITIES_FULFILLED';
export const GET_ACCOMMODATION_FACILITIES_REJECTED =
  'GET_ACCOMMODATION_FACILITIES_REJECTED';

export const GET_ACCOMMODATION_BY_ID = 'GET_ACCOMMODATION_BY_ID';
export const GET_ACCOMMODATION_BY_ID_PENDING =
  'GET_ACCOMMODATION_BY_ID_PENDING';
export const GET_ACCOMMODATION_BY_ID_FULFILLED =
  'GET_ACCOMMODATION_BY_ID_FULFILLED';
export const GET_ACCOMMODATION_BY_ID_REJECTED =
  'GET_ACCOMMODATION_BY_ID_REJECTED';

export const GET_ACCOMMODATION_ROOMS = 'GET_ACCOMMODATION_ROOMS';
export const GET_ACCOMMODATION_ROOMS_PENDING =
  'GET_ACCOMMODATION_ROOMS_PENDING';
export const GET_ACCOMMODATION_ROOMS_FULFILLED =
  'GET_ACCOMMODATION_ROOMS_FULFILLED';
export const GET_ACCOMMODATION_ROOMS_REJECTED =
  'GET_ACCOMMODATION_ROOMS_REJECTED';

export const GET_ACCOMMODATION_BY_SERVICE_ITEM_ID =
  'GET_ACCOMMODATION_BY_SERVICE_ITEM_ID';
export const GET_ACCOMMODATION_BY_SERVICE_ITEM_ID_PENDING =
  'GET_ACCOMMODATION_BY_SERVICE_ITEM_ID_PENDING';
export const GET_ACCOMMODATION_BY_SERVICE_ITEM_ID_FULFILLED =
  'GET_ACCOMMODATION_BY_SERVICE_ITEM_ID_FULFILLED';
export const GET_ACCOMMODATION_BY_SERVICE_ITEM_ID_REJECTED =
  'GET_ACCOMMODATION_BY_SERVICE_ITEM_ID_REJECTED';
export const RESET_GET_ACOOMMODATION = 'RESET_GET_ACOOMMODATION';
