let DATA = {
  Result: [
    [
      {
        Id: 1,
        RouteName: 'CGK-DPS',
        AirlineLogo: null,
        AirlineName: 'Garuda Indonesia',
        FlightCode: '1234',
        DeparturePlace: {
          Id: 2,
          Name: 'Soekarno-Hatta International Airport',
          Code: 'CGK',
          Address: 'Tangerang City, Banten 19120',
          CityId: 'JAKARTA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1154,
            Address1: 'Tangerang City, Banten 19120',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'JAKARTA',
            Area: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            City: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Region: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        DeparturePlaceTime: '2019-11-26T09:00:00',
        ArrivalPlace: {
          Id: 1,
          Name: 'Ngurah Rai International Airport',
          Code: 'DPS',
          Address:
            'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
          CityId: 'KUTA',
          PlaceType: 'Airport',
          City: {
            UTC: 8,
            ImageUrl: null,
            Id: 'KUTA',
            Name: 'Kuta',
          },
          Region: {
            ImageUrl: null,
            Id: 'BALI',
            Name: 'Bali',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1165,
            Address1:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'BADUNG',
            Area: {
              Id: 'BADUNG',
              Name: 'Badung',
            },
            City: {
              Id: 'KUTA',
              Name: 'Kuta',
            },
            Region: {
              Id: 'BALI',
              Name: 'Bali',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
            Coordinate: null,
          },
          IsPopular: true,
        },
        ArrivalPlaceTime: '2019-11-26T14:00:00',
        Duration: '3600',
        Class: 'Economy',
        ConnectionCount: 1,
        Connection: [
          {
            Class: 'Economy',
            FlightCode: '1234',
            Duration: '3600',
            DeparturePlace: {
              Id: 2,
              Name: 'Soekarno-Hatta International Airport',
              Code: 'CGK',
              Address: 'Tangerang City, Banten 19120',
              CityId: 'JAKARTA',
              PlaceType: 'Airport',
              City: {
                UTC: 7,
                ImageUrl: null,
                Id: 'JAKARTA',
                Name: 'Jakarta',
              },
              Region: {
                ImageUrl: null,
                Id: 'JAKARTA',
                Name: 'Jakarta',
              },
              Country: {
                Code: null,
                ImageUrl: null,
                Id: 'ID',
                Name: 'Indonesia',
              },
              AddressObject: {
                Id: 1154,
                Address1: 'Tangerang City, Banten 19120',
                Address2: '',
                Address3: '',
                PostalCode: '',
                Landmark: '',
                AreaId: 'JAKARTA',
                Area: {
                  Id: 'JAKARTA',
                  Name: 'Jakarta',
                },
                City: {
                  Id: 'JAKARTA',
                  Name: 'Jakarta',
                },
                Region: {
                  Id: 'JAKARTA',
                  Name: 'Jakarta',
                },
                Country: {
                  Id: 'ID',
                  Name: 'Indonesia',
                },
                AddressString:
                  'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
                Coordinate: null,
              },
              IsPopular: false,
            },
            DepartureTime: '2019-11-26T09:00:00',
            ArrivalPlace: {
              Id: 27,
              Name: 'Juanda International Airport',
              Code: 'SUB',
              Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
              CityId: 'SURABAYA',
              PlaceType: 'Airport',
              City: {
                UTC: 7,
                ImageUrl: null,
                Id: 'SURABAYA',
                Name: 'Surabaya',
              },
              Region: {
                ImageUrl: null,
                Id: 'JAWATIMUR',
                Name: 'Jawa Timur',
              },
              Country: {
                Code: null,
                ImageUrl: null,
                Id: 'ID',
                Name: 'Indonesia',
              },
              AddressObject: {
                Id: 799,
                Address1: 'Jalan Ir. Haji Juanda Surabaya 61253',
                Address2: '',
                Address3: '',
                PostalCode: '',
                Landmark: '',
                AreaId: 'SURABAYA',
                Area: {
                  Id: 'SURABAYA',
                  Name: 'Surabaya',
                },
                City: {
                  Id: 'SURABAYA',
                  Name: 'Surabaya',
                },
                Region: {
                  Id: 'JAWATIMUR',
                  Name: 'Jawa Timur',
                },
                Country: {
                  Id: 'ID',
                  Name: 'Indonesia',
                },
                AddressString:
                  'Jalan Ir. Haji Juanda Surabaya 61253, Surabaya, Surabaya, Jawa Timur, Indonesia',
                Coordinate: null,
              },
              IsPopular: false,
            },
            ArrivalTime: '2019-11-26T10:00:00',
          },
          {
            Class: 'Economy',
            FlightCode: '1234',
            Duration: '3600',
            DeparturePlace: {
              Id: 27,
              Name: 'Juanda International Airport',
              Code: 'SUB',
              Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
              CityId: 'SURABAYA',
              PlaceType: 'Airport',
              City: {
                UTC: 7,
                ImageUrl: null,
                Id: 'SURABAYA',
                Name: 'Surabaya',
              },
              Region: {
                ImageUrl: null,
                Id: 'JAWATIMUR',
                Name: 'Jawa Timur',
              },
              Country: {
                Code: null,
                ImageUrl: null,
                Id: 'ID',
                Name: 'Indonesia',
              },
              AddressObject: {
                Id: 799,
                Address1: 'Jalan Ir. Haji Juanda Surabaya 61253',
                Address2: '',
                Address3: '',
                PostalCode: '',
                Landmark: '',
                AreaId: 'SURABAYA',
                Area: {
                  Id: 'SURABAYA',
                  Name: 'Surabaya',
                },
                City: {
                  Id: 'SURABAYA',
                  Name: 'Surabaya',
                },
                Region: {
                  Id: 'JAWATIMUR',
                  Name: 'Jawa Timur',
                },
                Country: {
                  Id: 'ID',
                  Name: 'Indonesia',
                },
                AddressString:
                  'Jalan Ir. Haji Juanda Surabaya 61253, Surabaya, Surabaya, Jawa Timur, Indonesia',
                Coordinate: null,
              },
              IsPopular: false,
            },
            DepartureTime: '2019-11-26T13:00:00',
            ArrivalPlace: {
              Id: 1,
              Name: 'Ngurah Rai International Airport',
              Code: 'DPS',
              Address:
                'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
              CityId: 'KUTA',
              PlaceType: 'Airport',
              City: {
                UTC: 8,
                ImageUrl: null,
                Id: 'KUTA',
                Name: 'Kuta',
              },
              Region: {
                ImageUrl: null,
                Id: 'BALI',
                Name: 'Bali',
              },
              Country: {
                Code: null,
                ImageUrl: null,
                Id: 'ID',
                Name: 'Indonesia',
              },
              AddressObject: {
                Id: 1165,
                Address1:
                  'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621',
                Address2: '',
                Address3: '',
                PostalCode: '',
                Landmark: '',
                AreaId: 'BADUNG',
                Area: {
                  Id: 'BADUNG',
                  Name: 'Badung',
                },
                City: {
                  Id: 'KUTA',
                  Name: 'Kuta',
                },
                Region: {
                  Id: 'BALI',
                  Name: 'Bali',
                },
                Country: {
                  Id: 'ID',
                  Name: 'Indonesia',
                },
                AddressString:
                  'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
                Coordinate: null,
              },
              IsPopular: true,
            },
            ArrivalTime: '2019-11-26T14:00:00',
          },
        ],
      },
    ],
    [
      {
        Id: 1,
        RouteName: 'CGK-DPS',
        AirlineLogo: null,
        AirlineName: 'Garuda Indonesia',
        FlightCode: '1234',
        DeparturePlace: {
          Id: 2,
          Name: 'Soekarno-Hatta International Airport',
          Code: 'CGK',
          Address: 'Tangerang City, Banten 19120',
          CityId: 'JAKARTA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1154,
            Address1: 'Tangerang City, Banten 19120',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'JAKARTA',
            Area: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            City: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Region: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        DeparturePlaceTime: '2019-11-26T09:00:00',
        ArrivalPlace: {
          Id: 1,
          Name: 'Ngurah Rai International Airport',
          Code: 'DPS',
          Address:
            'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
          CityId: 'KUTA',
          PlaceType: 'Airport',
          City: {
            UTC: 8,
            ImageUrl: null,
            Id: 'KUTA',
            Name: 'Kuta',
          },
          Region: {
            ImageUrl: null,
            Id: 'BALI',
            Name: 'Bali',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1165,
            Address1:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'BADUNG',
            Area: {
              Id: 'BADUNG',
              Name: 'Badung',
            },
            City: {
              Id: 'KUTA',
              Name: 'Kuta',
            },
            Region: {
              Id: 'BALI',
              Name: 'Bali',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
            Coordinate: null,
          },
          IsPopular: true,
        },
        ArrivalPlaceTime: '2019-11-26T11:00:00',
        Duration: '3600',
        Class: 'Economy',
        ConnectionCount: 0,
        Connection: [],
      },
    ],
  ],
  Similar: [
    [
      {
        Id: 1,
        RouteName: 'CGK-DPS-SUB',
        AirlineLogo: null,
        AirlineName: 'Garuda Indonesia',
        FlightCode: '1234',
        DeparturePlace: {
          Id: 2,
          Name: 'Soekarno-Hatta International Airport',
          Code: 'CGK',
          Address: 'Tangerang City, Banten 19120',
          CityId: 'JAKARTA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1154,
            Address1: 'Tangerang City, Banten 19120',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'JAKARTA',
            Area: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            City: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Region: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        DeparturePlaceTime: '2019-11-26T09:00:00',
        ArrivalPlace: {
          Id: 1,
          Name: 'Ngurah Rai International Airport',
          Code: 'DPS',
          Address:
            'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
          CityId: 'KUTA',
          PlaceType: 'Airport',
          City: {
            UTC: 8,
            ImageUrl: null,
            Id: 'KUTA',
            Name: 'Kuta',
          },
          Region: {
            ImageUrl: null,
            Id: 'BALI',
            Name: 'Bali',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1165,
            Address1:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'BADUNG',
            Area: {
              Id: 'BADUNG',
              Name: 'Badung',
            },
            City: {
              Id: 'KUTA',
              Name: 'Kuta',
            },
            Region: {
              Id: 'BALI',
              Name: 'Bali',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
            Coordinate: null,
          },
          IsPopular: true,
        },
        ArrivalPlaceTime: '2019-11-26T11:00:00',
        Duration: '3600',
        Class: 'Economy',
        ConnectionCount: 0,
        Connection: [],
      },
      {
        Id: 1,
        RouteName: 'CGK-DPS-SUB-CGK',
        AirlineLogo: null,
        AirlineName: 'Garuda Indonesia',
        FlightCode: '1234',
        DeparturePlace: {
          Id: 1,
          Name: 'Ngurah Rai International Airport',
          Code: 'DPS',
          Address:
            'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 80362',
          CityId: 'KUTA',
          PlaceType: 'Airport',
          City: {
            UTC: 8,
            ImageUrl: null,
            Id: 'KUTA',
            Name: 'Kuta',
          },
          Region: {
            ImageUrl: null,
            Id: 'BALI',
            Name: 'Bali',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1165,
            Address1:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'BADUNG',
            Area: {
              Id: 'BADUNG',
              Name: 'Badung',
            },
            City: {
              Id: 'KUTA',
              Name: 'Kuta',
            },
            Region: {
              Id: 'BALI',
              Name: 'Bali',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Raya Gusti Ngurah Rai, Tuban, Kuta, Kabupaten Badung, Bali 803621, Badung, Kuta, Bali, Indonesia',
            Coordinate: null,
          },
          IsPopular: true,
        },
        DeparturePlaceTime: '2019-11-30T09:00:00',
        ArrivalPlace: {
          Id: 27,
          Name: 'Juanda International Airport',
          Code: 'SUB',
          Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
          CityId: 'SURABAYA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'SURABAYA',
            Name: 'Surabaya',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAWATIMUR',
            Name: 'Jawa Timur',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 799,
            Address1: 'Jalan Ir. Haji Juanda Surabaya 61253',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'SURABAYA',
            Area: {
              Id: 'SURABAYA',
              Name: 'Surabaya',
            },
            City: {
              Id: 'SURABAYA',
              Name: 'Surabaya',
            },
            Region: {
              Id: 'JAWATIMUR',
              Name: 'Jawa Timur',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Ir. Haji Juanda Surabaya 61253, Surabaya, Surabaya, Jawa Timur, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        ArrivalPlaceTime: '2019-12-30T10:00:00',
        Duration: '3600',
        Class: 'Economy',
        ConnectionCount: 0,
        Connection: [],
      },
      {
        Id: 1,
        RouteName: 'CGK-DPS-SUB-CGK',
        AirlineLogo: null,
        AirlineName: 'Garuda Indonesia',
        FlightCode: '1234',
        DeparturePlace: {
          Id: 27,
          Name: 'Juanda International Airport',
          Code: 'SUB',
          Address: 'Jalan Ir. Haji Juanda Surabaya 61253',
          CityId: 'SURABAYA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'SURABAYA',
            Name: 'Surabaya',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAWATIMUR',
            Name: 'Jawa Timur',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 799,
            Address1: 'Jalan Ir. Haji Juanda Surabaya 61253',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'SURABAYA',
            Area: {
              Id: 'SURABAYA',
              Name: 'Surabaya',
            },
            City: {
              Id: 'SURABAYA',
              Name: 'Surabaya',
            },
            Region: {
              Id: 'JAWATIMUR',
              Name: 'Jawa Timur',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Jalan Ir. Haji Juanda Surabaya 61253, Surabaya, Surabaya, Jawa Timur, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        DeparturePlaceTime: '2019-12-02T09:00:00',
        ArrivalPlace: {
          Id: 2,
          Name: 'Soekarno-Hatta International Airport',
          Code: 'CGK',
          Address: 'Tangerang City, Banten 19120',
          CityId: 'JAKARTA',
          PlaceType: 'Airport',
          City: {
            UTC: 7,
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Region: {
            ImageUrl: null,
            Id: 'JAKARTA',
            Name: 'Jakarta',
          },
          Country: {
            Code: null,
            ImageUrl: null,
            Id: 'ID',
            Name: 'Indonesia',
          },
          AddressObject: {
            Id: 1154,
            Address1: 'Tangerang City, Banten 19120',
            Address2: '',
            Address3: '',
            PostalCode: '',
            Landmark: '',
            AreaId: 'JAKARTA',
            Area: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            City: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Region: {
              Id: 'JAKARTA',
              Name: 'Jakarta',
            },
            Country: {
              Id: 'ID',
              Name: 'Indonesia',
            },
            AddressString:
              'Tangerang City, Banten 19120, Jakarta, Jakarta, Jakarta, Indonesia',
            Coordinate: null,
          },
          IsPopular: false,
        },
        ArrivalPlaceTime: '2019-12-02T10:00:00',
        Duration: '3600',
        Class: 'Economy',
        ConnectionCount: 0,
        Connection: [],
      },
    ],
  ],
};
export { DATA };
