//Login
const LOGIN_FAILED = "LOGIN_FAILED";
const LOGIN_START = "LOGIN_START";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGOUT = "LOGOUT";
const RESET_STATUS_LOGIN = "RESET_STATUS_LOGIN";
const GET_TOKEN = "GET_TOKEN";
//Register
const REGISTER = "REGISTER";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILED = "REGISTER_FAILED";
const RESET_REGISTER = "RESET_REGISTER";
//Forgot Password
const FORGOT_PASSWORD = "FORGOT_PASSWORD";
const RESET_STATUS_FORGOT = "RESET_STATUS_FORGOT";
const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";
//General
const GET_TOTAL_BRANCH_START = "GET_TOTAL_BRANCH_START";
const GET_TOTAL_BRANCH_SUCCESS = "GET_TOTAL_BRANCH_SUCCESS";
const GET_TOTAL_BRANCH_FAILED = "GET_TOTAL_BRANCH_FAILED";
const GET_TOTAL_EMPLOYEE_START = "GET_TOTAL_EMPLOYEE_START";
const GET_TOTAL_EMPLOYEE_SUCCESS = "GET_TOTAL_EMPLOYEE_SUCCESS";
const GET_TOTAL_EMPLOYEE_FAILED = "GET_TOTAL_EMPLOYEE_FAILED";
const GET_TOTAL_REVENUE_START = "GET_TOTAL_REVENUE_START";
const GET_TOTAL_REVENUE_SUCCESS = "GET_TOTAL_REVENUE_SUCCESS";
const GET_TOTAL_REVENUE_FAILED = "GET_TOTAL_REVENUE_FAILED";
const GET_TOTAL_CURRENCIES_START = "GET_TOTAL_CURRENCIES_START";
const GET_TOTAL_CURRENCIES_SUCCESS = "GET_TOTAL_CURRENCIES_SUCCESS";
const GET_TOTAL_CURRENCIES_FAILED = "GET_TOTAL_CURRENCIES_FAILED";
const GET_PAX_TYPE_TOUR_START = "GET_PAX_TYPE_TOUR_START";
const GET_PAX_TYPE_TOUR_SUCCESS = "GET_PAX_TYPE_TOUR_SUCCESS";
const GET_PAX_TYPE_TOUR_FAILED = "GET_PAX_TYPE_TOUR_FAILED";
const GET_TYPE_TOUR_START = "GET_TYPE_TOUR_START";
const GET_TYPE_TOUR_SUCCESS = "GET_TYPE_TOUR_SUCCESS";
const GET_TYPE_TOUR_FAILED = "GET_TYPE_TOUR_FAILED";
const GET_CITY_INCOUNTRY_START = "GET_CITY_INCOUNTRY_START";
const GET_CITY_INCOUNTRY_SUCCESS = "GET_CITY_INCOUNTRY_SUCCESS";
const GET_CITY_INCOUNTRY_FAILED = "GET_CITY_INCOUNTRY_FAILED";
const GET_COUNTRY = "GET_COUNTRY";
const GET_COUNTRY_SUCCESS = "GET_COUNTRY_SUCCESS";
const GET_COUNTRY_FAILED = "GET_COUNTRY_FAILED";
const RESET_COUNTRY = "RESET_COUNTRY";
const GET_LANGUAGE = "GET_LANGUAGE";
const GET_LANGUAGE_SUCCESS = "GET_LANGUAGE_SUCCESS";
const GET_LANGUAGE_FAILED = "GET_LANGUAGE_FAILED";
const RESET_LANGUAGE = "RESET_LANGUAGE";
const GET_GUEST_TITLE = "GET_GUEST_TITLE";
const GET_GUEST_TITLE_SUCCESS = "GET_GUEST_TITLE_SUCCESS";
const GET_GUEST_TITLE_FAILED = "GET_GUEST_TITLE_FAILED";
const RESET_GUEST_TITLE = "RESET_GUEST_TITLE";

const GET_CITY_BYCOUNTRYID_START = "GET_CITY_BYCOUNTRYID_START";
const GET_CITY_BYCOUNTRYID_SUCCESS = "GET_CITY_BYCOUNTRYID_SUCCESS";
const GET_CITY_BYCOUNTRYID_FAILED = "GET_CITY_BYCOUNTRYID_FAILED";

const GET_MOVEMENTMODE = "GET_MOVEMENTMODE";
const GET_MOVEMENTMODE_SUCCESS = "GET_MOVEMENTMODE_SUCCESS";
const GET_MOVEMENTMODE_FAILED = "GET_MOVEMENTMODE_FAILED";

//Home
const GET_IMAGES_HOME = "GET_IMAGES_HOME";
const GET_IMAGES_HOME_SUCCESS = "GET_IMAGES_HOME_SUCCESS";
const GET_IMAGES_HOME_FAILED = "GET_IMAGES_HOME_FAILED";
const GET_FEATURED_PACKAGES = "GET_FEATURED_PACKAGES";
const GET_FEATURED_PACKAGES_SUCCESS = "GET_FEATURED_PACKAGES_SUCCESS";
const GET_FEATURED_PACKAGES_FAILED = "GET_FEATURED_PACKAGES_FAILED";
const RESET_FEATURED_PACKAGES = "RESET_FEATURED_PACKAGES";

//User
const GET_USER_PROFILE = "GET_USER_PROFILE";
const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
const GET_USER_PROFILE_FAILED = "GET_USER_PROFILE_FAILED";
const RESET_USER_PROFILE_GET = "RESET_USER_PROFILE_GET";

//fixed pacakge
const GET_FIXPACKAGES = "GET_FIXPACKAGES";
const GET_FIXPACKAGES_BY_TOUR_TYPE = "GET_FIXPACKAGES_BY_TOUR_TYPE";
const GET_FIXPACKAGES_SUCCESS = "GET_FIXPACKAGES_SUCCESS";
const GET_FIXPACKAGES_FAILED = "GET_FIXPACKAGES_FAILED";
const RESET_STATUS_FIXPACKAGES = "RESET_STATUS_FIXPACKAGES";

const GET_FIXPACKAGES_BY_ID = "GET_FIXPACKAGES_BY_ID";
const GET_FIXPACKAGES_BY_ID_SUCCESS = "GET_FIXPACKAGES_BY_ID_SUCCESS";
const GET_FIXPACKAGES_BY_ID_FAILED = "GET_FIXPACKAGES_BY_ID_FAILED";
const RESET_FIXPACKAGES_BY_ID = "RESET_FIXPACKAGES_BY_ID";

const GET_SUPPLEMENT_BY_ID = "GET_SUPPLEMENT_BY_ID";
const GET_SUPPLEMENT_BY_ID_SUCCESS = "GET_SUPPLEMENT_BY_ID_SUCCESS";
const GET_SUPPLEMENT_BY_ID_FAILED = "GET_SUPPLEMENT_BY_ID_FAILED";
const RESET_SUPPLEMENT_BY_ID = "RESET_SUPPLEMENT_BY_ID";

const POST_FIX_PACKAGES = "POST_FIX_PACKAGES";
const POST_FIX_PACKAGES_SUCCESS = "POST_FIX_PACKAGES_SUCCESS";
const POST_FIX_PACKAGES_FAILED = "POST_FIX_PACKAGES_FAILED";
const RESET_POST_FIX_PACKAGES = "RESET_POST_FIX_PACKAGES";

const POST_DEMO_FIX_PACKAGES = "POST_DEMO_FIX_PACKAGES";
const POST_DEMO_FIX_PACKAGES_SUCCESS = "POST_DEMO_FIX_PACKAGES_SUCCESS";
const POST_DEMO_FIX_PACKAGES_FAILED = "POST_DEMO_FIX_PACKAGES_FAILED";
const RESET_POST_DEMO_PRICE = "RESET_POST_DEMO_PRICE";

const POST_FIX_PACKAGES_ONHALF = "POST_FIX_PACKAGES_ONHALF";
const POST_FIX_PACKAGES_ONHALF_SUCCESS = "POST_FIX_PACKAGES_ONHALF_SUCCESS";
const POST_FIX_PACKAGES_ONHALF_FAILED = "POST_FIX_PACKAGES_ONHALF_FAILED";

const GET_USERINFO = "GET_USERINFO ";
const GET_USERINFO_SUCCESS = "GET_USERINFO_SUCCESS";
const GET_USERINFO_FAILED = "GET_USERINFO_FAILED";
const GET_USERROLES = "GET_USERROLES";
const GET_USERROLES_SUCCESS = "GET_USERROLES_SUCCESS";
const GET_USERROLES_FAILED = "GET_USERROLES_FAILED";

const GET_COMPANY_PROFILE = "GET_COMPANY_PROFILE";
const GET_COMPANY_PROFILE_SUCCESS = "GET_COMPANY_PROFILE_SUCCESS";
const GET_COMPANY_PROFILE_FAILED = "GET_COMPANY_PROFILE_FAILED";
const RESET_COMPANY_PROFILE_GET = "RESET_COMPANY_PROFILE_GET";

const REMOVE_COMPANY_LOGO = "REMOVE_COMPANY_LOGO";
const REMOVE_COMPANY_LOGO_SUCCESS = "REMOVE_COMPANY_LOGO_SUCCESS";
const REMOVE_COMPANY_LOGO_FAILED = "REMOVE_COMPANY_LOGO_FAILED";

const CHANGE_PASSWORD = " CHANGE_PASSWORD";
const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

const POST_USER_PROFILE = "POST_USER_PROFILE";
const POST_USER_PROFILE_SUCCESS = "POST_USER_PROFILE_SUCCESS";
const POST_USER_PROFILE_FAILED = "POST_USER_PROFILE_FAILED";
const RESET_USER_PROFILE = "RESET_USER_PROFILE";

const GET_USER_LIST = "GET_USER_LIST";
const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
const GET_USER_LIST_FAILED = "GET_USER_LIST_FAILED";
const POST_COMPANY_USER = "POST_COMPANY_USER";
const POST_COMPANY_USER_SUCCESS = "POST_COMPANY_USER_SUCCESS";
const POST_COMPANY_USER_FAILED = "POST_COMPANY_USER_FAILED";
//History
const GET_BOOKING_CREATED = "GET_BOOKING_CREATED";
const GET_BOOKING_CREATED_SUCCESS = "GET_BOOKING_CREATED_SUCCESS";
const GET_BOOKING_CREATED_FAILED = "GET_BOOKING_CREATED_FAILED";

const GET_BOOKING_INPAYMENT = "GET_BOOKING_INPAYMENT";
const GET_BOOKING_INPAYMENT_SUCCESS = "GET_BOOKING_INPAYMENT_SUCCESS";
const GET_BOOKING_INPAYMENT_FAILED = "GET_BOOKING_INPAYMENT_FAILED";

const GET_BOOKING_CONFIRMED = "GET_BOOKING_CONFIRMED";
const GET_BOOKING_CONFIRMED_SUCCESS = "GET_BOOKING_CONFIRMED_SUCCESS";
const GET_BOOKING_CONFIRMED_FAILED = "GET_BOOKING_CONFIRMED_FAILED";

const GET_BOOKING_COMPLETED = "GET_BOOKING_COMPLETED";
const GET_BOOKING_COMPLETED_SUCCESS = "GET_BOOKING_COMPLETED_SUCCESS";
const GET_BOOKING_COMPLETED_FAILED = "GET_BOOKING_COMPLETED_FAILED";

const GET_BOOKING_CANCEL = "GET_BOOKING_CANCEL";
const GET_BOOKING_CANCEL_SUCCESS = "GET_BOOKING_CANCEL_SUCCESS";
const GET_BOOKING_CANCEL_FAILED = "GET_BOOKING_CANCEL_FAILED";

const RESET_STATUS_HISTORY_CREATED = "RESET_STATUS_HISTORY_CREATED";
const RESET_STATUS_HISTORY_INPAYMENT = "RESET_STATUS_HISTORY_INPAYMENT";
const RESET_STATUS_HISTORY_CONFIRMED = "RESET_STATUS_HISTORY_CONFIRMED";
const RESET_STATUS_HISTORY_COMPLETED = "RESET_STATUS_HISTORY_COMPLETED";
const RESET_STATUS_HISTORY_CANCEL = "RESET_STATUS_HISTORY_CANCEL";

const GET_TOUR_SCHEDULE = "GET_TOUR_SCHEDULE";
const GET_TOUR_SCHEDULE_SUCCESS = "GET_TOUR_SCHEDULE_SUCCESS";
const GET_TOUR_SCHEDULE_FAILED = "GET_TOUR_SCHEDULE_FAILED";

const GET_BROCURE = "GET_BROCURE";
const GET_BROCURE_SUCCESS = "GET_BROCURE_SUCCESS";
const GET_BROCURE_FAILED = "GET_BROCURE_FAILED";

//get status unread for my booking
const GET_STATUS_UNREAD_BOOKING = "GET_STATUS_UNREAD_BOOKING";
const GET_STATUS_UNREAD_BOOKING_SUCCESS = "GET_STATUS_UNREAD_BOOKING_SUCCESS";
const GET_STATUS_UNREAD_BOOKING_FAILED = "GET_STATUS_UNREAD_BOOKING_FAILED";

const GET_STATUS_UNREAD_BOOKING_QUOTATION =
  "GET_STATUS_UNREAD_BOOKING_QOUTATOIN";
const GET_STATUS_UNREAD_BOOKING_CREATED = "GET_STATUS_UNREAD_BOOKING_CREATED";
const GET_STATUS_UNREAD_BOOKING_INPAYMENT =
  "GET_STATUS_UNREAD_BOOKING_INPAYMENT";
const GET_STATUS_UNREAD_BOOKING_COMPLETED =
  "GET_STATUS_UNREAD_BOOKING_COMPLETED";
const GET_STATUS_UNREAD_BOOKING_CONFIRMED =
  "GET_STATUS_UNREAD_BOOKING_CONFIRMED";
const GET_STATUS_UNREAD_BOOKING_CANCELLED =
  "GET_STATUS_UNREAD_BOOKING_CANCELLED";
// success and failed for status created
const GET_STATUS_UNREAD_BOOKING_SUCCESS_CREATED =
  "GET_STATUS_UNREAD_BOOKING_SUCCESS_CREATED";
const GET_STATUS_UNREAD_BOOKING_FAILED_CREATED =
  "GET_STATUS_UNREAD_BOOKING_FAILED_CREATED";
// success and failed for status INPAYMENT
const GET_STATUS_UNREAD_BOOKING_SUCCESS_INPAYMENT =
  "GET_STATUS_UNREAD_BOOKING_SUCCESS_INPAYMENT";
const GET_STATUS_UNREAD_BOOKING_FAILED_INPAYMENT =
  "GET_STATUS_UNREAD_BOOKING_FAILED_INPAYMENT";
// success and failed for status confirmed
const GET_STATUS_UNREAD_BOOKING_SUCCESS_CONFIRMED =
  "GET_STATUS_UNREAD_BOOKING_SUCCESS_CONFIRMED";
const GET_STATUS_UNREAD_BOOKING_FAILED_CONFIRMED =
  "GET_STATUS_UNREAD_BOOKING_FAILED_CONFIRMED";
// success and failed for status completed
const GET_STATUS_UNREAD_BOOKING_SUCCESS_COMPLETED =
  "GET_STATUS_UNREAD_BOOKING_SUCCESS_COMPLETED";
const GET_STATUS_UNREAD_BOOKING_FAILED_COMPLETED =
  "GET_STATUS_UNREAD_BOOKING_FAILED_COMPLETED";
// success and failed for status cancelled
const GET_STATUS_UNREAD_BOOKING_SUCCESS_CANCELLED =
  "GET_STATUS_UNREAD_BOOKING_SUCCESS_CANCELLED";
const GET_STATUS_UNREAD_BOOKING_FAILED_CANCELLED =
  "GET_STATUS_UNREAD_BOOKING_FAILED_CANCELLED";
// success and failed for status quotation
const GET_STATUS_UNREAD_BOOKING_SUCCESS_QUOTATION =
  "GET_STATUS_UNREAD_BOOKING_SUCCESS_QUOTATION";
const GET_STATUS_UNREAD_BOOKING_FAILED_QUOTATION =
  "GET_STATUS_UNREAD_BOOKING_FAILED_QUOTATION";
const RESET_STATUS_UNREAD_BOOKING = "RESET_STATUS_UNREAD_BOOKING";
///////
const RESET_CHANGE_PASSWORD = "RESET_CHANGE_PASSWORD";
const POST_COMPANY_EDIT = "POST_COMPANY_EDIT";
const POST_COMPANY_EDIT_SUCCESS = "POST_COMPANY_EDIT_SUCCESS";
const POST_COMPANY_EDIT_FAILED = "POST_COMPANY_EDIT_FAILED";
const RESET_COMPANY_EDIT = "RESET_COMPANY_EDIT";

const GET_ID = "GET_ID";
const RESET_POST_COMPANY_USER = "RESET_POST_COMPANY_USER";
const GET_TOUR_OPERATOR_PROFILE = "GET_TOUR_OPERATOR_PROFILE";
const GET_TOUR_OPERATOR_PROFILE_SUCCESS = "GET_TOUR_OPERATOR_PROFILE_SUCCESS";
const GET_TOUR_OPERATOR_PROFILE_FAILED = "GET_TOUR_OPERATOR_PROFILE_FAILED";
const RESET_TOUR_OPERATOR_PROFILE = "RESET_TOUR_OPERATOR_PROFILE";
//Ready
const GET_READYPACKAGES = "GET_READYPACKAGES";
const GET_READYPACKAGES_SUCCESS = "GET_READYPACKAGES_SUCCESS";
const GET_READYPACKAGES_FAILED = "GET_READYPACKAGES_FAILED";
const GET_READYPACKAGES_BY_ID = "GET_READYPACKAGES_BY_ID";
const GET_READYPACKAGES_BY_ID_SUCCESS = "GET_READYPACKAGES_BY_ID_SUCCESS";
const GET_READYPACKAGES_BY_ID_FAILED = "GET_READYPACKAGES_BY_ID_FAILED";
const RESET_READYPACKAGES_BY_ID = " RESET_READYPACKAGES_BY_ID";

// Custom Package //
const CUSTOM_ITENERARY = "CUSTOM_ITENERARY";
const RESET_CUSTOM_ITENERARY = "RESET_CUSTOM_ITENERARY";
const SET_DEPARTURES_ITINERARY = "SET_DEPARTURES_ITINERARY";
const RESET_DEPARTURES_ITINERARY = "RESET_DEPARTURES_ITINERARY";
const SET_RETURNS_ITINERARY = "SET_RETURNS_ITINERARY";
const RESET_RETURNS_ITINERARY = "RESET_RETURNS_ITINERARY";
const ARRIVAL_ITENERARY = "ARRIVAL_ITENERARY";
const RESET_ARRIVAL_ITENERARY = "RESET_ARRIVAL_ITENERARY";
const DEPATURE_ITENERARY = "DEPATURE_ITENERARY";
const RESET_DEPATURE_ITENERARY = "RESET_DEPATURE_ITENERARY";
const SUMMARY_PROGRAM = "SUMMARY_PROGRAM";
const RESET_SUMMARY_PROGRAM = "RESET_SUMMARY_PROGRAM";
const DAILY_PROGRAM = "DAILY_PROGRAM";
const RESET_DAILY_PROGRAM = "RESET_DAILY_PROGRAM";
const GUEST_ITENERARY = "GUEST_ITENERARY";
const RESET_GUEST_ITENERARY = "RESET_GUEST_ITENERARY";
const SET_TOUROPERATOR = "SET_TOUROPERATOR";
const RESET_TOUROPERATOR = "RESET_TOUROPERATOR";
const SET_GUEST_QUOTATION = "SET_GUEST_QUOTATION";
const RESET_GUEST_QUOTATION = "RESET_GUEST_QUOTATION";
//Item Itenerary
///Hotel
const GET_ACCOMMODATION_FILTER = "GET_ACCOMMODATION_FILTER";
const RESET_ACCOMMODATION_FILTER = "RESET_ACCOMMODATION_FILTER";
const GET_ACCOMMODATION_FILTER_SUCCESS = "GET_ACCOMMODATION_FILTER_SUCCESS";
const GET_ACCOMMODATION_FILTER_FAILED = "GET_ACCOMMODATION_FILTER_FAILED";

const GET_ACCOMMODATION = "GET_ACCOMMODATION";
const RESET_ACCOMMODATION = "RESET_ACCOMMODATION";
const GET_ACCOMMODATION_SUCCESS = "GET_ACCOMMODATION_SUCCESS";
const GET_ACCOMMODATION_FAILED = "GET_ACCOMMODATION_FAILED";
const SET_CITY_ACCOMMODATION = "SET_CITY_ACCOMMODATION";

const GET_ACCOMMODATION_ITEM = "GET_ACCOMMODATION_ITEM";
const GET_ACCOMMODATION_ITEM_SUCCESS = "GET_ACCOMMODATION_ITEM_SUCCESS";
const GET_ACCOMMODATION_ITEM_FAILED = "GET_ACCOMMODATION_ITEM_FAILED";
const GET_ROOM_ACCOMODATION_ITEM = "GET_ROOM_ACCOMODATION_ITEM";
const GET_ROOM_ACCOMODATION_ITEM_SUCCESS = "GET_ROOM_ACCOMODATION_ITEM_SUCCESS";
const GET_ROOM_ACCOMODATION_ITEM_FAILED = "GET_ROOM_ACCOMODATION_ITEM_FAILED";
const RESET_GET_ROOM_ACCOMODATION = "RESET_GET_ROOM_ACCOMODATION";
const GET_ACCOMMODATION_PROFILE = "GET_ACCOMMODATION_PROFILE";
const GET_ACCOMMODATION_PROFILE_SUCCESS = "GET_ACCOMMODATION_PROFILE_SUCCESS";
const GET_ACCOMMODATION_PROFILE_FAILED = "GET_ACCOMMODATION_PROFILE_FAILED";
const RESET_ACCOMMODATION_PROFILE = "RESET_ACCOMMODATION_PROFILE";

///Transport
const GET_TRANSPORT_SEAT_FILTER = "GET_TRANSPORT_SEAT_FILTER";
const GET_TRANSPORT_SEAT_FILTER_SUCCESS = "GET_TRANSPORT_SEAT_FILTER_SUCCESS";
const GET_TRANSPORT_SEAT_FILTER_FAILED = "GET_TRANSPORT_SEAT_FILTER_FAILED";
const GET_TRANSPORT_RATING_FILTER = "GET_TRANSPORT_RATING_FILTER";
const GET_TRANSPORT_RATING_FILTER_SUCCESS =
  "GET_TRANSPORT_RATING_FILTER_SUCCESS";
const GET_TRANSPORT_RATING_FILTER_FAILED = "GET_TRANSPORT_RATING_FILTER_FAILED";
const GET_TRANSPORT_TYPE_FILTER = "GET_TRANSPORT_TYPE_FILTER";
const GET_TRANSPORT_TYPE_FILTER_SUCCESS = "GET_TRANSPORT_TYPE_FILTER_SUCCESS";
const GET_TRANSPORT_TYPE_FILTER_FAILED = "GET_TRANSPORT_TYPE_FILTER_FAILED";
const GET_TRANSPORT = "GET_TRANSPORT";
const GET_TRANSPORT_SUCCESS = "GET_TRANSPORT_SUCCESS";
const GET_TRANSPORT_FAILED = "GET_TRANSPORT_FAILED";
const RESET_GET_TRANSPORT = "RESET_GET_TRANSPORT";

///Attraction
const GET_ATTRACTION_TYPE_FILTER = "GET_ATTRACTION_TYPE_FILTER";
const GET_ATTRACTION_TYPE_FILTER_SUCCESS = "GET_ATTRACTION_TYPE_FILTER_SUCCESS";
const GET_ATTRACTION_TYPE_FILTER_FAILED = "GET_ATTRACTION_TYPE_FILTER_FAILED";
const GET_ATTRACTION = "GET_ATTRACTION";
const GET_ATTRACTION_SUCCESS = "GET_ATTRACTION_SUCCESS";
const GET_ATTRACTION_FAILED = "GET_ATTRACTION_SUCCESS";
const RESET_GET_ATTRACTION = "RESET_GET_ATTRACTION";
///Restaurant
const GET_RESTAURANT = "GET_RESTAURANT";
const GET_RESTAURANT_SUCCESS = "GET_RESTAURANT_SUCCESS";
const GET_RESTAURANT_FAILED = "GET_RESTAURANT_FAILED";
const RESET_GET_RESTAURANT = "RESET_GET_RESTAURANT";
const GET_MENU_CLASSES = "GET_MENU_CLASSES";
const GET_MENU_CLASSES_SUCCESS = "GET_MENU_CLASSES_SUCCESS";
const GET_MENU_CLASSES_FAILED = "GET_MENU_CLASSES_FAILED";
const GET_MENU_CATEGORY = "GET_MENU_CATEGORY";
const GET_MENU_CATEGORY_SUCCESS = "GET_MENU_CATEGORY_SUCCESS";
const GET_MENU_CATEGORY_FAILED = "GET_MENU_CATEGORY_FAILED";
const GET_MENU_TYPES = "GET_MENU_TYPES";
const GET_MENU_TYPES_SUCCESS = "GET_MENU_TYPES_SUCCESS";
const GET_MENU_TYPES_FAILED = "GET_MENU_TYPES_FAILED";

///Airport
const SET_AIRPORT = "SET_AIRPORT";
const RESET_GET_AIRPORT = "RESET_GET_AIRPORT";
const GET_LIST_AIRPORT = "GET_LIST_AIRPORT";
const GET_LIST_AIRPORT_SUCCESS = "GET_LIST_AIRPORT_SUCCESS";
const GET_LIST_AIRPORT_FAILED = "GET_LIST_AIRPORT_FAILED";

//item Profile Detail
const GET_ACCOMMODATION_BY_ID = "GET_ACCOMMODATION_BY_ID";
const GET_ACCOMMODATION_BY_ID_SUCCESS = "GET_ACCOMMODATION_BY_ID_SUCCESS";
const GET_ACCOMMODATION_BY_ID_FAILED = "GET_ACCOMMODATION_BY_ID_FAILED";
const GET_ACCOMMODATION_BY_SERVICE_ITEM_ID =
  "GET_ACCOMMODATION_BY_SERVICE_ITEM_ID";
const GET_ACCOMMODATION_BY_SERVICE_ITEM_ID_SUCCESS =
  "GET_ACCOMMODATION_BY_SERVICE_ITEM_ID_SUCCESS";
const GET_ACCOMMODATION_BY_SERVICE_ITEM_ID_FAILED =
  "GET_ACCOMMODATION_BY_SERVICE_ITEM_ID_FAILED";
const RESET_GET_ACCOMODATION_BY_ID = "RESET_GET_ACCOMODATION_BY_ID";
const GET_ATTRACTION_BY_ID = "GET_ATTRACTION_BY_ID";
const GET_ATTRACTION_BY_ID_SUCCESS = "GET_ATTRACTION_BY_ID_SUCCESS";
const GET_ATTRACTION_BY_ID_FAILED = "GET_ATTRACTION_BY_ID_FAILED";
const GET_RESTAURANT_BY_SERVICE_ITEM_ID = "GET_RESTAURANT_BY_SERVICE_ITEM_ID";
const GET_RESTAURANT_BY_SERVICE_ITEM_ID_SUCCESS =
  "GET_RESTAURANT_BY_SERVICE_ITEM_ID_SUCCESS";
const GET_RESTAURANT_BY_SERVICE_ITEM_ID_FAILED =
  "GET_RESTAURANT_BY_SERVICE_ITEM_ID_FAILED";
const RESET_GET_RESTAURANT_BY_SERVICE_ITEM_ID =
  "RESET_GET_RESTAURANT_BY_SERVICE_ITEM_ID";
const GET_RESTAURANT_BY_ID = "GET_RESTAURANT_BY_ID";
const GET_RESTAURANT_BY_ID_SUCCESS = "GET_RESTAURANT_BY_ID_SUCCESS";
const GET_RESTAURANT_BY_ID_FAILED = "GET_RESTAURANT_BY_ID_FAILED";
const RESET_GET_RESTAURANT_BY_ID = "RESET_GET_RESTAURANT_BY_ID";
const RESET_GET_ATTRACTION_BY_ID = "RESET_GET_ATTRACTION_BY_ID";
//get driving time
const SET_DRIVING = "SET_DRIVING";

//Transaction
const GET_TRANSACTION_BY_ID = "GET_TRANSACTION_BY_ID";
const GET_TRANSACTION_BY_ID_SUCCESS = "GET_TRANSACTION_BY_ID_SUCCESS";
const GET_TRANSACTION_BY_ID_FAILED = "GET_TRANSACTION_BY_ID_FAILED";

const RESET_TRANSACTION_BY_ID = "RESET_TRANSACTION_BY_ID";
const UPDATE_GUEST_LIST = "UPDATE_GUEST_LIST";
const UPDATE_GUEST_LIST_SUCCESS = "UPDATE_GUEST_LIST_SUCCESS";
const UPDATE_GUEST_LIST_FAILED = "UPDATE_GUEST_LIST_FAILED";
const GET_SUPPLEMENT_TRANSACTION_BY_ID = "GET_SUPPLEMENT_TRANSACTION_BY_ID";
const GET_SUPPLEMENT_TRANSACTION_BY_ID_SUCCESS =
  "GET_SUPPLEMENT_TRANSACTION_BY_ID_SUCCESS";
const GET_SUPPLEMENT_TRANSACTION_BY_ID_FAILED =
  "GET_SUPPLEMENT_TRANSACTION_BY_ID_FAILED";
const GET_INVOICE_TRANSACTION = "GET_INVOICE_TRANSACTION";
const GET_INVOICE_TRANSACTION_SUCCESS = "GET_INVOICE_TRANSACTION_SUCCESS";
const GET_INVOICE_TRANSACTION_FAILED = "GET_INVOICE_TRANSACTION_FAILED";
const GET_INVOICE_TRAVEL_AGENT = "GET_INVOICE_TRAVEL_AGENT";
const GET_INVOICE_TRAVEL_AGENT_SUCCESS = "GET_INVOICE_TRAVEL_AGENT_SUCCESS";
const GET_INVOICE_TRAVEL_AGENT_FAILED = "GET_INVOICE_TRAVEL_AGENT_FAILED";
const GET_INVOICE_GUEST = "GET_INVOICE_GUEST";
const GET_INVOICE_GUEST_SUCCESS = "GET_INVOICE_GUEST_SUCCESS";
const GET_INVOICE_GUEST_FAILED = "GET_INVOICE_GUEST_FAILED";
const GET_SCHEDULE_TRANSACTION = "GET_SCHEDULE_TRANSACTION";
const GET_SCHEDULE_TRANSACTION_SUCCESS = "GET_SCHEDULE_TRANSACTION_SUCCESS";
const GET_SCHEDULE_TRANSACTION_FAILED = "GET_SCHEDULE_TRANSACTION_FAILED";

const GET_VOUCHER_CONFIRMATION = "GET_VOUCHER_CONFIRMATION";
const GET_VOUCHER_CONFIRMATION_SUCCESS = "GET_VOUCHER_CONFIRMATION_SUCCESS";
const GET_VOUCHER_CONFIRMATION_FAILED = "GET_VOUCHER_CONFIRMATION_FAILED";

//advancefilter
const GET_COUNTRY_BYPAXTYPE = "GET_COUNTRY_BYPAXTYPE";
const GET_COUNTRY_BYPAXTYPE_SUCCESS = "GET_COUNTRY_BYPAXTYPE_SUCCESS";
const GET_COUNTRY_BYPAXTYPE_FAILED = "GET_COUNTRY_BYPAXTYPE_FAILED";
const GET_CITY_BYPAXTYPE_COUNTRYID = "GET_CITY_BYPAXTYPE_COUNTRYID";
const GET_CITY_BYPAXTYPE_COUNTRYID_SUCCESS =
  "GET_CITY_BYPAXTYPE_COUNTRYID_SUCCESS";
const GET_CITY_BYPAXTYPE_COUNTRYID_FAILED =
  "GET_CITY_BYPAXTYPE_COUNTRYID_FAILED";
const GET_REGION_BYCOUNTRY = "GET_REGION_BYCOUNTRY";
const GET_REGION_BYCOUNTRY_SUCCESS = "GET_REGION_BYCOUNTRY_SUCCESS";
const GET_REGION_BYCOUNTRY_FAILED = "GET_REGION_BYCOUNTRY_FAILED";

const GET_BOOKING_FILTER = "GET_BOOKING_FILTER";
const GET_BOOKING_FILTER_SUCCESS = "GET_BOOKING_FILTER_SUCCESS";
const GET_BOOKING_FILTER_FAILED = "GET_BOOKING_FILTER_FAILED";

const GET_ACCOMMODATION_RATINGS = "GET_ACCOMMODATION_RATINGS";
const GET_ACCOMMODATION_RATINGS_SUCCESS = "GET_ACCOMMODATION_RATINGS_SUCCESS";
const GET_ACCOMMODATION_RATINGS_FAILED = "GET_ACCOMMODATION_RATINGS_FAILED";

const GET_ACCOMMODATION_AREAS = "GET_ACCOMMODATION_AREAS";
const GET_ACCOMMODATION_AREAS_SUCCESS = "GET_ACCOMMODATION_AREAS_SUCCESS";
const GET_ACCOMMODATION_AREAS_FAILED = "GET_ACCOMMODATION_AREAS_FAILED";

const GET_ACCOMMODATION_LOCATIONS = "GET_ACCOMMODATION_LOCATIONS";
const GET_ACCOMMODATION_LOCATIONS_SUCCESS =
  "GET_ACCOMMODATION_LOCATIONS_SUCCESS";
const GET_ACCOMMODATION_LOCATIONS_FAILED = "GET_ACCOMMODATION_LOCATIONS_FAILED";

const GET_ACCOMMODATION_TYPES = "GET_ACCOMMODATION_TYPES";
const GET_ACCOMMODATION_TYPES_SUCCESS = "GET_ACCOMMODATION_TYPES_SUCCESS";
const GET_ACCOMMODATION_TYPES_FAILED = "GET_ACCOMMODATION_TYPES_FAILED";

const GET_ACCOMMODATION_FACILITIES = "GET_ACCOMMODATION_FACILITIES";
const GET_ACCOMMODATION_FACILITIES_SUCCESS =
  "GET_ACCOMMODATION_FACILITIES_SUCCESS";
const GET_ACCOMMODATION_FACILITIES_FAILED =
  "GET_ACCOMMODATION_FACILITIES_FAILED";

const GET_ACCOMMODATION_NAME = "GET_ACCOMMODATION_NAME";
const GET_ACCOMMODATION_NAME_SUCCESS = "GET_ACCOMMODATION_NAME_SUCCESS";
const GET_ACCOMMODATION_NAME_FAILED = "GET_ACCOMMODATION_NAME_FAILED";

const GET_RESTAURANT_SPECIALIZATIONS = "GET_RESTAURANT_SPECIALIZATIONS";
const GET_RESTAURANT_SPECIALIZATIONS_SUCCESS =
  "GET_RESTAURANT_SPECIALIZATIONS_SUCCESS";
const GET_RESTAURANT_SPECIALIZATIONS_FAILED =
  "GET_RESTAURANT_SPECIALIZATIONS_FAILED";

const RESET_ADVANCE_FILTER = "RESET_ADVANCE_FILTER";

//my qoutation
const GET_MY_QOUTATION = "GET_MY_QOUTATION";
const GET_MY_QOUTATION_SUCCESS = "GET_MY_QOUTATION_SUCCESS";
const GET_MY_QOUTATION_FAILED = "GET_MY_QOUTATION_FAILED";
const RESET_MY_QOUTATION = "RESET_MY_QOUTATION";
const POST_QUOTATION = "POST_QUOTATION";
const POST_QUOTATION_SUCCESS = "POST_QUOTATION_SUCCESS";
const POST_QUOTATION_FAILED = "POST_QUOTATION_FAILED";
const RESET_QUOTATION = "RESET_QUOTATION";

//Payment
const GET_TOBE_PAYED = "GET_TOBE_PAYED";
const GET_TOBE_PAYED_SUCCESS = "GET_TOBE_PAYED_SUCCESS";
const GET_TOBE_PAYED_FAILED = "GET_TOBE_PAYED_FAILED";
const GET_CONFIRMATION_DEMO = "GET_CONFIRMATION_DEMO";
const GET_CONFIRMATION_DEMO_SUCCESS = "GET_CONFIRMATION_DEMO_SUCCESS";
const GET_CONFIRMATION_DEMO_FAILED = "GET_CONFIRMATION_DEMO_FAILED";
const RESET_CONFIRMATION_DEMO = "RESET_CONFIRMATION_DEMO";
const GET_CONFIRMATION = "GET_CONFIRMATION";
const GET_CONFIRMATION_CANCEL_SUCCESS = "GET_CONFIRMATION_CANCEL_SUCCESS";
const GET_CONFIRMATION_CANCEL_FAILED = "GET_CONFIRMATION_CANCEL_FAILED";
const GET_CONFIRMATION_SUCCESS = "GET_CONFIRMATION_SUCCESS";
const GET_CONFIRMATION_FAILED = "GET_CONFIRMATION_FAILED";
const RESET_CONFIRMATION = "RESET_CONFIRMATION";
const GET_TOPUP = "GET_TOPUP";
const GET_TOPUP_SUCCESS = "GET_TOPUP_SUCCESS";
const GET_TOPUP_FAILED = "GET_TOPUP_FAILED";
const GET_BANK_ACCOUNT = "GET_BANK_ACCOUNT";
const GET_BANK_ACCOUNT_SUCCESS = "GET_BANK_ACCOUNT_SUCCESS";
const GET_BANK_ACCOUNT_FAILED = "GET_BANK_ACCOUNT_FAILED";
const GET_BILLED = "GET_BILLED";
const GET_BILLED_SUCCESS = "GET_BILLED_SUCCESS";
const GET_BILLED_FAILED = "GET_BILLED_FAILED";
const GET_BILLS = "GET_BILLS";
const GET_BILLS_SUCCESS = "GET_BILLS_SUCCESS";
const GET_BILLS_FAILED = "GET_BILLS_FAILED";

//Transaction
const GET_TOUR_OPERATOR_LIST = "GET_TOUR_OPERATOR_LIST";
const GET_TOUR_OPERATOR_LIST_SUCCESS = "GET_TOUR_OPERATOR_LIST_SUCCESS";
const GET_TOUR_OPERATOR_LIST_FAILED = "GET_TOUR_OPERATOR_LIST_FAILED";
const RESET_TOUR_OPERATOR_LIST = "RESET_TOUR_OPERATOR_LIST";
const GET_TOUR_OPERATOR_PROFILE_LIST = "GET_TOUR_OPERATOR_PROFILE_LIST";
const GET_TOUR_OPERATOR_PROFILE_LIST_SUCCESS =
  "GET_TOUR_OPERATOR_PROFILE_LIST_SUCCESS";
const GET_TOUR_OPERATOR_PROFILE_LIST_FAILED =
  "GET_TOUR_OPERATOR_PROFILE_LIST_FAILED";

const SET_ITEM_TRANSACTION = "SET_ITEM_TRANSACTION";
const RESET_ITEM_TRANSACTION = "RESET_ITEM_TRANSACTION";

const GET_REASON = "GET_REASON";
const GET_REASON_SUCCESS = "GET_REASON_SUCCESS";
const GET_REASON_FAILED = "GET_REASON_FAILED";

const POST_DEMO_CUSTOM = "POST_DEMO_CUSTOM";
const RESET_POST_DEMO_CUSTOM = "RESET_POST_DEMO_CUSTOM";
const POST_DEMO_CUSTOM_FAILED = "POST_DEMO_CUSTOM_FAILED";
const POST_DEMO_CUSTOM_SUCCESS = "POST_DEMO_CUSTOM_SUCCESS";

const POST_CREATE_CUSTOM = "POST_CREATE_CUSTOM";
const RESET_POST_CREATE_CUSTOM = "RESET_POST_CREATE_CUSTOM";
const POST_CREATE_CUSTOM_FAILED = "POST_CREATE_CUSTOM_FAILED";
const POST_CREATE_CUSTOM_SUCCESS = "POST_CREATE_CUSTOM_SUCCESS";

const POST_CREATE_CUSTOM_ONBEHALF = "POST_CREATE_CUSTOM_ONBEHALF";
const POST_CREATE_CUSTOM_ONBEHALF_FAILED = "POST_CREATE_CUSTOM_ONBEHALF_FAILED";
const POST_CREATE_CUSTOM_ONBEHALF_SUCCESS =
  "POST_CREATE_CUSTOM_ONBEHALF_SUCCESS";

const POST_EDIT_QUOTATION = "POST_EDIT_QUOTATION";
const POST_EDIT_QUOTATION_SUCCESS = "POST_EDIT_QUOTATION_SUCCESS";
const POST_EDIT_QUOTATION_FAILED = "POST_EDIT_QUOTATION_FAILED";

const GET_LIST_COMPANY = "GET_LIST_COMPANY";
const RESET_LIST_COMPANY = "RESET_LIST_COMPANY";
const GET_LIST_COMPANY_SUCCESS = "GET_LIST_COMPANY_SUCCESS";
const GET_LIST_COMPANY_FAILED = "GET_LIST_COMPANY_FAILED";

const SIMPLE_REGISTER_COMPANY = "SIMPLE_REGISTER_COMPANY";
const SIMPLE_REGISTER_COMPANY_SUCCESS = "SIMPLE_REGISTER_COMPANY_SUCCESS";
const SIMPLE_REGISTER_COMPANY_FAILED = "SIMPLE_REGISTER_COMPANY_FAILED";
const RESET_SIMPLE_REGISTER_COMPANY = "RESET_SIMPLE_REGISTER_COMPANY";
const GET_USERID_BY_COMPANYCODE = "GET_USERID_BY_COMPANYCODE";
const GET_USERID_BY_COMPANYCODE_SUCCESS = "GET_USERID_BY_COMPANYCODE_SUCCESS";
const GET_USERID_BY_COMPANYCODE_FAILED = "GET_USERID_BY_COMPANYCODE_FAILED";
const RESET_GET_USERID = "RESET_GET_USERID";

const SET_ADDITIONAL_SERVICE = "SET_ADDITIONAL_SERVICE";
const RESET_ADDITIONAL_SERVICE = "RESET_ADDITIONAL_SERVICE";

//Tour Guide

const SET_GUEST_TOUR_GUIDE = "SET_GUEST_TOUR_GUIDE";

//Additional Service
const GET_ADDITIONAL_SERVICE = "GET_ADDITIONAL_SERVICE";
const GET_ADDITIONAL_SERVICE_SUCCESS = "GET_ADDITIONAL_SERVICE_SUCCESS";
const GET_ADDITIONAL_SERVICE_FAILED = "GET_ADDITIONAL_SERVICE_FAILED";

const GET_ADDITIONAL_SERVICE_BY_ID = "GET_ADDITIONAL_SERVICE_BY_ID";
const GET_ADDITIONAL_SERVICE_BY_ID_SUCCESS =
  "GET_ADDITIONAL_SERVICE_BY_ID_SUCCESS";
const GET_ADDITIONAL_SERVICE_BY_ID_FAILED =
  "GET_ADDITIONAL_SERVICE_BY_ID_FAILED";

//Airline Ticket
const GET_LIST_TICKET = "GET_LIST_TICKET";
const GET_LIST_TICKET_SUCCESS = "GET_LIST_TICKET_SUCCESS";
const GET_LIST_TICKET_FAILED = "GET_LIST_TICKET_FAILED";
const RESET_LIST_TICKET = "RESET_LIST_TICKET";

const GET_TICKET_AIRLINE_BY_ID = "GET_TICKET_AIRLINE_BY_ID";
const GET_TICKET_AIRLINE_BY_ID_SUCCESS = "GET_TICKET_AIRLINE_BY_ID_SUCCESS";
const GET_TICKET_AIRLINE_BY_ID_FAILED = "GET_TICKET_AIRLINE_BY_ID_FAILED";

export {
  LOGOUT,
  RESET_STATUS_LOGIN,
  GET_TOKEN,
  LOGIN_FAILED,
  GET_IMAGES_HOME,
  GET_IMAGES_HOME_SUCCESS,
  GET_IMAGES_HOME_FAILED,
  GET_FEATURED_PACKAGES,
  GET_FEATURED_PACKAGES_SUCCESS,
  GET_FEATURED_PACKAGES_FAILED,
  RESET_FEATURED_PACKAGES,
  LOGIN_START,
  LOGIN_SUCCESS,
  REGISTER,
  REGISTER_SUCCESS,
  REGISTER_FAILED,
  RESET_REGISTER,
  FORGOT_PASSWORD,
  FORGOT_PASSWORD_SUCCESS,
  FORGOT_PASSWORD_FAILED,
  RESET_STATUS_FORGOT,
  //User and Company
  GET_USERINFO,
  GET_USERINFO_SUCCESS,
  GET_USERINFO_FAILED,
  GET_USER_PROFILE,
  GET_USER_PROFILE_SUCCESS,
  GET_USER_PROFILE_FAILED,
  GET_COMPANY_PROFILE,
  GET_COMPANY_PROFILE_SUCCESS,
  GET_COMPANY_PROFILE_FAILED,
  RESET_COMPANY_PROFILE_GET,
  REMOVE_COMPANY_LOGO,
  REMOVE_COMPANY_LOGO_SUCCESS,
  REMOVE_COMPANY_LOGO_FAILED,
  GET_USERROLES,
  GET_USERROLES_SUCCESS,
  GET_USERROLES_FAILED,
  RESET_USER_PROFILE_GET,
  //
  POST_USER_PROFILE,
  POST_USER_PROFILE_SUCCESS,
  POST_USER_PROFILE_FAILED,
  //General
  GET_TOTAL_BRANCH_START,
  GET_TOTAL_BRANCH_SUCCESS,
  GET_TOTAL_BRANCH_FAILED,
  GET_TOTAL_EMPLOYEE_START,
  GET_TOTAL_EMPLOYEE_SUCCESS,
  GET_TOTAL_EMPLOYEE_FAILED,
  GET_TOTAL_REVENUE_START,
  GET_TOTAL_REVENUE_SUCCESS,
  GET_TOTAL_REVENUE_FAILED,
  GET_TOTAL_CURRENCIES_START,
  GET_TOTAL_CURRENCIES_SUCCESS,
  GET_TOTAL_CURRENCIES_FAILED,
  GET_COUNTRY,
  RESET_COUNTRY,
  GET_COUNTRY_SUCCESS,
  GET_COUNTRY_FAILED,
  GET_PAX_TYPE_TOUR_START,
  GET_PAX_TYPE_TOUR_SUCCESS,
  GET_PAX_TYPE_TOUR_FAILED,
  GET_TYPE_TOUR_START,
  GET_TYPE_TOUR_SUCCESS,
  GET_TYPE_TOUR_FAILED,
  GET_CITY_INCOUNTRY_START,
  GET_CITY_INCOUNTRY_SUCCESS,
  GET_CITY_INCOUNTRY_FAILED,
  GET_CITY_BYCOUNTRYID_START,
  GET_CITY_BYCOUNTRYID_SUCCESS,
  GET_CITY_BYCOUNTRYID_FAILED,
  GET_MOVEMENTMODE,
  GET_MOVEMENTMODE_SUCCESS,
  GET_MOVEMENTMODE_FAILED,
  GET_LANGUAGE,
  GET_LANGUAGE_SUCCESS,
  GET_LANGUAGE_FAILED,
  RESET_LANGUAGE,
  GET_GUEST_TITLE,
  GET_GUEST_TITLE_SUCCESS,
  GET_GUEST_TITLE_FAILED,
  RESET_GUEST_TITLE,
  //
  CHANGE_PASSWORD,
  CHANGE_PASSWORD_SUCCESS,
  CHANGE_PASSWORD_FAILED,
  GET_USER_LIST,
  GET_USER_LIST_SUCCESS,
  GET_USER_LIST_FAILED,
  POST_COMPANY_USER,
  POST_COMPANY_USER_SUCCESS,
  POST_COMPANY_USER_FAILED,
  //Booking
  GET_BOOKING_CREATED,
  GET_BOOKING_INPAYMENT,
  GET_BOOKING_CONFIRMED,
  GET_BOOKING_COMPLETED,
  GET_BOOKING_CANCEL,
  GET_BOOKING_CREATED_SUCCESS,
  GET_BOOKING_CREATED_FAILED,
  GET_BOOKING_INPAYMENT_SUCCESS,
  GET_BOOKING_INPAYMENT_FAILED,
  GET_BOOKING_CONFIRMED_SUCCESS,
  GET_BOOKING_CONFIRMED_FAILED,
  GET_BOOKING_COMPLETED_SUCCESS,
  GET_BOOKING_COMPLETED_FAILED,
  GET_BOOKING_CANCEL_SUCCESS,
  GET_BOOKING_CANCEL_FAILED,
  GET_TOUR_SCHEDULE,
  GET_TOUR_SCHEDULE_SUCCESS,
  GET_TOUR_SCHEDULE_FAILED,
  RESET_STATUS_HISTORY_CREATED,
  RESET_STATUS_HISTORY_INPAYMENT,
  RESET_STATUS_HISTORY_CONFIRMED,
  RESET_STATUS_HISTORY_COMPLETED,
  RESET_STATUS_HISTORY_CANCEL,
  GET_BROCURE,
  GET_BROCURE_SUCCESS,
  GET_BROCURE_FAILED,
  GET_STATUS_UNREAD_BOOKING,
  GET_STATUS_UNREAD_BOOKING_SUCCESS,
  GET_STATUS_UNREAD_BOOKING_FAILED,
  RESET_STATUS_UNREAD_BOOKING,
  ///////
  RESET_CHANGE_PASSWORD,
  POST_COMPANY_EDIT,
  POST_COMPANY_EDIT_SUCCESS,
  POST_COMPANY_EDIT_FAILED,
  RESET_COMPANY_EDIT,
  GET_ID,
  RESET_POST_COMPANY_USER,
  RESET_USER_PROFILE,
  //Series Package
  GET_FIXPACKAGES,
  GET_FIXPACKAGES_SUCCESS,
  GET_FIXPACKAGES_FAILED,
  RESET_STATUS_FIXPACKAGES,
  GET_FIXPACKAGES_BY_ID,
  GET_FIXPACKAGES_BY_ID_SUCCESS,
  GET_FIXPACKAGES_BY_ID_FAILED,
  GET_FIXPACKAGES_BY_TOUR_TYPE,
  POST_FIX_PACKAGES,
  POST_FIX_PACKAGES_SUCCESS,
  POST_FIX_PACKAGES_FAILED,
  RESET_FIXPACKAGES_BY_ID,
  GET_SUPPLEMENT_BY_ID,
  GET_SUPPLEMENT_BY_ID_SUCCESS,
  GET_SUPPLEMENT_BY_ID_FAILED,
  RESET_SUPPLEMENT_BY_ID,
  POST_DEMO_FIX_PACKAGES,
  POST_DEMO_FIX_PACKAGES_SUCCESS,
  POST_DEMO_FIX_PACKAGES_FAILED,
  RESET_POST_DEMO_PRICE,
  POST_FIX_PACKAGES_ONHALF,
  POST_FIX_PACKAGES_ONHALF_SUCCESS,
  POST_FIX_PACKAGES_ONHALF_FAILED,
  GET_TOUR_OPERATOR_PROFILE,
  GET_TOUR_OPERATOR_PROFILE_SUCCESS,
  GET_TOUR_OPERATOR_PROFILE_FAILED,
  RESET_TOUR_OPERATOR_PROFILE,
  RESET_POST_FIX_PACKAGES,
  //Ready Package
  GET_READYPACKAGES,
  GET_READYPACKAGES_SUCCESS,
  GET_READYPACKAGES_FAILED,
  GET_READYPACKAGES_BY_ID,
  GET_READYPACKAGES_BY_ID_SUCCESS,
  GET_READYPACKAGES_BY_ID_FAILED,
  RESET_READYPACKAGES_BY_ID,
  //Custom Package
  CUSTOM_ITENERARY,
  RESET_CUSTOM_ITENERARY,
  SET_DEPARTURES_ITINERARY,
  RESET_DEPARTURES_ITINERARY,
  SET_RETURNS_ITINERARY,
  RESET_RETURNS_ITINERARY,
  ARRIVAL_ITENERARY,
  RESET_ARRIVAL_ITENERARY,
  DEPATURE_ITENERARY,
  RESET_DEPATURE_ITENERARY,
  SUMMARY_PROGRAM,
  RESET_SUMMARY_PROGRAM,
  DAILY_PROGRAM,
  RESET_DAILY_PROGRAM,
  GUEST_ITENERARY,
  RESET_GUEST_ITENERARY,
  SET_TOUROPERATOR,
  RESET_TOUROPERATOR,
  SET_GUEST_QUOTATION,
  RESET_GUEST_QUOTATION,
  //ITEM ITENERARY
  ///Hotel
  GET_ACCOMMODATION_FILTER,
  RESET_ACCOMMODATION_FILTER,
  GET_ACCOMMODATION_FILTER_SUCCESS,
  GET_ACCOMMODATION_FILTER_FAILED,
  GET_ACCOMMODATION,
  RESET_ACCOMMODATION,
  SET_CITY_ACCOMMODATION,
  GET_ACCOMMODATION_SUCCESS,
  GET_ACCOMMODATION_FAILED,
  GET_ACCOMMODATION_ITEM,
  GET_ACCOMMODATION_ITEM_SUCCESS,
  GET_ACCOMMODATION_ITEM_FAILED,
  GET_ROOM_ACCOMODATION_ITEM,
  GET_ROOM_ACCOMODATION_ITEM_SUCCESS,
  GET_ROOM_ACCOMODATION_ITEM_FAILED,
  RESET_GET_ROOM_ACCOMODATION,
  GET_ACCOMMODATION_PROFILE,
  GET_ACCOMMODATION_PROFILE_SUCCESS,
  GET_ACCOMMODATION_PROFILE_FAILED,
  RESET_ACCOMMODATION_PROFILE,
  ///Transport
  GET_TRANSPORT_SEAT_FILTER,
  GET_TRANSPORT_SEAT_FILTER_SUCCESS,
  GET_TRANSPORT_SEAT_FILTER_FAILED,
  GET_TRANSPORT_RATING_FILTER,
  GET_TRANSPORT_RATING_FILTER_SUCCESS,
  GET_TRANSPORT_RATING_FILTER_FAILED,
  GET_TRANSPORT_TYPE_FILTER,
  GET_TRANSPORT_TYPE_FILTER_SUCCESS,
  GET_TRANSPORT_TYPE_FILTER_FAILED,
  GET_TRANSPORT,
  GET_TRANSPORT_SUCCESS,
  GET_TRANSPORT_FAILED,
  RESET_GET_TRANSPORT,
  ///Attraction
  GET_ATTRACTION_TYPE_FILTER,
  GET_ATTRACTION_TYPE_FILTER_SUCCESS,
  GET_ATTRACTION_TYPE_FILTER_FAILED,
  GET_ATTRACTION,
  GET_ATTRACTION_SUCCESS,
  GET_ATTRACTION_FAILED,
  RESET_GET_ATTRACTION,
  RESET_GET_ATTRACTION_BY_ID,
  ///Restaurant
  GET_RESTAURANT,
  GET_RESTAURANT_SUCCESS,
  GET_RESTAURANT_FAILED,
  RESET_GET_RESTAURANT,
  RESET_GET_RESTAURANT_BY_ID,
  GET_MENU_CLASSES,
  GET_MENU_CLASSES_SUCCESS,
  GET_MENU_CLASSES_FAILED,
  GET_MENU_CATEGORY,
  GET_MENU_CATEGORY_SUCCESS,
  GET_MENU_CATEGORY_FAILED,
  GET_MENU_TYPES,
  GET_MENU_TYPES_SUCCESS,
  GET_MENU_TYPES_FAILED,
  ///Airport
  SET_AIRPORT,
  RESET_GET_AIRPORT,
  GET_LIST_AIRPORT,
  GET_LIST_AIRPORT_SUCCESS,
  GET_LIST_AIRPORT_FAILED,
  //item profile ID
  GET_ACCOMMODATION_BY_ID,
  GET_ACCOMMODATION_BY_ID_SUCCESS,
  GET_ACCOMMODATION_BY_ID_FAILED,
  RESET_GET_ACCOMODATION_BY_ID,
  GET_ACCOMMODATION_BY_SERVICE_ITEM_ID,
  GET_ACCOMMODATION_BY_SERVICE_ITEM_ID_SUCCESS,
  GET_ACCOMMODATION_BY_SERVICE_ITEM_ID_FAILED,
  GET_ATTRACTION_BY_ID,
  GET_ATTRACTION_BY_ID_SUCCESS,
  GET_ATTRACTION_BY_ID_FAILED,
  GET_RESTAURANT_BY_SERVICE_ITEM_ID,
  GET_RESTAURANT_BY_SERVICE_ITEM_ID_SUCCESS,
  GET_RESTAURANT_BY_SERVICE_ITEM_ID_FAILED,
  RESET_GET_RESTAURANT_BY_SERVICE_ITEM_ID,
  GET_RESTAURANT_BY_ID,
  GET_RESTAURANT_BY_ID_SUCCESS,
  GET_RESTAURANT_BY_ID_FAILED,
  //Get Driving
  SET_DRIVING,
  //transaction
  GET_TRANSACTION_BY_ID,
  GET_TRANSACTION_BY_ID_SUCCESS,
  GET_TRANSACTION_BY_ID_FAILED,
  RESET_TRANSACTION_BY_ID,
  UPDATE_GUEST_LIST,
  UPDATE_GUEST_LIST_SUCCESS,
  UPDATE_GUEST_LIST_FAILED,
  GET_SUPPLEMENT_TRANSACTION_BY_ID,
  GET_SUPPLEMENT_TRANSACTION_BY_ID_SUCCESS,
  GET_SUPPLEMENT_TRANSACTION_BY_ID_FAILED,
  GET_INVOICE_TRANSACTION,
  GET_INVOICE_TRANSACTION_SUCCESS,
  GET_INVOICE_TRANSACTION_FAILED,
  GET_INVOICE_TRAVEL_AGENT,
  GET_INVOICE_TRAVEL_AGENT_SUCCESS,
  GET_INVOICE_TRAVEL_AGENT_FAILED,
  GET_INVOICE_GUEST,
  GET_INVOICE_GUEST_SUCCESS,
  GET_INVOICE_GUEST_FAILED,
  GET_SCHEDULE_TRANSACTION,
  GET_SCHEDULE_TRANSACTION_SUCCESS,
  GET_SCHEDULE_TRANSACTION_FAILED,
  GET_VOUCHER_CONFIRMATION,
  GET_VOUCHER_CONFIRMATION_SUCCESS,
  GET_VOUCHER_CONFIRMATION_FAILED,
  SET_ADDITIONAL_SERVICE,
  RESET_ADDITIONAL_SERVICE,
  GET_REASON,
  GET_REASON_SUCCESS,
  GET_REASON_FAILED,
  //advancefilter
  GET_COUNTRY_BYPAXTYPE,
  GET_COUNTRY_BYPAXTYPE_SUCCESS,
  GET_COUNTRY_BYPAXTYPE_FAILED,
  GET_CITY_BYPAXTYPE_COUNTRYID,
  GET_CITY_BYPAXTYPE_COUNTRYID_SUCCESS,
  GET_CITY_BYPAXTYPE_COUNTRYID_FAILED,
  GET_REGION_BYCOUNTRY,
  GET_REGION_BYCOUNTRY_SUCCESS,
  GET_REGION_BYCOUNTRY_FAILED,
  GET_BOOKING_FILTER,
  GET_BOOKING_FILTER_SUCCESS,
  GET_BOOKING_FILTER_FAILED,
  GET_ACCOMMODATION_RATINGS,
  GET_ACCOMMODATION_RATINGS_SUCCESS,
  GET_ACCOMMODATION_RATINGS_FAILED,
  GET_ACCOMMODATION_AREAS,
  GET_ACCOMMODATION_AREAS_SUCCESS,
  GET_ACCOMMODATION_AREAS_FAILED,
  GET_ACCOMMODATION_LOCATIONS,
  GET_ACCOMMODATION_LOCATIONS_SUCCESS,
  GET_ACCOMMODATION_LOCATIONS_FAILED,
  GET_ACCOMMODATION_TYPES,
  GET_ACCOMMODATION_TYPES_SUCCESS,
  GET_ACCOMMODATION_TYPES_FAILED,
  GET_ACCOMMODATION_FACILITIES,
  GET_ACCOMMODATION_FACILITIES_SUCCESS,
  GET_ACCOMMODATION_FACILITIES_FAILED,
  GET_ACCOMMODATION_NAME,
  GET_ACCOMMODATION_NAME_SUCCESS,
  GET_ACCOMMODATION_NAME_FAILED,
  GET_RESTAURANT_SPECIALIZATIONS,
  GET_RESTAURANT_SPECIALIZATIONS_SUCCESS,
  GET_RESTAURANT_SPECIALIZATIONS_FAILED,
  RESET_ADVANCE_FILTER,
  //my qoutation
  GET_MY_QOUTATION,
  GET_MY_QOUTATION_SUCCESS,
  GET_MY_QOUTATION_FAILED,
  RESET_MY_QOUTATION,
  POST_QUOTATION,
  POST_QUOTATION_SUCCESS,
  POST_QUOTATION_FAILED,
  RESET_QUOTATION,
  //payment
  GET_TOBE_PAYED,
  GET_TOBE_PAYED_SUCCESS,
  GET_TOBE_PAYED_FAILED,
  GET_CONFIRMATION_DEMO,
  GET_CONFIRMATION_DEMO_SUCCESS,
  GET_CONFIRMATION_DEMO_FAILED,
  RESET_CONFIRMATION_DEMO,
  GET_CONFIRMATION,
  GET_CONFIRMATION_CANCEL_SUCCESS,
  GET_CONFIRMATION_CANCEL_FAILED,
  GET_CONFIRMATION_SUCCESS,
  GET_CONFIRMATION_FAILED,
  RESET_CONFIRMATION,
  GET_TOPUP,
  GET_TOPUP_SUCCESS,
  GET_TOPUP_FAILED,
  GET_BANK_ACCOUNT,
  GET_BANK_ACCOUNT_SUCCESS,
  GET_BANK_ACCOUNT_FAILED,
  GET_BILLED,
  GET_BILLED_SUCCESS,
  GET_BILLED_FAILED,
  GET_BILLS,
  GET_BILLS_SUCCESS,
  GET_BILLS_FAILED,
  //Transaction
  GET_TOUR_OPERATOR_LIST,
  GET_TOUR_OPERATOR_LIST_SUCCESS,
  GET_TOUR_OPERATOR_LIST_FAILED,
  RESET_TOUR_OPERATOR_LIST,
  GET_TOUR_OPERATOR_PROFILE_LIST,
  GET_TOUR_OPERATOR_PROFILE_LIST_SUCCESS,
  GET_TOUR_OPERATOR_PROFILE_LIST_FAILED,
  SET_ITEM_TRANSACTION,
  RESET_ITEM_TRANSACTION,
  POST_DEMO_CUSTOM,
  RESET_POST_DEMO_CUSTOM,
  POST_DEMO_CUSTOM_FAILED,
  POST_DEMO_CUSTOM_SUCCESS,
  POST_CREATE_CUSTOM,
  RESET_POST_CREATE_CUSTOM,
  POST_CREATE_CUSTOM_FAILED,
  POST_CREATE_CUSTOM_SUCCESS,
  POST_CREATE_CUSTOM_ONBEHALF,
  POST_CREATE_CUSTOM_ONBEHALF_FAILED,
  POST_CREATE_CUSTOM_ONBEHALF_SUCCESS,
  POST_EDIT_QUOTATION,
  POST_EDIT_QUOTATION_SUCCESS,
  POST_EDIT_QUOTATION_FAILED,
  GET_LIST_COMPANY,
  RESET_LIST_COMPANY,
  GET_LIST_COMPANY_SUCCESS,
  GET_LIST_COMPANY_FAILED,
  SIMPLE_REGISTER_COMPANY,
  SIMPLE_REGISTER_COMPANY_SUCCESS,
  SIMPLE_REGISTER_COMPANY_FAILED,
  RESET_SIMPLE_REGISTER_COMPANY,
  GET_USERID_BY_COMPANYCODE,
  GET_USERID_BY_COMPANYCODE_SUCCESS,
  GET_USERID_BY_COMPANYCODE_FAILED,
  RESET_GET_USERID,
  //TourGuide
  SET_GUEST_TOUR_GUIDE,
  //Additional Service
  GET_ADDITIONAL_SERVICE,
  GET_ADDITIONAL_SERVICE_SUCCESS,
  GET_ADDITIONAL_SERVICE_FAILED,
  GET_ADDITIONAL_SERVICE_BY_ID,
  GET_ADDITIONAL_SERVICE_BY_ID_SUCCESS,
  GET_ADDITIONAL_SERVICE_BY_ID_FAILED,
  //Airline Ticket
  GET_LIST_TICKET,
  GET_LIST_TICKET_SUCCESS,
  GET_LIST_TICKET_FAILED,
  RESET_LIST_TICKET,
  GET_TICKET_AIRLINE_BY_ID,
  GET_TICKET_AIRLINE_BY_ID_SUCCESS,
  GET_TICKET_AIRLINE_BY_ID_FAILED
};
