export const GET_AIRPORT = 'GET_AIRPORT';
export const GET_AIRPORT_PENDING = 'GET_AIRPORT_PENDING';
export const GET_AIRPORT_FULFILLED = 'GET_AIRPORT_FULFILLED';
export const GET_AIRPORT_REJECTED = 'GET_AIRPORT_REJECTED';

export const SET_AIRPORT = 'SET_AIRPORT';
export const SET_DRIVING = 'SET_DRIVING';
export const RESET_TRANSPORTATION = 'RESET_TRANSPORTATION';

export const GET_DRIVING = 'GET_DRIVING';
export const GET_DRIVING_PENDING = 'GET_DRIVING_PENDING';
export const GET_DRIVING_FULFILLED = 'GET_DRIVING_FULFILLED';
export const GET_DRIVING_REJECTED = 'GET_DRIVING_REJECTED';

export const GET_DURATION = 'GET_DURATION';
export const GET_DURATION_PENDING = 'GET_DURATION_PENDING';
export const GET_DURATION_FULFILLED = 'GET_DURATION_FULFILLED';
export const GET_DURATION_REJECTED = 'GET_DURATION_REJECTED';

export const GET_LIST_AIRPORT = 'GET_LIST_AIRPORT';
export const GET_LIST_AIRPORT_PENDING = 'GET_LIST_AIRPORT_PENDING';
export const GET_LIST_AIRPORT_FULFILLED = 'GET_LIST_AIRPORT_FULFILLED';
export const GET_LIST_AIRPORT_REJECTED = 'GET_LIST_AIRPORT_REJECTED';

export const GET_TRANSPORTATION_PROFILE_RATINGS =
  'GET_TRANSPORTATION_PROFILE_RATINGS';
export const GET_TRANSPORTATION_PROFILE_RATINGS_PENDING =
  'GET_TRANSPORTATION_PROFILE_RATINGS_PENDING';
export const GET_TRANSPORTATION_PROFILE_RATINGS_FULFILLED =
  'GET_TRANSPORTATION_PROFILE_RATINGS_FULFILLED';
export const GET_TRANSPORTATION_PROFILE_RATINGS_REJECTED =
  'GET_TRANSPORTATION_PROFILE_RATINGS_REJECTED';
export const GET_TRANSPORTATION_PROFILE_CATEGORIES =
  'GET_TRANSPORTATION_PROFILE_CATEGORIES';
export const GET_TRANSPORTATION_PROFILE_CATEGORIES_PENDING =
  'GET_TRANSPORTATION_PROFILE_CATEGORIES_PENDING';
export const GET_TRANSPORTATION_PROFILE_CATEGORIES_FULFILLED =
  'GET_TRANSPORTATION_PROFILE_CATEGORIES_FULFILLED';
export const GET_TRANSPORTATION_PROFILE_CATEGORIES_REJECTED =
  'GET_TRANSPORTATION_PROFILE_CATEGORIES_REJECTED';
export const GET_TRANSPORTATION_PROFILES = 'GET_TRANSPORTATION_PROFILES';
export const GET_TRANSPORTATION_PROFILES_PENDING =
  'GET_TRANSPORTATION_PROFILES_PENDING';
export const GET_TRANSPORTATION_PROFILES_FULFILLED =
  'GET_TRANSPORTATION_PROFILES_FULFILLED';
export const GET_TRANSPORTATION_PROFILES_REJECTED =
  'GET_TRANSPORTATION_PROFILES_REJECTED';
export const GET_TRANSPORTATION_TYPES = 'GET_TRANSPORTATION_TYPES';
export const GET_TRANSPORTATION_TYPES_PENDING =
  'GET_TRANSPORTATION_TYPES_PENDING';
export const GET_TRANSPORTATION_TYPES_FULFILLED =
  'GET_TRANSPORTATION_TYPES_FULFILLED';
export const GET_TRANSPORTATION_TYPES_REJECTED =
  'GET_TRANSPORTATION_TYPES_REJECTED';
export const GET_TRANSPORTATION_SEAT_TYPES = 'GET_TRANSPORTATION_SEAT_TYPES';
export const GET_TRANSPORTATION_SEAT_TYPES_PENDING =
  'GET_TRANSPORTATION_SEAT_TYPES_PENDING';
export const GET_TRANSPORTATION_SEAT_TYPES_FULFILLED =
  'GET_TRANSPORTATION_SEAT_TYPES_FULFILLED';
export const GET_TRANSPORTATION_SEAT_TYPES_REJECTED =
  'GET_TRANSPORTATION_SEAT_TYPES_REJECTED';
export const GET_TRANSPORTATION_UNITS_FILTER =
  'GET_TRANSPORTATION_UNITS_FILTER';
export const GET_TRANSPORTATION_UNITS_FILTER_PENDING =
  'GET_TRANSPORTATION_UNITS_FILTER_PENDING';
export const GET_TRANSPORTATION_UNITS_FILTER_FULFILLED =
  'GET_TRANSPORTATION_UNITS_FILTER_FULFILLED';
export const GET_TRANSPORTATION_UNITS_FILTER_REJECTED =
  'GET_TRANSPORTATION_UNITS_FILTER_REJECTED';
export const RESET_STATUS_TRANSPORTATION = 'RESET_STATUS_TRANSPORTATION';
export const RESET_STATUS_TRANSPORTATION_UNITS_FILTER =
  'RESET_STATUS_TRANSPORTATION_UNITS_FILTER';
