export const GET_AIRPORT = "GET_AIRPORT";
export const GET_AIRPORT_PENDING = "GET_AIRPORT_PENDING";
export const GET_AIRPORT_FULFILLED = "GET_AIRPORT_FULFILLED";
export const GET_AIRPORT_REJECTED = "GET_AIRPORT_REJECTED";

export const SET_AIRPORT = "SET_AIRPORT";
export const SET_DRIVING = "SET_DRIVING";
export const RESET_TRANSPORTATION = "RESET_TRANSPORTATION";

export const GET_DRIVING = "GET_DRIVING";
export const GET_DRIVING_PENDING = "GET_DRIVING_PENDING";
export const GET_DRIVING_FULFILLED = "GET_DRIVING_FULFILLED";
export const GET_DRIVING_REJECTED = "GET_DRIVING_REJECTED";

export const GET_DURATION = "GET_DURATION";
export const GET_DURATION_PENDING = "GET_DURATION_PENDING";
export const GET_DURATION_FULFILLED = "GET_DURATION_FULFILLED";
export const GET_DURATION_REJECTED = "GET_DURATION_REJECTED";

export const GET_LIST_AIRPORT = "GET_LIST_AIRPORT";
export const GET_LIST_AIRPORT_PENDING = "GET_LIST_AIRPORT_PENDING";
export const GET_LIST_AIRPORT_FULFILLED = "GET_LIST_AIRPORT_FULFILLED";
export const GET_LIST_AIRPORT_REJECTED = "GET_LIST_AIRPORT_REJECTED";
