import EStyleSheet from 'react-native-extended-stylesheet';
import { Dimensions, Platform } from 'react-native';

const width = Dimensions.get('window').width;

export default EStyleSheet.create({
  $goldcolor: '$gold',
  $black: 'black',
  $textnoteColor: '$textnote',
  $redcolor: '$red',
  $softblueColor: '$softblue',
  $darkBlueColor: '$darkBlue',
  $greenColor: '$greenpayment',
  tintColorRed: { tintColor: '$red' },
  colorred: { color: '$red' },
  paddingTop0: { paddingTop: 0 },
  marginTop70: { marginTop: 70 },
  paddingBottom120: { paddingBottom: 120 },
  marginTopnegatif10: { marginTop: -10 },
  paddingHorizontal15: { paddingHorizontal: 15 },
  alignEnd: { alignItems: 'flex-end' },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  marginBottom0: { marginBottom: 0 },
  justifyCenter: { justifyContent: 'center' },
  justiftEnd: { justifyContent: 'flex-end' },
  justiftSpace: { justifyContent: 'space-between' },
  marginLeft5: { marginLeft: 5 },
  padding5: { paddingHorizontal: 5, paddingVertical: 5 },
  paddingLeft5: { paddingLeft: 5 },
  positionCloseModal: { alignItems: 'flex-end', paddingRight: 5 },
  positionOrder: {
    paddingRight: 15,
    paddingLeft: 5,
    marginRight: 5,
  },
  marginBottom60: { marginBottom: 60 },
  marginTop60: { marginTop: 60 },
  marginBottom10: { marginBottom: 10 },
  positionSchedule: { marginBottom: 10, marginTop: 5 },
  bottom: {
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  marginTop10Bottom20: {
    marginTop: 10,
    marginBottom: 20,
  },
  marginBottom20: {
    marginBottom: 20,
  },
  bottomHorizontal: {
    paddingHorizontal: 10,
  },
  colorlightGrey2: {
    color: '$lightGrey2',
  },
  iconFrameAdd: {
    width: 40,
    height: 40,
    padding: 10,
    backgroundColor: '$softblue',
    borderRadius: 20,
  },
  tintColorWhite: {
    tintColor: 'white',
  },
  checkBoxStyle: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  containerDataTour: {
    backgroundColor: '#faf4e1',
    paddingVertical: 20,
    alignItems: 'center',
    marginTop: 20,
  },
  containerDataTour1: {
    backgroundColor: '#faf4e1',
    paddingVertical: 20,
    alignItems: 'center',
  },

  cardAccomodation: {
    backgroundColor: '$whitelight',
    width: 250,
    height: 100.7,
    // flex: 1,
    marginBottom: 5,
    marginLeft: 5,
    paddingHorizontal: 10,
    paddingVertical: 10,
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    elevation: 3,
    shadowRadius: 5,
    shadowOpacity: 1.0,
  },
  cardWarning: {
    width: '95%',
    height: 22.7,
    position: 'relative',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '$cardoverlay',
  },
  row: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: 'center',
    flexDirection: 'row',
    width: width,
  },
  // rowNoPadding: {
  //   width: '100%',
  //   flexDirection: 'row',
  // },
  rowGold: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: 'center',
    backgroundColor: '$cardoverlay',
    width: width,
    flexDirection: 'row',
  },
  rowRight: {
    justifyContent: 'flex-end',
    flexDirection: 'row',
    flex: 1,
    width: '90%',
  },
  col45: {
    width: '45%',
  },

  col40: {
    width: '40%',
  },
  col60: {
    width: '60%',
  },
  col65: {
    width: '65%',
  },
  col15: {
    width: '15%',
  },
  col25: {
    width: '25%',
  },
  col20Width: {
    width: '20%',
  },
  col10: {
    width: '10%',
  },
  col5: {
    width: '5%',
  },
  image: {
    width: '90%',
    height: '90%',
  },
  textwrap: { flexWrap: 'wrap' },
  text14: {
    fontSize: 14,
    textAlign: 'left',
  },
  text16: {
    fontSize: 16,
    textAlign: 'left',
  },
  text10: {
    color: 'black',
    fontSize: 10,
    textAlign: 'left',
    flexWrap: 'wrap',
  },
  text12Red: {
    color: '$red',
    fontSize: 12,
  },
  text14Red: {
    color: '$red',
    fontSize: 14,
  },
  text12Gold: {
    color: '$gold',
    fontSize: 12,
  },
  text14Gold: {
    color: '$gold',
    fontSize: 14,
  },
  text12: {
    color: 'black',
    fontSize: 12,
  },

  text18GoldBold: {
    color: '$gold',
    fontSize: 18,
    fontWeight: Platform.OS === 'ios' ? '600' : '300',
  },
  text18GoldPay: {
    color: '$greenpayment',
    fontSize: 18,
    fontWeight: Platform.OS === 'ios' ? '600' : '300',
  },
  text20MustPay: {
    color: '$darkBlue',
    fontSize: 20,
    fontWeight: Platform.OS === 'ios' ? '600' : '300',
  },
  text20TotalPay: {
    color: '$red',
    fontSize: 20,
    fontWeight: Platform.OS === 'ios' ? '600' : '300',
  },
  text: {
    fontSize: 14,
    color: 'black',
    paddingHorizontal: 5,
    paddingVertical: 5,
    textAlign: 'left',
    alignSelf: 'flex-start',
  },
  text18Red: {
    color: '$red',
    // fontFamily: 'Roboto',
    fontSize: 18,
    fontWeight: Platform.OS === 'ios' ? '600' : '300',
  },
  colNoPadding70: {
    width: '70%',
  },
  colNoPadding30: {
    width: '30%',
  },
  bold12: {
    fontWeight: '300',
    fontSize: 12,
  },
  bold14: {
    fontWeight: '300',
    fontSize: 14,
  },
  bold14Red: {
    color: '$red',
    fontWeight: '300',
    fontSize: 14,
  },
  bold16: {
    fontWeight: 'bold',
    fontSize: 16,
  },
  bold16red: { color: '$red', fontWeight: 'bold', fontSize: 16 },
  bold18: {
    fontWeight: '300',
    fontSize: 18,
  },
  bold20: {
    fontWeight: '300',
    fontSize: 20,
  },

  footer: {
    position: 'absolute',
    flex: 0.1,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#f4f4f4',
    shadowOffset: {
      width: 5,
      height: 5,
    },
    zIndex: 0,
    shadowRadius: 10,
    shadowOpacity: 0.5,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: 'hidden',
  },
  row90: {
    flexDirection: 'row',
    width: '100%',
    paddingHorizontal: 5,
    paddingVertical: 5,
  },
  paid: {
    width: '100%',
    height: 30,
    backgroundColor: '$cardoverlay',
    justifyContent: 'center',
  },
  container: {
    width: width,
    height: 80,
    backgroundColor: '$cardoverlay',
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerOnBeHald: {
    width: width,
    height: 20,
    backgroundColor: '$gold',
    justifyContent: 'center',
    alignItems: 'center',
  },

  containerScroll: {
    flex: 1,
    width: '100%',
    marginBottom: 60,
  },
  Scroll: {
    flex: 1,
    width: '100%',
  },
  CardTitle: {
    width: '100%',
    height: 50.3,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },

  //BARU//
  cardRadius: {
    marginBottom: 20,
    width: '90%',
    paddingVertical: 20,
    backgroundColor: '#fff',
    alignSelf: 'center',
    shadowColor: '#f4f4f4',
    shadowOffset: {
      width: 5,
      height: 5,
    },
    zIndex: 0,
    shadowRadius: 10,
    shadowOpacity: 0.5,
    borderRadius: 5,
    overflow: 'hidden',
  },
  cardRadiusTop: {
    width: '90%',
    marginTop: 20,
    paddingVertical: 20,
    backgroundColor: '#fff',
    alignSelf: 'center',
    shadowColor: '#f4f4f4',
    shadowOffset: {
      width: 5,
      height: 5,
    },
    zIndex: 0,
    shadowRadius: 10,
    shadowOpacity: 0.5,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    overflow: 'hidden',
  },
  cardRadiusBottom: {
    backgroundColor: '#252525',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  colPadding20: {
    paddingHorizontal: 20,
  },

  bold24: {
    fontWeight: '300',
    fontSize: 24,
  },
  // bold20: {
  //   fontWeight: '300',
  //   fontSize: 20,
  // },
  topNav: {
    position: 'absolute',
    zIndex: 1,
    alignSelf: 'flex-start',
    paddingLeft: 20,
    paddingTop: 20,
  },
  topNavText: {
    position: 'absolute',
    zIndex: 1,
    alignSelf: 'center',
    justifyContent: 'center',
    paddingBottom: 0,
    paddingTop: 30,
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    overflow: 'hidden',
    height: 70,
    zIndex: 99,
  },
  gradientHeader: {
    width: '100%',
    height: 150,
    position: 'absolute',
  },
  headerText: {
    color: '#252525',
    fontWeight: '300',
    textAlign: 'center',
    fontSize: 16,
  },
  detailText: {
    color: '$gold',
    fontWeight: '300',
    fontSize: 14,
  },
  alignRight: {
    alignItems: 'flex-end',
  },
  rowNoPadding: {
    // paddingHorizontal: 5,
    alignItems: 'center',
    flexDirection: 'row',
    // flex: 1,
    width: '100%',
  },
  rowGreyNoPadding: {
    // paddingHorizontal: 5,
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: '#f5f5f5',
    flex: 1,
    width: '100%',
  },
  row100: {
    paddingHorizontal: 5,
    alignItems: 'center',
    flexDirection: 'row',
    // flex: 1,
    width: '100%',
  },
  colNoPadding: {
    flexDirection: 'column',
    flex: 1,
    width: '100%',
    marginBottom: 20,
  },
  colNoPadding1: {
    flexDirection: 'column',
    flex: 1,
    width: '100%',
  },
  col50: {
    flexDirection: 'column',
    width: '50%',
    alignItems: 'flex-start',
  },
  col70: {
    flexDirection: 'column',
    width: '70%',
    alignItems: 'flex-start',
  },
  col30: {
    flexDirection: 'column',
    width: '30%',
    alignItems: 'flex-start',
  },
  text16GoldBold: {
    color: '$gold',
    fontSize: 16,
    fontWeight: '300',
  },
  text16Gold: {
    color: '$gold',
    fontSize: 16,
  },
  text22Bold: {
    color: '#252525',
    fontSize: 22,
    fontWeight: '300',
  },
  text40Bold: {
    color: '#252525',
    fontSize: 40,
    fontWeight: Platform.OS === 'ios' ? '600' : '300',
  },
  text20: {
    color: '#252525',
    fontSize: 20,
  },
  paddingBottom10: {
    paddingBottom: 10,
  },
  label: {
    borderRadius: 20,
    backgroundColor: '#e6ca6b',
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  innerContainerSort: {
    alignItems: 'flex-start',
    top: '40%',
    width: '100%',
    height: '30%',
    backgroundColor: '$whitelight',
    paddingRight: 20,
    paddingLeft: 20,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  innerContainerReason: {
    alignItems: 'flex-start',
    top: '5%',
    width: '100%',
    height: '95%',
    backgroundColor: '$whitelight',
    paddingRight: 20,
    paddingLeft: 20,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  footerFilter: {
    backgroundColor: '#252525',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 60,
    shadowColor: '#d3d3d3',
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowRadius: 10,
    shadowOpacity: 1,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderTopWidth: 0,
    elevation: 13,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    backgroundColor: '$lightgrey1',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
  },
  innerContainerLoading: {
    height: '50%',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 8,
    shadowColor: '$greylight',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '$background',
    shadowOpacity: 0.3,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  innerContainerSuccess: {
    height: '80%',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 8,
    shadowColor: '$greylight',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '$background',
    shadowOpacity: 0.3,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // modalContainer: {
  //   flex: 1,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   width: '100%',
  //   height: '100%',
  //   backgroundColor: '$lightgrey1',
  // },
  // innerContainer: {
  //   position: 'absolute',
  //   width: '70%',
  //   padding: 20,
  //   backgroundColor: '$whitelight',
  //   paddingRight: 20,
  //   paddingLeft: 20,
  //   paddingHorizontal: 10,
  //   paddingVertical: 10,
  //   borderRadius: 20,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
  containerImageModal: {
    width: 200,
    height: 200,
  },
  textAreaContainer: {
    borderColor: 'grey',
    borderWidth: 1,
    padding: 5,
    width: '100%',
  },
  textAreaContainerDisable: {
    borderColor: 'grey',
    borderWidth: 1,
    padding: 5,
    width: '100%',
    backgroundColor: '$disabel',
  },
  textArea: {
    height: 150,
    width: '100%',
    justifyContent: 'flex-start',
  },
  textAreaDisable: {
    backgroundColor: '$disabel',
    height: 150,
    width: '100%',
    justifyContent: 'flex-start',
  },
  marginTopBottom10: {
    marginTop: 10,
    marginBottom: 10,
  },
  stylesPageSchedule: {
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    width: Dimensions.get('window').width,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    flexDirection: 'row',
    backgroundColor: '#fff',
  },
  containerHighlightOrderedDetail: {
    backgroundColor: '#FFECAB',
  },
  cardRadiusBottomTotalPrice: {
    backgroundColor: '#ccc',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
});
