// Login
export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_PENDING = 'POST_LOGIN_PENDING';
export const POST_LOGIN_FULFILLED = 'POST_LOGIN_FULFILLED';
export const POST_LOGIN_REJECTED = 'POST_LOGIN_REJECTED';
export const RESET_LOGIN_STATUS = 'RESET_LOGIN_STATUS';
export const SET_TOKEN = 'SET_TOKEN';
